### ISSUE TITLE
Update styles to use the new module system is Sass

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#1008]
## Description

The `@import` declaration has been deprecated in favor of the new module system with `@use` to fix a lot of issues. Full blog available [here](https://sass-lang.com/blog/the-module-system-is-launched).

It looks like I have until October 1, 2022 to fully adopt according to the blog and `@import` will be deprecated October 1, 2021.

## Initial Highlights

With the new support for `_index.scss` files, I can simplify imports a lot.

```diff
-@import '~@react-md/utils/dist/mixins';
+@use '~@react-md/utils' as utils;

-@include react-md-utils;
+@include utils.create;       // Not entirely sure yet for naming on this

 .my-class {
-  @include rmd-utils-rtl-auto(left, translateX(-50%));
+  @include utils.rtl-auto(left, translateX(-50%));
 }
```

Or when not using webpack:

```diff
-@import '@react-md/utils/dist/scss/mixins';
+@use '@react-md/utils/native' as utils;  // might do @react-md/utils/dist/scss for this or another name

-@include react-md-utils;
+@include utils.create;       // Not entirely sure yet for naming on this

 .my-class {
-  @include rmd-utils-rtl-auto(left, translateX(-50%));
+  @include utils.rtl-auto(left, translateX(-50%));
 }
```

With the `@forward` rule, I can actually have some functions, mixins, and variables as private with the `hide` functionality.

```scss
$height: 1.5rem !default
$width: 80% !default;

/// @private
$internal-calc-usage: calc($height - $width);
```

```scss
@forward 'variables' hide internal-calc-usage;
```

### Details

- means that consumers of this library will have to use [sass](https://www.npmjs.com/package/sass) instead of [node-sass](https://www.npmjs.com/package/node-sass) -- also looks like `node-sass` has been deprecated
  - also might require the use of `fibers` due to performance issues? [Infos](https://sass-lang.com/dart-sass)
- with the new module system, I'll no longer need to prefix everything with `rmd-` which will be pretty nice
- might be good to figure out if I can create a codemod for this
- there is a [sass-migrator](https://sass-lang.com/documentation/cli/migrator) which can help with the transition for both me and users of this library
- simplifies imports to `~@react-md/{{PACKAGE_NAME}}` or `@react-md/{{PACKAGE_NAME}}/ instead of `@react-md/{{PACKAGE_NAME}}/dist/mixins`

### Thoughts

- I'm hoping to finish implementing the remaining missing features from v1 before tackling this
- might be good to figure out how much the custom properties are used as well as how useful the prefixes are for them. I can save 2.5kb at the time of writing this by switching them to 1-4 character strings
- might also be good to see if it's still worthwhile to keep the `rmd-` prefix on css classes and just come up with shorter names
- hopefully this fixes some of the compilation performance issues in webpack

**Comment by stickfigure** [comment]
Some random feedback from a user who only barely understands the issues:

 * 2.5k is not significant to us; our SPA is >2.5MB. Would hate to sacrifice clarity for that small of a gain.

 * I didn't know about sass vs node-sass; just switched from node-sass to sass and found compilation not significantly different (with fibers). Webpack startup went from ~90s to ~110s; individual changes seem to be around the same, typically around 30s. We do notice one weird visual change in the text/icon spacing in menus, which I'll open an issue for.

 * We twiddle the rmd classes in our css. I know we're not supposed to, and we try to avoid it, but we have barely any idea how to use the sass mixins. I can open dev tools and immediately see the CSS selectors I need to override, that's easy.

**Comment by mlaursen** [comment]
Thanks! Feedback like this is helpful for me since I'm working on this project alone and don't have people to sanity check me and throw ideas at.

I like the rmd prefixes for the same reason, but wasn't sure if anyone else debugged that way/liked the verbosity. I think I'll keep them unless others chime in.

I really need to expand the documentation/examples for the mixin system -- I really like it (but I did make it) since it solves a lot of styling/overriding I've encountered at work. Maybe a screencast or more real world demos would help for that part.

**Comment by novym** [comment]
FYI, There are deprecation warnings currently in `react-md` V1 and V2

V1 warnings (react-md@1.16.1)
```
DEPRECATION WARNING on line 1491, column 7 of node_modules/react-md/src/scss/_colors.scss: 
@elseif is deprecated and will not be supported in future Sass versions.

Use "@else if" instead.
     ╷
1491 │     } @elseif $fallback-color == null {
     │       ^^^^^^^
     ╵
```

V2 warnings (react-md@2.8.3)
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($rmd-button-icon-size - $rmd-icon-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
51 │   (($rmd-button-icon-size - $rmd-icon-size) / 2);
   │    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@react-md/app-bar/dist/_variables.scss 51:4  @import
    node_modules/@react-md/app-bar/dist/_functions.scss 6:9   @import
    node_modules/@react-md/app-bar/dist/_mixins.scss 10:9     @import
    src/scss/_react-md-setup.scss 11:9                        @import
    src/index.scss 3:9                                        root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(max($back-luminance, $front-luminance), min($back-luminance, $front-luminance))

More info and automated migrator: https://sass-lang.com/d/slash-div
    ╷
193 │     @return max($back-luminance, $front-luminance) /
    │ ┌───────────^
194 │ │     min($back-luminance, $front-luminance);
    │ └──────────────────────────────────────────^
    ╵
    node_modules/@react-md/theme/dist/_color-a11y.scss 193:11  rmd-theme-contrast()
    node_modules/@react-md/theme/dist/_color-a11y.scss 314:20  rmd-theme-best-contrast-color()
    node_modules/@react-md/theme/dist/_variables.scss 53:24    @import
    node_modules/@react-md/theme/dist/_helpers.scss 7:9        @import
    node_modules/@react-md/theme/dist/_functions.scss 7:9      @import
    node_modules/@react-md/elevation/dist/_mixins.scss 5:9     @import
    node_modules/@react-md/button/dist/_mixins.scss 5:9        @import
    src/components/FilterChip/FilterChip.scss 2:9              root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($tracking, $font-size * 16)

More info and automated migrator: https://sass-lang.com/d/slash-div
   ╷
79 │   @return $tracking / ($font-size * 16) * 1em;
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/@react-md/typography/dist/_variables.scss 79:11   rmd-typography-get-letter-spacing()
    node_modules/@react-md/typography/dist/_variables.scss 305:23  @import
    node_modules/@react-md/typography/dist/_mixins.scss 8:9        @import
    node_modules/@react-md/button/dist/_mixins.scss 9:9            @import
    src/components/FilterChip/FilterChip.scss 2:9                  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2
```

**Comment by mlaursen** [comment]
This should now be partially supported in v3.0.0. I created #1223 to implement full support for the scoped packages.
