### ISSUE TITLE
Nothing return from avatar sass mixin

### ISSUE THREAD

**Issue by rakibulalam** [mlaursen/react-md#1013]
I am trying to customize my own avatar style. unfortunately sass mixin nothing returns from.

```
@import '~@react-md/avatar/dist/mixins';


.container {
  $rmd-avatar-border-radius: 50% !default;
  $rmd-avatar-line-height: 1.75rem;
  $rmd-avatar-color: $rmd-grey-100 !default;
  $rmd-avatar-background-color: $rmd-grey-700 !default;
  $rmd-avatar-border-color: rgba(0, 0, 0, 0.12);
  $rmd-avatar-size: 2.5rem !default;
  $rmd-avatar-font-size: 1.5rem !default;
  $rmd-avatar-line-height: 1.75rem;

  $rmd-avatar-theme-values: (
    background-color: $rmd-avatar-background-color,
    border-color: $rmd-avatar-border-color,
    border-radius: $rmd-avatar-border-radius,
    color: $rmd-avatar-color,
    font-size: $rmd-avatar-font-size,
    size: $rmd-avatar-size,
  ) !default;

  @include react-md-avatar();
}
```

**Comment by mlaursen** [comment]
Can you provide some information?

- Are you trying to override the default styles for the avatar or create a "one-off" avatar component with different styles?
- Is your example in a CSS Modules file?

From the [react-md-avatar SassDoc](https://react-md.dev/packages/avatar/sassdoc#avatar-mixin-react-md-avatar) you can see the code that it generates would be something like:

```scss
.container .rmd-avatar {
  // styles
}

.container .rmd-avatar__image {
  // styles
}
```

**Comment by rakibulalam** [comment]
I am using mono repo. independently need to modify the avatar component to making our own design system. In that same way, I modified the grid system. But when I am trying to add the mixin of avatar its returns nothing. Yeah, I am using css module system by using scss.

**Comment by rakibulalam** [comment]
Oh, I am really sorry I forget the debug styles object for the CSS modules. thanks for your reply :)
