### ISSUE TITLE
sass vs node-sass visual difference

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#1015]
rmd 2.4.3, chrome 86.

Exact same code, the only difference is replacing node-sass with sass+fibers in the package.json.

The node-sass version of a menu, with spacing between text and icon:

https://monosnap.com/file/2CeDgaOLTNthsTUeof3M0INGeafvcq

The sass version seem to be missing the spacing:

https://monosnap.com/file/GkjQlIrur72aFHWYVfgEONFIKJCO3T

This seems to work in one place but not the other:
```
.rmd-icon--before {
    margin-right: var(--rmd-icon-text-spacing, 0.5rem);
}
```

**Comment by mlaursen** [comment]
Darn.. This probably means `sass` doesn't like [this mixin](https://github.com/mlaursen/react-md/blob/972d9a96cfd85ead408c8fe4eac29155f49b72b8/packages/list/src/_mixins.scss#L155-L175) if all the other text icon spacing works. Wonder if there's a difference in how strings/escaping between the two.
