### ISSUE TITLE
[TextField] Label overlapping value when a auto fill

### ISSUE THREAD

**Issue by lindomar-oliveira** [mlaursen/react-md#1043]
I'm using version 2.5.1, and I have this problem described in the title.

In this sandbox is the reproduction: [https://codesandbox.io/s/form-example-text-field-example-forked-oe538](https://codesandbox.io/s/form-example-text-field-example-forked-oe538).

**Comment by lindomar-oliveira** [comment]
@mlaursen In the **TextArea** component the problem still persists, even after the update.

**Comment by mlaursen** [comment]
Whoops.. That's what I get for only writing new tests for the `TextField`. I'll check out the `TextArea` again
