### ISSUE TITLE
[Chip] Is there some way to make a non-clickable chip?

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#1046]
Maybe this is a feature request. I'd like chips that look like chips but aren't clickable and don't make the cursor into a hand.

I'm currently using Chip, disabled, overriding color and background-color to the normal chip colors. It would be nice if this was a simple property.

**Comment by mlaursen** [comment]
Hmm, would you be able to describe the use case a bit for me? I'd be happy to implement this if I can understand how it should be used. Seems like it might be able to render the chip as an element other than a button for this? 

The material design docs mostly make chips as intractable elements and I'm not too imaginative with use cases.

**Comment by stickfigure** [comment]
No problem. Here I'm using chips to show available sizes for a product:

![image](https://user-images.githubusercontent.com/162508/105065756-0e9e0100-5a33-11eb-8ae9-544584165310.png)

**Comment by mlaursen** [comment]
Great, thanks! I think this usecase makes sense to me.

I can probably target this for the next minor release since planning out the Date/Time pickers has me a bit more stumped than I'd hoped.
