### ISSUE TITLE
Question: Is "toggleable-mini" layout mode functional?

### ISSUE THREAD

**Issue by RatikantHM** [mlaursen/react-md#1067]
Hi,

I tried with below options for desktop:

`desktopLayout='toggleable-mini'
 largeDesktopLayout='toggleable-mini'`

But both seems not working. what I want is when user clicks a "collapse" button, it should show the nav with icons only (without link text). Is this feature available, if yes, can you please provide any reference?

Thanks a lot in adv.!

**Comment by RatikantHM** [comment]
Ok, I saw in few of the examples, it's mentioned "temporary-mini" and "toggleable-mini" are not yet supported. Is there any plan when this will be functional?

**Comment by mlaursen** [comment]
Ahh yeah, sorry. I haven't implemented the mini variants yet. I'm thinking I'll have them available in the 2.7.0 or 2.8.0 release.

I've been running into some scope creep issues with these since I keep wanting to add a bit more functionality and customization as I play around with it.
