### ISSUE TITLE
Question: useAppSize equivalent for class based component?

### ISSUE THREAD

**Issue by RatikantHM** [mlaursen/react-md#1072]
Hi,

I have a case where I need to set grid span for 2 grid-list depending on device type (like for mobile grid 1 will have span 1, and grid 2 will have span 3; for tablet grid 1 will have span 2 and grid will have span 4 etc). 

I am planning to detect the device just like useAppSize() hook for FC. Is there any equivalent of useAppSize() to use in class based component?

Thanks!

**Comment by mlaursen** [comment]
Unfortunately not. You could probably write a higher-order-component for this though to provide the `AppSize` as props though:

```js
export function withAppSize(Component) {
  return function ComponentWithAppSize(props) {
    const appSize = useAppSize();

    return <Component {...props} {...appSize} />;
  }
}

class Example extends React.Component {
  render() {
    const { isPhone, isTablet, isDesktop, isLargeDesktop, isLandscape } = this.props;

    return // implementation
  }
}

export default withAppSize(Example);
```
