### ISSUE TITLE
Dark theme elevation feature overrides custom background colors

### ISSUE THREAD

**Issue by rafaelbrier** [mlaursen/react-md#1075]
The SASS variable of some components are being overridden when using dark Theme.
![image](https://user-images.githubusercontent.com/22086005/108607522-9d3dcf00-739f-11eb-890a-c44b34839f57.png)

1) Look, the image shows a style ".dark-theme .rmd-toast" where the variable "--rmd-theme-background" are being set again for some reason. 

2) Below at the class ".dark-theme" i globally defined that variable.

3) The code that i use for theme switch:
```
// Uses System Preference
@media (prefers-color-scheme: dark) {
    :root {
        @include rmd-theme-dark;
    }
}

@media (prefers-color-scheme: light) {
    :root {
        @include rmd-theme-light;
    }
}

// Class for global theme change
.dark-theme {
    @include rmd-theme-dark;
}

.light-theme {
    @include rmd-theme-light;
}
```

**What is the expected behavior?**

The variable should not be overridden in the dark theme.

**A little about versions:**  
Windows
Chrome
"react-md": "^2.5.3"

**Comment by mlaursen** [comment]
Whoops, this was an unintended side-effect of using [@mixin rmd-theme-dark-elevation-styles](https://github.com/mlaursen/react-md/blob/24e5df14c731411d7691253383435036326407b5/packages/theme/src/_mixins.scss#L63-L89) and [@mixin rmd-theme-dark-elevation](https://github.com/mlaursen/react-md/blob/24e5df14c731411d7691253383435036326407b5/packages/theme/src/_mixins.scss#L91-L108) to implement these changes. I'll introduce new SCSS variables to help solve this as well as reduce the specificity for the dark elevation styles.

This bug current affects:

- `@react-md/alert`
- `@react-md/card`
- `@react-md/dialog`
- `@react-md/form` (temporary `Listbox` only)
- `@react-md/menu`
- `@react-md/sheet`

**Comment by rafaelbrier** [comment]
Thank you for the clarification! I'll disable the dark elevation for now.
