### ISSUE TITLE
Can't import the module

### ISSUE THREAD

**Issue by cgevokins** [mlaursen/react-md#1086]
When I do this.

`
import {
    Tree,
    useTreeItemSelection,
    useTreeItemExpansion,
} from "@react-md/tree";`

I cannot load my component. 

Getting:
`Uncaught TypeError: Object(...) is not a function`
`DevTools failed to load SourceMap: Could not load content for http://localhost:3000/Portal.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`
`DevTools failed to load SourceMap: Could not load content for http://localhost:3000/getItemsFrom.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**To Reproduce** Steps to reproduce the behavior:

1. npm install @react-md/tree
2. import module as above
3. npm start

**Expected behavior** 
Can import module.

**Screenshots** If applicable, add screenshots to help explain your problem.
-

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 88.0.4324.190

**Smartphone (please complete the following information):**
-

**Comment by mlaursen** [comment]
I think this might be an issue with your setup since I'm unable to reproduce:
- https://codesandbox.io/s/awesome-snowflake-yz8c2?file=/src/App.tsx
