### ISSUE TITLE
Is it possible to see some of your internal example code?

### ISSUE THREAD

**Issue by grimunit** [mlaursen/react-md#116]
I'm currently trying to implement the FileUpload component and going off of your example. Trying to understand exactly how the interaction between the CSSTransitionGroup and your UploadedFileCard work. Not sure how you're handling only targeting the 'X' in the top right of the card with the _hanldeListClick function. Tried finding your UploadedFileCard in the repo but I guess you don't have some of those example internals anywhere visible. Maybe nudging me in the right direction to know how I can do it myself if you don't want to go through the trouble of exposing all the example helper code. I already tried the CSSTransitionGroup documentation and didn't help answer that piece. 

Also thanks for all the effort you've put into this, the example code itself is amazingly valuable.

**Comment by mlaursen** [comment]
Ahh sorry about that. I didn't want to have all of the other code visible to try to keep it small and I hacked that card a bit.. Doesn't work with all file types :). My demo website has it's own [github](/mlaursen/react-md-docs). It's really a *lazy* way of testing my project as a separate dependency.

The `UploadedFileCard` is defined [here](/mlaursen/react-md-docs/blob/master/src/js/components/file-inputs/UploadedFileCard.jsx) and he only thing the `CSSTransitionGroup` is doing is added a small `scaleY` animation when a file is added or removed so you can skip over that. Let me know if there are any more questions; I'll try to help out.

**Comment by grimunit** [comment]
Awesome I got everything working now, knowing about that repo is super helpful thank you.
