### ISSUE TITLE
Typo in _cards.scss line 12

### ISSUE THREAD

**Issue by vinaypuppal** [mlaursen/react-md#123]
you missed 'n' in "@extend" on `line 12` of  `_cards.scss`

**Comment by vinaypuppal** [comment]
**Checkout here:**
 https://github.com/mlaursen/react-md/blob/3f8330b978f8b796f5bd60f2624c331614e70cde/src/scss/components/_cards.scss#L11-L13

**Comment by mlaursen** [comment]
Thanks, I will fix this for version `0.3.4`. Hopefully it will be released later tonight.

**Comment by mlaursen** [comment]
Release 0.3.4 has been released with this fix.
