### ISSUE TITLE
How to use the documentation for packages? am i missing something?

### ISSUE THREAD

**Issue by scobby** [mlaursen/react-md#1396]
**Describe the bug** 
Cant use the documentation and implement for a example for a select field

**To Reproduce** 

1. Go to 'https://react-md.dev/packages/form/select-field-demos#select-example-title'
2. Change the appearance of the demo 
3. Where to find generated configuration for that item?

**Expected behavior** 
In general the documentation is nice, but not easy to handle, because only in very less examples i can copy example code.

Demo Code:
Even in the Demo Section i would expect that i get a generated code for that particular selected configuration.
And if i click on the code view for many examples, they are generated from the configuration and not easy to use.

Code for Button:
For example for Button its just "<Button>Button</Button>"

So am i missing something? is there a better documentation with example code for the packages?
Currently i have to do relative big research on how to those packages, is this intended?

**Comment by mlaursen** [comment]
Ahh, whoops. Thanks for letting me know. It looks like I forgot to add simple examples for the Select components and mostly focused on trying to showcase the theming and features. I'll update the documentation site to show some simple examples to help out.

**Comment by scobby** [comment]
Switched to react-suite. Have a look at that documentation. Clean selfexplaining and good examples to copy. Parameters at bottom. 

Von meinem Smartphone 
gesendet
