### ISSUE TITLE
SassError: argument `$color` of `red($color)` must be a color

### ISSUE THREAD

**Issue by Emmijozzy** [mlaursen/react-md#1422]
ERROR in ./src/assets/scss/themes.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[0].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].oneOf[7].use[4]!./src/assets/scss/themes.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: argument `$color` of `red($color)` must be a color
        on line 185 of node_modules/bootstrap/scss/_functions.scss, in function `red`
        from line 185 of node_modules/bootstrap/scss/_functions.scss, in function `luminance`
        from line 174 of node_modules/bootstrap/scss/_functions.scss, in function `contrast-ratio`
        from line 159 of node_modules/bootstrap/scss/_functions.scss, in function `color-contrast`
        from line 7 of node_modules/bootstrap/scss/_accordion.scss
        from line 29 of node_modules/bootstrap/scss/bootstrap.scss
        from line 15 of src/assets/scss/config/saas/bootstrap.scss
        from line 2 of src/assets/scss/themes.scss
>>     "r": red($color),

   ---------^

SassError: SassError: argument `$color` of `red($color)` must be a color

**Comment by mlaursen** [comment]
Could you provide some more information or code for the `src/assets/scss/themes.scss` file? By looking at the stack trace, it looks like this is an issue in `bootstrap` and not this library.
