### ISSUE TITLE
Icon names are off by one within the material icons docs.

### ISSUE THREAD

**Issue by arminbro** [mlaursen/react-md#1423]
**Describe the bug** A clear and concise description of what the bug is.
- On the material-icons demo page, I see many of the icon names are off by one so that the previous icon matches up to the following icon in the list. 

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://react-md.dev/packages/material-icons/demos
2. Scroll down, and you should see the icons/labels are mismatched by one.

**Expected behavior** A clear and concise description of what you expected to
happen.
- The names of the icons should match their associated icons. So if we take a look at the screenshot below, the first icon on the left, should be `Archive`, and on the right, the label should be `ArrowBack`.

**Screenshots** If applicable, add screenshots to help explain your problem.
- <img width="400" alt="Screen Shot 2022-08-04 at 10 40 50 AM" src="https://user-images.githubusercontent.com/3334599/182894828-089db934-e269-4c49-b911-19a58c0abfa3.png">

**Desktop (please complete the following information):**
- OS: macOS Monterey (12.4)
- Browser: FireFox (v103.0.1), Chrome (v104.0.5112.79)

**Comment by mlaursen** [comment]
Thanks for reporting this issue. Looks like it was an issue around different order for `Object.entries()` between node and the browser which caused it to be off after SSR. This fix should be live in about 20 minutes.

**Comment by arminbro** [comment]
Excellent, thanks for the quick turnaround!
