### ISSUE TITLE
Do not display check icon when chip is not selected in Filter Chips

### ISSUE THREAD

**Issue by lpb313** [mlaursen/react-md#1432]
The check icon is visible on the filter chips demo when the chips are not selected :
https://codesandbox.io/s/fv1fpu

![Capture](https://user-images.githubusercontent.com/51735387/204054361-3eef142c-580f-45d4-a04a-3697ded095d7.PNG)

**Comment by MarekPrim** [comment]
Tested this in my app, the icon dissapears when the ***disableIconTransition*** is set to true.
