### ISSUE TITLE
React-MD doesn't work with Next.js

### ISSUE THREAD

**Issue by frol** [mlaursen/react-md#150]
Could you, please, help to debug the error I receive when I use React-MD in [Next.js](https://github.com/zeit/next.js) project?

Here is the `pages/index.js`:

```jsx
import React from 'react'
import Head from 'next/head'
import { RaisedButton } from 'react-md/lib/Buttons'

export default class App extends React.Component {
  handleClick() {
    console.log("clicked!")
  }
  render() {
    return <div>
      <Head>
        <link rel="stylesheet" href="https://npmcdn.com/react-md/dist/react-md.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons" />
      </Head>
      <div>
        <RaisedButton label="Hello, World!" onClick={this.handleClick} />
      </div>
    </div>
  }
}
```

Here are the npm dependencies:

```
$ npm install --save next react-md react-addons-transition-group react-addons-pure-render-mixin react-addons-css-transition-group
```

On page load I see the following warnings:

```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
Warning: getInitialState was defined on ReactTransitionGroup, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
```

The first warning points to this line: https://github.com/mlaursen/react-md/blob/bec6b087eb0a6af38f0a0613d25d8a17f6c7b0a6/src/js/Inks/injectInk.js#L243. However, I couldn't locate the real source of the second warning.

And here is what I get on a button click:

```
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded
Uncaught TypeError: Cannot read property 'componentWillLeave' of undefined
```

The line of code where the error occurs is inside React: https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/src/addons/transitions/ReactTransitionGroup.js#L194

I do get `clicked!` logged, but the "bubble" animation doesn't work.

It seems that something magical happens and it feels like there are two Reacts are loaded somehow, so the ref keys are not registered.

*NOTE: I have also opened an issue on Next.js project: https://github.com/zeit/next.js/issues/196*

**Comment by mlaursen** [comment]
Since I don't know anything about the Next.js project, it might be a little hard for me to debug. But I have a couple of questions that might be able to help.

1. Does this work?

```js
import React form 'react';
import TransitionGroup from 'react-addons-transition-group';

class Test extends React.Component {
  componentWillEnter(done) {
    done();
  }
  componentWillLeave(done) {
    done();
  }

  render() {
    return <div ref={woop => console.log(woop)} />;
  }
}

export default class App extends React.Component {
  render() {
    return <div>
      <Head>
        <link rel="stylesheet" href="https://npmcdn.com/react-md/dist/react-md.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons" />
      </Head>
      <TransitionGroup>
        <Test ref={test => console.log(test)} />
      </TransitionGroup>
    </div>
  }
}
```

2. Does this problem still occur if you add an `onClick` handler to the `Card` component?
3. If the following does not, what happens if you add a `ref` ?

I can look into this more deeply once I finish my `v1.0.0` release.

**Comment by frol** [comment]
This doesn't work; here is the console log:

```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
Warning: getInitialState was defined on ReactTransitionGroup, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
<div data-reactid="4"></div>
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded
```

**Comment by frol** [comment]
@mlaursen Thank you for your help! I think, it is not React-MD bug, so I will close this issue, but if you have an idea of what and how this can be fixed, you are welcome to the new bug I have opened on Next.js: https://github.com/zeit/next.js/issues/204
