### ISSUE TITLE
UMD CSS is broken in 1.0.0-alpine

### ISSUE THREAD

**Issue by frol** [mlaursen/react-md#151]
The UMD CSS link, https://unpkg.com/react-md/dist/react-md.css, redirects to https://unpkg.com/react-md@1.0.0-alpha/dist/react-md.css, which returns 404 with the following error:

```
Not found: file "/dist/react-md.css" in package react-md@1.0.0-alpha
```

**Comment by mlaursen** [comment]
Sorry that's my bad. I couldn't figure out how to use the `npm dist-tag` correctly so the UMD for `react-md.css` no longer exists. With the `v1.0.0` release, there are now 255? (18 * 15) precompiled themes available.

You can either link by:
- specifying the pre `v1.0.0` release: https://unpkg.com/react-md@0.3.7/dist/react-md.css (this is how it was working until this alpha)
- or by continue using the latest https://unpkg.com/react-md/dist/react-md.PRIMARY-SECONDARY.min.css

So if you want teal and cyan as your colors, you could link with https://unpkg.com/react-md/dist/react-md.teal-cyan.min.css

**Comment by mlaursen** [comment]
I'm actually going to do a quick patch to add the pre-v1.0.0 files back.

**Comment by mlaursen** [comment]
I don't know how long it'll take for unpkg to refresh the `latest` tag from npm, but it _should_ eventually update and the original https://unpkg.com/react-md/dist/react-md.css should redirect to https://unpkg.con/react-md@1.0.0-alpha.1/dist/react-md.css

**Comment by frol** [comment]
Yes, it is updated now! Thank you!
