### ISSUE TITLE
JS in 1.0.0 alpha UMD builds is broken

### ISSUE THREAD

**Issue by frol** [mlaursen/react-md#152]
Just copy and open the UMD example, and nothing will be displayed, but the error in the console:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

*NOTE: I haven't tested npm packages, as I am still not comfortable enough with this Node.JS world.*

**Comment by mlaursen** [comment]
It looks like I messed something up with the UMD build (I'm new to the UMD World). Using `ReactMD.default` works instead of just `ReactMD`. I'm not sure why it isn't working anymore since it is the same build as before. I'll look into it and get that fixed. Here is the example I used for the `v1.0.0-alpha` version.

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/react-md/dist/react-md.deep-purple-pink.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons|Roboto:400,500,700">
  </head>
  <body>
    <div id="app"></div>
		<script src="https://unpkg.com/react/dist/react-with-addons.min.js"></script>
    <script src="https://unpkg.com/react-dom/dist/react-dom.min.js"></script>
    <script src="https://unpkg.com/react-md/dist/react-md.min.js"></script>
    <script>
const MyAwesomeComponent = React.createClass({
  render() {
    return React.createElement(ReactMD.default.Button, { label: 'Hello', flat: true });
  }
});
ReactDOM.render(React.createElement(MyAwesomeComponent), document.getElementById('app'))
    </script>
  </body>
</html>
```

**Comment by frol** [comment]
I am new to this whole new JS world, so I appreciate your help, and I hope I don't bother you too much.

**Comment by mlaursen** [comment]
No worries! I'm glad someone else is interested in my lib, it's gotten to be a bit hard to find every bug by myself so this is helpful. UMD had been an afterthought :/

**Comment by mlaursen** [comment]
Ok, it should all be fixed now. I published `v1.0.0-alpha.2`. So once unpkg refreshes, you should be able to use the UMD build without the `.default`.

**Comment by frol** [comment]
Yep, it is working now!

Heads up: Please, fix the UMD example in the docs to include the closing `</script>` for the last chunk of code.

**Comment by mlaursen** [comment]
Oof. Thanks! I'll push up some changes later tonight that will include that.
