### ISSUE TITLE
Documentation routes filenames are not in line with the code

### ISSUE THREAD

**Issue by frol** [mlaursen/react-md#155]
This is related to React-MD 1.0.0.

There are the following files:

* `docs/src/shared/routes/Components.js`
* `docs/src/shared/routes/Customization.js`
* `docs/src/shared/routes/DiscoverMore.js`
* `docs/src/shared/routes/GettingStarted.js`
* `docs/src/shared/routes/GetMarkdownPage.js`
* `docs/src/shared/routes/GetSassDocPage.js`
* `docs/src/shared/routes/GettingStarted.js`

But the `index.js` includes these files fir the first letter in lowercase, which results in build errors:

```
    ERROR in ./src/shared/routes/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./gettingStarted in /tmp/react-md/docs/src/shared/routes
     @ ./src/shared/routes/index.js 31:16-43
```

There is also a `GoogleLogo.svg` in `src/shared/imgs/GoogleLogo.svg`, which is imported as `googleLogo.svg`.

**Comment by mlaursen** [comment]
Darn. I think this is a problem when I merged the new documentation site into the docs folder. It's lowercase on my filesystem so I never ran into a problem and there are sometimes bugs where file name case isn't enforced. I'll look into fixing it today.

**Comment by mlaursen** [comment]
This should be fixed now. Going to close.
