### ISSUE TITLE
Tooltips are rotated along with the elements

### ISSUE THREAD

**Issue by frol** [mlaursen/react-md#156]
*This is only reproducible in React-MD 1.0*

Here is the video of the bug I see in the latest docs (built on my laptop):

![preview](https://cloud.githubusercontent.com/assets/304265/20392702/b26536ea-ace1-11e6-8569-dcf53952af84.gif)

**Comment by mlaursen** [comment]
This one is actually going to be pretty hard to fix. I keep pushing it back in priority. The CSS spec doesn't really have anyway to prevent a single child from inheriting the `transform` property. The previous versions of react-md didn't actually use the rotate transition with the code blocks so it didn't appear before.

I'll try thinking about this some more to see if there is a fix. It might just be to prevent the flip transition if there is a tooltip :/ Don't really like that though.

**Comment by mlaursen** [comment]
This should be fixed now (if you use tooltips in the `md-collapser and md-collapser--flipped`). Unfortunately, this isn't a fix-all solution if the rotation happens outside of this use case. The code can just be duplicated in the referenced commit though.

I am going to mark this as closed.

**Comment by frol** [comment]
Thank you!
