### ISSUE TITLE
Icons not working 

### ISSUE THREAD

**Issue by JustasPolis** [mlaursen/react-md#181]
Hello, 

having issues with icons, f.e 

``
     <Button raised primary label="Talk Dirty to Me" iconClassName="fa fa-hand-spock-o" />
``

it's not working. Tried to import material-icons via index.html, webfontloader, no luck.

Am I doing something wrong or it's some bug ?

**Comment by timworx** [comment]
Hey @JustasPolis - Those are FontAwesome icons, not material-icons. material-icons are used with this syntax `<FontIcon>home</FontIcon>` ([source](https://react-md.mlaursen.com/components/font-icons))

For that sake of testing/verifying toss this in your index.html:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
```

**Comment by JustasPolis** [comment]
@timworx  Thanks ! Somehow missed that.

**Comment by timworx** [comment]
Glad I could help! 
I also responded to your post on Gitter about create react app (I'm using it as well)
