### ISSUE TITLE
Slider step verification is floating point vulnerable

### ISSUE THREAD

**Issue by CombatCode** [mlaursen/react-md#184]
Hi, 
can we somehow workaround floating point issue when dealing with sider ? When Slider instance will take as arguments e.g.:
```
value : 1
step : 0.01
```
it will produce an error:
```warning.js?8a56:36 Warning: Failed prop type: The 'value' prop on 'Slider' should be a number divisible by the 'step' prop. The current value is '1' and the 'step' is '0.1'.```

Warning message is generated by : 
 https://github.com/mlaursen/react-md/blob/master/src/js/Sliders/Slider.js#L259 
```} else if (props.defaultValue % step !== 0) {```

**Comment by daturon** [comment]
This happens because 1 % 0.01 = 0.00999999999999998

**Comment by daturon** [comment]
https://github.com/mlaursen/react-md/pull/185

**Comment by mlaursen** [comment]
I added some more tests to verify the changes. Should be good for the v1.0.1 release when it is finished.

**Comment by nbolten** [comment]
As of version 1.0.14, I'm getting a floating point warning for a discrete slider with these settings:

    <Slider
      discrete
      discreteTicks={0.5}
      id='test'
      label='Test'
      defaultValue={8}
      max={10}
      step={0.5}
      valuePrecision={1}
    />

This is the error I'm getting:
`warning.js:36 Warning: Failed prop type: The 'defaultValue' prop on 'Slider' should be a number divisible by the 'step' prop. The current value is '7.000000000000001' and the 'step' is '0.5'.`
