### ISSUE TITLE
Possibility for including font-icons as local assets

### ISSUE THREAD

**Issue by geohuz** [mlaursen/react-md#186]
I'm not sure if I can include font-icons in my output bundle. Without fetching the icons online each time on page loading. For mobile/cordova project it is important to just treat them as local assets.
Another import reason is the google web fonts cdn is unreachable in area such as China.

**Comment by mlaursen** [comment]
I think the [host-material-icons](https://react-md.mlaursen.com/customization/typography?tab=1#mixin-host-material-icons) mixin is what you are looking for? Lemme know if I misunderstood
