### ISSUE TITLE
Keyboard usage of autocomplete causes form submission

### ISSUE THREAD

**Issue by timworx** [mlaursen/react-md#194]
Currently if an Autocomplete is used within a form, then when you use the `Enter` key to make your selection, it will also trigger the onClick event on the element with `type="submit"` within the form.

For the user, it makes sense to trigger form submission when the menu is closed, but not while the Autocomplete menu is open. Your typical `select` element is a good example of this.

What are your thoughts?

**Comment by mlaursen** [comment]
Ooh. That might be a problem with my `AccessibleFakeButton` which is used for the `ListItem` and `SelectField`. I might just need to prevent default behavior when I simulate the button enter or space interaction so it isn't submitted as well.

**Comment by timworx** [comment]
Probably worth mentioning if it's related: selecting the text in an Autocomplete and pressing Delete has no affect.

**Comment by mlaursen** [comment]
> Probably worth mentioning if it's related: selecting the text in an Autocomplete and pressing Delete has no affect.

Could you expand on that? From my tests, I have been able to remove text for the Autocomplete's text field by pressing delete or backspace.

**Comment by timworx** [comment]
Sorry, I mean selecting / highlighting all of the text in the field and then pressing delete does not delete all the text in it. While delete of a single character at a time does work.

**Comment by mlaursen** [comment]
It seems to be working for me? 
![autocomplete](https://cloud.githubusercontent.com/assets/3920850/21465361/44f467fa-c95d-11e6-880a-40ef29f09834.gif)

**Comment by timworx** [comment]
Well, that one is on me for not checking in the examples first. It isn't working in my implementation, I'll have to go back and see why that is now.

**Comment by mlaursen** [comment]
Ok, so I can update the Autocomplete so that it only submits a form when pressing enter on the text field. However, it looks like pressing enter on the SelectField will not be able to submit the form because it opens the menu on enter.

I am not sure if I should update the SelectField to only be opened on click/touch or the up/down keys. I kind of like the enter to open it.. but might be best to emulate the real html select.

**Comment by mlaursen** [comment]
Going to close this for now. When I decide what to do about the SelectField, I will reference this issue in the newly created issue.

**Comment by gotrecillo** [comment]
Sorry for posting in a closed issue.

There is some info about this ?

Can we help with anything ?

**Comment by carlgieringer** [comment]
I think this is still an issue.
