### ISSUE TITLE
[Feature] DataTable should be able to have a fixed header and footer (vertically scrollable body)

### ISSUE THREAD

**Issue by frol** [mlaursen/react-md#197]
Are there any plans to implement a fixed-header DataTables? There is a dedicated module developed by Facebook named FixedDataTable, which supports this: https://facebook.github.io/fixed-data-table/example-flexgrow.html, but I wonder what is easier: apply all the React-MD styles to the FixedDataTable components or implement the missing feature right into the React-MD.

**UPDATE:** I have found quite a brilliant solution for fixed-header tables in pure CSS: http://stackoverflow.com/a/33562974/1178806

**Comment by mlaursen** [comment]
I had looked into implementing a fixed header/footer for DataTables. Last time I checked, it makes the `EditDialogColumn`, `SelectFieldColumn`, and `TablePagination` components (well, anything that relies on `position: absolute`) unreliably positioned and messes up the row hover color.

I do think this is a feature that should be implemented at some point; or at least allow styles to easily be applied to existing solutions.

**Comment by frol** [comment]
I have succeeded in hacking this in pure HTML and CSS using React-MD CSS and React-MD HTML with minor changes and I believe it doesn't break anything!

[qq.html.zip](https://github.com/mlaursen/react-md/files/669923/qq.html.zip)

I took the generated HTML from React-MD documentation examples using Chrome inspector and did the following changes:

* added  3 div wrappers:
  1. horizontal scrolling wrapper
  2. container helper with padding-top placeholder for the header
  3. vertical scrolling wrapper
* added `<div>`'s to the `<th></th>` copying the titles (i.e. `<th>Title</th>` -> `<th>Title <div>Title</div></th>`)
* added some CSS

NOTE: I have also patched the `<td class="md-table-checkbox">` in `<thead>` as I believe it should be `<th>` (not `td`).

NOTE: Most of the CSS and HTML patches are originated from the stackoverflow answer I posted in my first message.

**Comment by mlaursen** [comment]
Thank you. I'll use this as a reference when I start working on this feature. Might be a bit though :)

**Comment by frol** [comment]
This is implemented in #318, so I am closing this.
