### ISSUE TITLE
Allow element types as Avatar children

### ISSUE THREAD

**Issue by lwansbrough** [mlaursen/react-md#198]
I have a custom icon (an SVG element) I'd like to put in an `Avatar`. I can do it, but I get an error/warning about prop types.

**Comment by mlaursen** [comment]
Is there a reason you can't do:
```
render() {
  const icon = <FontIcon iconClassName={null}><svg ..... /></FontIcon>;
  return <Avatar icon={icon} />;
}
```

or

```
render() {
  return <Avatar src={svgPath} alt="Alt describing icon" />;
}
```
?

I do think that it is still ok to update the PropTypes to allow more than just `string` for the `children` prop.

**Comment by lwansbrough** [comment]
@mlaursen Yup that might also be a solution!
