### ISSUE TITLE
CardTitle continues over the edge of Card

### ISSUE THREAD

**Issue by lwansbrough** [mlaursen/react-md#199]
When you have a very long subtitle (and possibly title?) for your CardTitle, no wrapping occurs, so the text continues off the edge of the Card.

**Comment by mlaursen** [comment]
Fortunately, the `title` will still correctly wrap. I had forgotten that the `subtitle` uses the `h3` tag which should not wrap lines according to the [typography specs](https://material.io/guidelines/style/typography.html#typography-line-height). Is it better to allow line wrapping for the `subtitle` or to have any text overflow as ellipsis?

**Comment by lwansbrough** [comment]
@mlaursen Well I'm biased because wrapping solves my problem. :) Generally it's probably safe to follow specs, though from a design perspective - in my opinion - if you don't have an Avatar to the left of your title, then wrapping the subtitle seems good.

**Comment by mlaursen** [comment]
I think I will go with this:

**No Avatar** - title and subtitle can line-wrap
**With Avatar** title and subtitle can not line-wrap and overflow is ellipsis-ed

I'm personally not a fan of the line-wrap prevention most of the time. Keep having to override it :/

**Comment by lwansbrough** [comment]
Great solution, didn't think you could control at that granularity. Thanks!
