### ISSUE TITLE
Redux Form dirty prop forces rerender and resets active state of a field

### ISSUE THREAD

**Issue by roderik** [mlaursen/react-md#202]
I have got an issue using react-md together with redux form. I have built a form; it looks great, and it functions as it should. Except when first interacting with the form.

The form renders and the fields display in their empty state
<img width="530" alt="screen shot 2016-12-28 at 12 14 37" src="https://cloud.githubusercontent.com/assets/16780/21520938/ac602638-ccf8-11e6-98b1-4c8b62e642ac.png">

I select the field; the label moves up, and the field is in the active state
<img width="530" alt="screen shot 2016-12-28 at 12 14 55" src="https://cloud.githubusercontent.com/assets/16780/21520943/b46d29ac-ccf8-11e6-8999-1e6638763379.png">

I start typing, and after the first letter, the field goes back in the inactive state, further typing is lost.
<img width="525" alt="screen shot 2016-12-28 at 12 15 03" src="https://cloud.githubusercontent.com/assets/16780/21520946/bdd33342-ccf8-11e6-8c35-360ca649470c.png">

Selecting the field again, allows me to type as I expect. Other fields also work normally as of now.
<img width="522" alt="screen shot 2016-12-28 at 12 15 15" src="https://cloud.githubusercontent.com/assets/16780/21520948/c6de954e-ccf8-11e6-956e-c06031c22e59.png">

I have an educated guess about the why, but I have got no idea on how to fix it. I was tracking the "render" events on the form, and the moment I type the first letter, the form rerenders because redux form sets the "dirty" prop to true. This render coincides with the revert to the inactive state of the field. There are no rerenders afterward.

Any idea on how I can fix this?

```
    "react": "^15.4.1",
    "react-addons-css-transition-group": "^15.4.1",
    "react-addons-transition-group": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-md": "^1.0.0",
    "react-redux": "^5.0.1",
    "react-router": "^3.0.0",
    "react-router-redux": "^4.0.7",
    "redux": "^3.6.0",
    "redux-form": "^6.4.1",
    "redux-thunk": "^2.0.0",
```

**Comment by mlaursen** [comment]
I haven't worked with redux-form yet, so I am not too sure what it does. Does the re-render cause a blur event to be triggered or completely remount the TextField? That is the only way looking through the TextField code that the `active` and `floating` state are set to `false` is with the blur.

When I finish some of the other tickets, I can try doing a react-form demo and debug with the TextField source to figure out what is happening.

**Comment by mlaursen** [comment]
I actually had some time today, but I am unable to reproduce at the moment. Here is the [gist](https://gist.github.com/mlaursen/641364cf6114692d470069c56c505880) I created to test it. It might be that it is just too simple. Would you happen to have any code examples I could use?

```
    "react": "^15.4.1",
    "react-addons-css-transition-group": "^15.4.1",
    "react-addons-transition-group": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-redux": "^5.0.1",
    "react-router": "^3.0.0",
    "react-router-redux": "^4.0.6",
    "redux": "^3.6.0",
    "redux-form": "^6.4.3",
    "redux-thunk": "^2.1.0",
```

![redux-form](https://cloud.githubusercontent.com/assets/3920850/21655865/ef13e66a-d278-11e6-877b-dce3e7b8c54f.gif)
