### ISSUE TITLE
Optional SwipeableViews component in the TabsContainer.js

### ISSUE THREAD

**Issue by tyholby** [mlaursen/react-md#203]
Can we have an option to make the SwipeableViews component in the TabsContainer.js not swipeable? Right now on mobile web, you can change tabs be clicking the tab or by swiping. If we have something that uses move events in the tab, the SwipeableViews interferes with that and changes tabs on you. 
If you don't want to add this improvement, can you think of a way that I can make them non-swipeable?

**Comment by mlaursen** [comment]
Yeah, I think I will add a `swipeableViewsProps` prop to the component so that you can add any other props from the [SwipeableViews API](https://github.com/oliviertassinari/react-swipeable-views#swipeableviews-).
