### ISSUE TITLE
Docs Search component does not work on iOS

### ISSUE THREAD

**Issue by tcrognon** [mlaursen/react-md#206]
To reproduce, go to https://react-md.mlaursen.com/ on iPhone 6 (maybe other versions, too?) and tap the search icon. It does not gain focus like it's supposed to.

**Comment by mlaursen** [comment]
I have no way of natively testing this.. But I am guessing it is because the iOS does not focus a text field if you click the label? I'll mark this as Help Wanted.

**Comment by daturon** [comment]
On my iPhone 6S default as tap a text box or a label is not taken into focus. Such things make software for example in Swift.

**Comment by mlaursen** [comment]
The documentation website has been updated with the new changes. It _should_ be working now for iOS since I no longer rely on the `focus` event to toggle the search. Please let me know if it still does not work.
