### ISSUE TITLE
Deprecate the `closeOnNavItemClick` prop for Drawer and use `autoclose` instead

### ISSUE THREAD

**Issue by Amin52J** [mlaursen/react-md#207]
Hello and thank you so much for this brilliant library, I was going through the prop types of the Drawer component when I saw that there are two properties (which from my point of view) do the exact same thing.

autoclose: Boolean if a temporary drawer should close when a nav item is clicked.
closeOnNavItemClick: Boolean if the navigation drawer should automatically close when a nav item has been clicked.

If they are the same, we should be using only one of them and if they're not, then we should clarify the definitions as it is a bit confusing.

**Comment by mlaursen** [comment]
This was a bug on my end. I forgot about the `autoclose` prop. They do the same thing. I'll deprecate `closeOnNavItemClick`.
