### ISSUE TITLE
Question: styling text-field inside of toolbar

### ISSUE THREAD

**Issue by jasonallen** [mlaursen/react-md#211]
I'm trying to add a search box inside of a toolbar, similar to how google keep does:

![google keep toolbar](http://i.imgur.com/0cdIzlQ.png)

Using the Toolbar's `children` works well. However the search md-text-field's text is invisible, or rather, white-on-white. This is because it inherits the md-toolbar--text-white css class. This would normally be desired, but in this case the text-field is inside a custom white div, so I don't want it to be that way. What's the best way to reset the text-area so that it doesn't think it's inside the toolbar?

**Comment by mlaursen** [comment]
Hmmm. Ok. So it looks like this happens [here](https://github.com/mlaursen/react-md/blob/master/src/scss/components/_toolbars.scss#L182-L189).

This can be undone multiple ways:
- setting both `$md-toolbar-include-text-fields` and `$md-toolbar-include-autocompletes` to false before `@include react-md-everything`. However, you might need to add [these styles](https://github.com/mlaursen/react-md/blob/master/src/scss/components/_toolbars.scss#L197-L206) back.
- setting `singleColor` to `false` on your toolbar (This would require you to specifically set the color of the `.md-btn--icon` and `md-title--toolbar` to `$md-white-base`)
- creating a new style
    ```
    .md-toolbar--text-white .md-text-field.md-text-field {
      color: get-color('text', true);
    }
    ```

**Comment by jasonallen** [comment]
Thanks - I was able to make it work with the singleColor suggestion.
