### ISSUE TITLE
Allow ListItem to be used outside of List?

### ISSUE THREAD

**Issue by renshenhe** [mlaursen/react-md#213]
The `ListItem` component is quite versatile in composition of other components i.e. card titles and comment headers.  I know there's a `CardTitle` component but I feel the `ListItem` has more potential outside of lists due to it's flexibility and design.

Possibly render `ListItem` and `Lists` as divs  or apply `list-style: none;` to `.md-list-item`, though the latter makes it seem off `<li>` item rendered outside of `<ul>` or `<ol>`.

I also support adding `ListItem` to #176

**Comment by mlaursen** [comment]
Sounds like a good idea to me. I wish I had named the current `component` prop as `tileComponent` since that is really what it is... I think I will go with a `listComponent` prop that defaults to `'li'` so it can be rendered as any html element or React component.
