### ISSUE TITLE
SelectField fails for zero-valued option

### ISSUE THREAD

**Issue by irvinlim** [mlaursen/react-md#214]
Hi, first of all thanks for this wonderful library! 😄 

One small issue though, I've noticed that the SelectField fails when I do the following:

```jsx
const items = [
  { value: 0, label: 'A' },
  { value: 1, label: 'B' },
  { value: 2, label: 'C' },
];

<SelectField id="select-field" menuItems={ items } />
```

Selecting any option works fine, except when I select "A" (the first option), which results in no option being shown in the select field, and `onChange` yields `NaN`.

After much digging, I've narrowed down the cause to this particular line in [`src/js/SelectFields/SelectField.js`](https://github.com/mlaursen/react-md/blob/master/src/js/SelectFields/SelectField.js#L647):

```jsx
itemValue = item[itemValueKey] || item[itemLabel];
```

When `item[itemValueKey]` is `0`, `itemValue` would then be set to `item[itemLabel]`, which, when passed to `_handleItemSelect`, evaluates `Number(item[itemLabel])` which then evaluates to `Number("A")`, or `NaN`.

-----

A simple fix would be to just change the line to:

```jsx
itemValue = item[itemValueKey] !== undefined && item[itemValueKey] !== null ? item[itemValueKey] : item[itemLabel];
```

I would be more than happy to create a PR if you wish.

Thank you!

**Comment by mlaursen** [comment]
Hmm. Should `null` be a valid value? I think it would just like `typeof item[itemValueKey] !== 'undefined' ? item[itemValueKey] : item[itemLabelKey]`. I think `null`, `0`, or the empty string `''` should be valid values to _reset_ a select field (unselected state). You are more than welcome to submit a PR to my `release/1.0.x` branch, or I will do one later today. Thanks :)

**Comment by irvinlim** [comment]
I think that `0` should be a valid form value, instead of using it to reset the field's value, as compared to `null` and `''`. Besides, `null` and `''` shouldn't be valid options when passing to `menuItems` either.

Just created the PR as well. Could I also kindly check when would the `1.0.x` branch be released on npm, together with quite a number of bugfixes?

Thank you! 😄

**Comment by mlaursen** [comment]
You're right that `null` shouldn't really be a valid value. But is `''` really invalid? `<option value=""></option>` technically works, not sure if you _should_ do that though. And yeah, `0` shouldn't reset the field, it is a valid value.

I was actually planning on releasing 1.0.1 today, I'm writing up a change log at the moment and figuring out if I missed any small bugs that could be added to this patch.
