### ISSUE TITLE
Implement Notification Component

### ISSUE THREAD

**Issue by shashwattt-Pretlist** [mlaursen/react-md#220]
Do we have a component to display notification with count.. 

something like 
![image](https://cloud.githubusercontent.com/assets/20681416/22018258/f938e356-dcd3-11e6-85fc-ce292ea6707f.png)

**Comment by mlaursen** [comment]
There isn't one at the moment. My main concern is making it look good with large digit numbers and figuring out what the largest digit number should be supported. I think 2 digits might be reasonable. If it is more than that, I might truncate to display `99+`.

Just curious, does the bubble surrounding the number always have to be a circle, or does it stretch into an oval?

**Comment by shashwattt-Pretlist** [comment]
The screen-shot attached is from a library called material-ui, the customization there is in form of style object, I guess we can change the shape accordingly.
And yes, 2 digits is reasonable.
I am still halfway getting acquainted react-md properties and customization, will try to create a PR with notification component as soon as I get my hands-on or are you already working ?? @mlaursen

**Comment by mlaursen** [comment]
I haven't started working on it yet, I've only done some in-browser hacking for this with an Icon Button. I'm currently working on finishing up the fixed table headers/footers, so feel free to make a PR for this :)
