### ISSUE TITLE
DataTable wrong selection when using  pagination

### ISSUE THREAD

**Issue by demj1206170** [mlaursen/react-md#224]
when select some rows(such as in index 0,1,2's row), when using  pagination,and from page 1 to page 2,those selection will be keeped,but page2 has not doing any select

**Comment by mlaursen** [comment]
Can you link to a code snippet or gist to show where it is failing?

**Comment by demj1206170** [comment]
https://react-md.mlaursen.com/components/data-tables  -> Table Pagination Example
in this example ,
