### ISSUE TITLE
[DataTable] - Implement a Compact DataTable

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#237]
There should be a way to make a more compact data table since the default one takes up a decent amount of space.

This should probably be able to be flagged in the `DataTable` itself as `compact`. The main concerns with this will be how to handle the select fields and edit dialog columns with the new spacing.

**Comment by stickfigure** [comment]
FWIW, I'd be perfectly happy with a compact data table that didn't support select fields and edit dialog columns. I just need information density for tabular data.
