### ISSUE TITLE
Datepicker defaultValue not being selected in the calendar when minDate is set

### ISSUE THREAD

**Issue by adhesivewombat** [mlaursen/react-md#245]
### Description
When creating a DatePicker component with `minDate` and `defaultValue` props set, the `defaultValue` is shown in the date text field, but not in the picker itself.  The datepicker just shows the current day as the selected day.  

I have tried this by setting the `defaultValue` prop equal to both a date object and a string.  I have tried this using the `value` prop with no success.  I have also tried to use the `initialCalendarDate` prop alongside `value` and/or `defaultValue` without success.

The interesting part is that the `defaultValue` or `value` prop will be selected in the calendar if a `minDate` is not set.

### Images/Screenshots
In this case, the `defaultValue` is equal to "2/12/2017" from the store.
![image](https://cloud.githubusercontent.com/assets/8271385/22754888/04ec3d0a-ee0f-11e6-88ce-1360f7371ca8.png)

### Code Sample
```
<DatePicker
    id="campaign-start-date"
    label="Start Date"
    onChange={(dateString) => onStartDateChange(dateString)}
    minDate={new Date()}
    maxDate={new Date(new Date(endDate).getTime() - millisecondsPerDay)}
    initialCalendarDate={startDate}
    defaultValue={startDate}
    inline={true}
/>
```
`startDate` is equal to "2/12/2017" from the store
`endDate` is equal to "2/20/2017" from the store
`onStartDateChange` just changes the value of startDate in the store
`milisecondsPerDay` is a const that equals 86400000 (this is so the max date can never be >= the endDate)

### Version
- React 15.4.2
- React-MD 1.0.1

**Comment by adhesivewombat** [comment]
After looking at the source code a bit, it looks like it might have something to do with the `componentWIllReceiveProps()` function in the DatePickerContainer.

**Comment by adhesivewombat** [comment]
Aha! I think you've already fixed this.  I updated to react-md 1.0.5 and it works as intended.  Nice!

**Comment by mlaursen** [comment]
Oh awesome! I think it was related to 53130fa

**Comment by adhesivewombat** [comment]
So I think I might have found another edge case.  It looks like this has been fixed on the initial load of the component, but after updating the `value` or `defaultValue` prop, the states' `calendarDate` (and I think `calendarTempDate` too) doesn't update.  

I'm still learning but it seems that it might have something to do with the `componentWillReceiveProps` function in the container.  I think it's because the state is set based on `this.state.calendarDate` which I'm not sure has updated yet?

**Comment by mlaursen** [comment]
Thanks, I was able to figure it out! Just to make sure I am testing the right use case... This is what we are expecting:

- The `value` of the `DatePicker` changes from an external source (Redux, Mobx, ... state management)
- The calendar's selected date should reflect those changes

I don't think it should be hooked up to the `defaultValue` prop (personally) since that should just be the default for initial setup. It should be a controlled component if it will keep changing.

**Comment by adhesivewombat** [comment]
Yep! That's the case. Good to know, I will make sure to use the `value` prop when I need control.
