### ISSUE TITLE
[Slider] - Implement a Range Slider

### ISSUE THREAD

**Issue by thaithcock** [mlaursen/react-md#246]
Hi mlaursen,

You have a slider but it only has 1 handle. Would it be possible to have a range slider as well?

**Comment by mlaursen** [comment]
Just to make sure, you would like something like this:
<img width="720" alt="screen shot 2017-02-10 at 1 43 17 pm" src="https://cloud.githubusercontent.com/assets/3920850/22843466/0258688c-ef97-11e6-9398-f22985f9cd90.png">?

**Comment by thaithco** [comment]
Yes, that is right, something like that.
