### ISSUE TITLE
[Documentation] What are components that are missing documentation or examples?

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#249]
Use this issue to post any components or Sass items that are missing documentation or examples.

The only item I have on my radar is to add more examples using react-router with the `NavigationDrawer`/`Drawer` components.

I do also use the `component` prop to be able to render my components as different components. I stole this from the `react-addons-transition-group` and `react-addons-css-transition-group`. Should I add more information about its usage?

**Comment by absolutebica** [comment]
I am trying to use your example on the Nagivation drawer and my 'npm start' ends up failling on these

import LoremIpsum from 'components/LoremIpsum';
import inboxListItems from 'constants/inboxListItems'; 

It tells me the module is not found.

**Comment by mlaursen** [comment]
Ahh ok. So anything that isn't listed in the `react-md/lib` namespace is stuff that is stuff that I created only for the documentation site. If you would like to see the code for files that are not fully listed in the examples, you can search [here](https://github.com/mlaursen/react-md/tree/master/docs/src/shared). I tried to keep the examples more related to used components and hiding some of the boilerplate/custom stuff.

**Comment by absolutebica** [comment]
Ok. So I had installed react-md with NPM. Do I need to either git clone or download the package off github in order to access the docs?

**Comment by absolutebica** [comment]
Where should that "shared" folder be placed? I copied the shared folder into the react-md directory inside node_modules..because placing it at the root of the project, and changing the path reference in the IMPORT statement didn't work. 

Now I get an error that says

Error in ./~/react-md/src/shared/components/LoremIpsum.jsx
Module parse failed: C:\Users\myname\home\www\sandbox\react-app\node_modules\react-md\src\shared\components\LoremIpsum.jsx Unexpected token (16:19)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (16:19)
 @ ./src/MyAwesomeComponent.js 39:18-70

**Comment by carlgieringer** [comment]
Hi @absolutebica, if you want to use these files for testing around, maybe just copy-paste their content into your project.  E.g., create a file named 'LoremIpsum.jsx' next to the file you want to use it in, and then use `import LoremIpsum from './LoremIpsum'`.  The leading `./` in the import statement should tell your transpiler to look in the same directory as the current file.

**Comment by eghernqvist** [comment]
Might not be of huge importance, but the `tooltipLabel` prop in the MenuButton example is missing in the Prop Types tab.

```
        <MenuButton
          id="vert-menu"
          icon
          buttonChildren="more_vert"
          className="menu-example"
          tooltipLabel="Open some menu"  // <-----
        >
          <ListItem primaryText="Item One" />
          <ListItem primaryText="Item Two" />
          <ListItem primaryText="Item Three" />
          <ListItem primaryText="Item Four" />
        </MenuButton>
```
