### ISSUE TITLE
TableColumn should expose grow and/or adjusted props

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#252]
When there are big DataTables, there are some performance concerns when auto-adjusting every column just to inject `md-table-column--grow` and `md-table-column--adjusted` once it has been rendered.

It should ideally be that every column automatically has `md-table-column--adjusted` if `grow` is not specified on the column.

**Comment by MichalWadowski** [comment]
Maybe for performance concerns helps library https://github.com/bvaughn/react-virtualized/ ?

**Comment by mlaursen** [comment]
I had been looking into react-virtualized, but the main problems I have with it is that their table is not actually a `<table>`, it is a grid of `<div>` and because of this, there is basically 0 accessibility at this time. It also relies on very specific height and width which I am not a giant fan of, but it completely makes sense. I could try looking into their docs a bit more to see if I could manipulate it to be a real table, but it is more on the back-burner for now.
