### ISSUE TITLE
[Icons] - Implement SvgIcon Component

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#253]
See #233 for details.

**Comment by MrXyfir** [comment]
I think it'd be nice to have support for both passing the SVG data in directly and also for using an existing SVG [symbol](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol).

Maybe if a `use` or similar prop is there it'll use that value for a `<use>` element's `xlink:href` attribute.

```jsx
render() {
  return (
    <svg ...>
      <use xlink:href={this.props.use} ... />
    </svg>
  )
}
```

For passing the data directly you can look into how Material-UI does it:

* http://www.material-ui.com/#/components/svg-icon
* https://github.com/callemall/material-ui/blob/master/src/SvgIcon/SvgIcon.js

**Comment by mlaursen** [comment]
Yeah, I would personally prefer the usage of an svg sprite map over inline solution. I'll make sure both ways are implemented.
