### ISSUE TITLE
Difference between docs and implementation of Remaining Props in TextField

### ISSUE THREAD

**Issue by carlosforero** [mlaursen/react-md#26]
The documentation of TextField says:
* Any remaining props: Any other props (such as style, aria-tags, etc) will be applied to the container component.

However the TextField implementation applies to the Input instead of field container:

lib/TextFields/TextFields.js:194
```javascript
      var textFieldProps = _extends({}, props, {
        value: value,
        className: (0, _classnames2.default)('md-text-field', className, {
          active: active,
          'floating-label': useFloatingLabel,
          'single-line': !useFloatingLabel && !multiline,
          'multi-line': multiline,
          'full-width': fullWidth
        }),
        onFocus: this.handleFocus,
        onBlur: this.handleBlur,
        onChange: this.handleChange
      });
```

I assume the right is in the container as the documentation says.

Other issue, the documentation says that `style` is a remaining property, but in the code `style` is filtered from the remaining properties:

lib/TextFields/TextFields.js:153
```javascript
var props = _objectWithoutProperties(_props, ['className', 'containerClassName', 'label', 'placeholder', 'maxLength', 'helpText', 'errorText', 'floatingLabel', 'icon', 'rightIcon', 'lineDirection', 'rows', 'maxRows', 'style', 'required', 'helpOnFocus', 'fullWidth']);
```

Should `style` be applied to the input or should be a remaining property and applied to the container?

**Comment by mlaursen** [comment]
I believe the documentation should specify that the props are added onto the input component instead of the field container so that any event handlers can be passed down correctly. That should be a documentation update.

After looking through the code, I believe that the style should actually be applied to the container instead of the inout/textarea tag since it would be much more likely to want inline styling on the container.

**Comment by carlosforero** [comment]
Currently there are className which applies to the Input and containerClassName which applies to the container.

I think should be similar with style. Making explicit the style property for the Input and adding a containerStyle property. What do you think?

**Comment by mlaursen** [comment]
That sounds good to me. Will be a few lines shorter to implement :)

**Comment by carlosforero** [comment]
Good, I can prepare a PR tomorrow night.
