### ISSUE TITLE
where did randomAvatars go?

### ISSUE THREAD

**Issue by wdiechmann** [mlaursen/react-md#265]
### Description

Trying to imitate your https://react-md.mlaursen.com/components/lists has me fighting the missing utils/RandomUtils/randomAvatars - 

Did you possibly leave it out on a commit/push?

### Images/Screenshots

    Error in ./src/App.js
    Module not found: 'utils/RandomUtils/randomAvatars' in /Users/walther/Projects/React/ithelps_client/src

### Link to a gist or code sample where the issue can be reproduced

    # ./src/App.js
    import randomAvatars from 'utils/RandomUtils/randomAvatars';

### Version
    "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-transition-group": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-md": "^1.0.6",

**Comment by mlaursen** [comment]
Ahh sorry. Anything that is not documented on the website is actually not something that _should_ be used. Components/utils not in the `react-md` namespace are only included for the documentation website as well. But you can see the code here:
- [randomAvatars.js](https://github.com/mlaursen/react-md/blob/master/docs/src/shared/utils/RandomUtils/randomAvatars.js)
- [RandomAvatar.jsx](https://github.com/mlaursen/react-md/blob/master/docs/src/shared/components/RandomAvatar.jsx)

**Comment by wdiechmann** [comment]
my bad 'cause you know:
copy/paste is every programmer's sword, and his curse ;)

but hey - thx for the js/template

if you reckon there is anything I can assist with - do not hesitate to come forward! This monumental task you've taken upon you is quite an endeavour!

**Comment by mlaursen** [comment]
No worries, it is the bane of us all :)

If there are any existing issues that you feel like you could fix, feel free to pick them up. Otherwise, let me know if documentation or anything is lacking!
