### ISSUE TITLE
Autocomplete onBlur event doesn't trigger when popup menu doesn't show up

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#266]
At first, many thanks to @mlaursen for this project. Its unbelievable how big and good quality and well documented project he maintain.

So, I have problem with blur event in Autocomplete component. Documentation says, that onBlur event will be triggered if entire component will be blured (when window is clicked or user tabs away from component). This is true only if we write text to filter which pass to component data and menu was show up. If user search term doesn't show autocomplete popup menu, then olny tabs away from component will trigger onBlur event. If we click away from autocomplete, onBlur doesn't trigger.

Next problem with blur is that if we select popup menu item, then onBlur is triggered (after onMenuClose) even if Autocomplete control still has focus.

**Comment by mlaursen** [comment]
Thanks for the rundown! I have a general idea about what is going on now.
