### ISSUE TITLE
[DataTable] - Disable checkboxes in data-table

### ISSUE THREAD

**Issue by thaithcock** [mlaursen/react-md#289]
Currently, the supplied "in-line" checkboxes in data-tables cannot be disabled.

It would be good if we could pass some sort of prop to disable these checkboxes, to prevent user interaction with them.

**Comment by mlaursen** [comment]
I think I will provide two props:

- `disabledRows` which will be a list of indexes for rows that should be disabled
- `disableAllRows` which will be a boolean if all the rows should have the checkbox disabled

**Comment by mlaursen** [comment]
It might be helpful to also expose `disableSelection` || `disableRow` || `disableCheckbox`? (names hard) on the `TableRow` itself as well.
