### ISSUE TITLE
Overlay for opening the drawer of NavigationDrawer?

### ISSUE THREAD

**Issue by cia48621793** [mlaursen/react-md#292]
I couldn't set this option besides extending NavigationDrawer and export the overlay props for it, is there other way round?

**Comment by mlaursen** [comment]
It looks like I did not correctly pass that on to the `Drawer` from the `NavigationDrawer`. I will add that

**Comment by mlaursen** [comment]
Hmm, actually it looks like I didn't document it on the `NavigationDrawer`.

You should be able to do this:

```
const { TEMPORARY } = NavigationDrawer.DrawerTypes;

<NavigationDrawer
    overlay
    clickableDesktopOverlay
    tabletDrawerType={TEMPORARY}
    desktopDrawerType={TEMPORARY}
    type={TEMPORARY}
/>
```

**Comment by cia48621793** [comment]
Thank you, it's working now.
