### ISSUE TITLE
[Button] - Add an option to make buttons have the same size when disabled or enabled

### ISSUE THREAD

**Issue by rodgobbi** [mlaursen/react-md#295]
Currently, a disabled floating button is smaller when it's active, because of that, when I disable or enable a button depending user input, it affects the layout and proportion of the others components in the same container. I solved this by giving every floating button a fixed size based on `$md-btn-floating-size`.
It would be good (for all types of button) if by default the button doesn't change the size when disabling it, or at least give an option for that.

**Comment by mlaursen** [comment]
I think this is a good idea. One of the changes of the next release is to allow constant sizes between all media devices instead of changing size (some components change size based on media), so this would be a good addition as well.

**Comment by rodgobbi** [comment]
This is really good, I always have doubt if a component will change size based on the media, with this option to make its size responsive I can know for sure, and style it personally if I want. And it is good to have in the documentation all the breakpoints of these responsive components, thus I can style personally the ones I want and they  will behave equally as the default responsive ones.
Thanks for the support, I'm really enjoying to use react-md.

**Comment by mlaursen** [comment]
Yeah, I understand _slightly_ why the material design guidelines change sizes based on device size, but now that I have been using it more... it is actually pretty annoying.

Right now, the components that change based on media are `Button` (_kind of_, they have invisible size changes for easier touch accessibility), `ListItem`, `TextField`, and `Toolbar`.

I'm glad that you have been enjoying it! :)
