### ISSUE TITLE
Drawer.overlay={false} only works for desktop, not tablet or mobile

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#298]
### Description

I have a `Drawer` set up like this (some props deleted for brevity):

```jsx
<Drawer
	type={Drawer.DrawerTypes.TEMPORARY}
	position="right"
	style={{ zIndex: 100, width: 'auto' }}
	overlay={false}
>
	{/* some stuff */}
</Drawer>
```

Basically I just want a temporary drawer on the right that works more or less like the temporary drawer on the left (with auto, no overlay). This works great in desktop mode. However, in mobile and tablet modes the overlay still shows up.

I can workaround this by setting `desktopMinWidth={1}`.

### Version
- React 15.4.2
- React-MD 1.0.8

**Comment by mlaursen** [comment]
The fixes for #299 also fixed the bug for this issue.
