### ISSUE TITLE
Drawer.overlay={false} doesn't work on page refresh

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#299]
### Description

When using `Drawer overlay={false}` with a right-side temporary drawer, the overlay still shows up (in all media types) on page reload. Resizing the window fixes the issue.

The workaround is to set `defaultMedia="desktop"`.

### Versions
- React 15.4.2
- React-MD 1.0.8

**Comment by mlaursen** [comment]
This might be related to #291 . I'll check it out

**Comment by mlaursen** [comment]
It was only sort of related. I needed to update the `Drawer` to do an initial fix for `temporary` types on desktop screens to make sure the overlay is invisible.
