### ISSUE TITLE
SelectColumnField not populated in certain case

### ISSUE THREAD

**Issue by jlabarbera11** [mlaursen/react-md#300]
If the menuItems is set within the render method, selecting an item will not show up in the select field. This seems to occur only if the component that renders the SelectFieldColumn is rerendered.

gist: https://gist.github.com/jlabarbera11/427bd6eaffbba7a5269a5b5e0f880750
codepen: https://codepen.io/anon/pen/WpdbeK?editors=0110

### Version
- React 15.4.2
- React-MD 1.0.6

**Comment by mlaursen** [comment]
This actually was a problem with the `SelectField` component itself. When the `menuItems` are declared in the render, the `===` check in `componentWillReceiveProps` fails and it attempts to find the label again. However, I forgot to do the check for `controlled` vs `uncontrolled` `SelectField`s so it chose the wrong current `value`.

**Comment by jlabarbera11** [comment]
Thanks for getting to this so quick. The codepen still seems broken though, the result that's shown doesn't match what was clicked. Also, it's still empty in the first render.

**Comment by mlaursen** [comment]
Hmm. You are correct. I actually tested this use case locally as well before closing it. I'll reopen to see what's wrong.

**Comment by mlaursen** [comment]
Looks like I only got half of the fix correct. I should have done the change in `componentWillUpdate` instead of `componentWillReceiveProps` since `componentWillReceiveProps` comes before the initial `activeLabel` state update.

**Comment by mlaursen** [comment]
It looks like I got it working correctly this time (in the pen as well). The only change required in the pen is to change the `defaultValue` from `type` to one of the `menuItems` and it displays correctly.
