### ISSUE TITLE
[NavigationDrawer] - Mini navigation icons do not center when using elements for navigation

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#304]
### Description

If using NavigationDrawer by passing real elements as `navItems`, the mini drawer does not center icons properly. That's because in mini mode the elements do not receive the `md-list-tile--mini` class. If you pass objects as `navItems` then it works correctly.

The only workaround I've been able to come up with is to specify padding for the icons myself using media queries (12px for mobile, 24px for tablet). 

It would be great if there was some way to avoid this. Seems like using router `<Link>`s as navItems would be a common use case.

### Version
- React 15.4.2
- React-MD 1.0.10

**Comment by pig800509** [comment]
same issue +1

**Comment by zachsa** [comment]
I found the same issue - it looks like the `md-list-tile--mini` class is not being added as expected. my setup is this:

```
import React from 'react'
import { Link, Route } from 'react-router-dom'
import { FontIcon, ListItem } from 'react-md'

<Route
  path={to}
  exact={exact}
  children={({ match }) => {
    return (
      <ListItem
        component={Link}
        active={!!match}
        to={to}
        primaryText={label}
        leftIcon={<FontIcon>{icon}</FontIcon>}
      />
    )
  }}
/>
```

**The fix for me is this:**

```
...

<Route
  path={to}
  exact={exact}
  children={({ match }) => {
    return (
      <ListItem
        tileClassName={'md-list-tile--mini'}
        component={Link}
        active={!!match}
        to={to}
        primaryText={label}
        leftIcon={<FontIcon>{icon}</FontIcon>}
      />
    )
  }}
/>
```
