### ISSUE TITLE
DatePicker show date in different format in different clients

### ISSUE THREAD

**Issue by Rajat421** [mlaursen/react-md#305]
one client is running on ubuntu google chrome and second client is runnig on mac google chrome ,both having same google chrome version 57.0.2987.98

**Comment by mlaursen** [comment]
Since the format is based on the browser locale, can you show what `window.navigator.userLanguage || window.navigator.language` is for both browsers?

**Comment by Rajat421** [comment]
@mlaursen thank you , there is problem with locales , now i have specified it explicitly ,working fine
