### ISSUE TITLE
[ExpansionPanel] - Give options to control the footer of the ExpansionPanel

### ISSUE THREAD

**Issue by rodgobbi** [mlaursen/react-md#306]
Currently I am using Expansion Panels just to present data, and the collapsible behavior is the important feature for me. To leverage this component in my app I'm currently hiding the default footer with buttons via CSS, it would be really good to have options over this footer and its buttons, making all optional.

**Comment by MichalWadowski** [comment]
Currently it's impossible to add some icons to action buttons. It would be nice if we could use own buttons - own components, not only parameters like primary/secondary or labels. Also it will be more flexible if we could define different number of action buttons.

**Comment by mlaursen** [comment]
Ok, I'll try to incorporate that as well!
