### ISSUE TITLE
Dialog / Snackbar Transition Bug

### ISSUE THREAD

**Issue by mkimberlin** [mlaursen/react-md#311]
### Description
If you set state that adds toast immediately after setting state that closes a open dialog, the Snackbar is abruptly removed from the DOM and never reinstated.  Adding a timeout to delay the adding of the toast to state will work around this issue.

### Link to a gist or code sample where the issue can be reproduced
[See this bug in action here](http://codepen.io/mkimberlin/pen/ryKZGd?editors=0010)

### Versions
- React => 15.4.2
- React-MD => 1.0.10

**Comment by mlaursen** [comment]
Thanks. It looked like it was a bug about always creating a "swap" timer incorrectly

**Comment by mkimberlin** [comment]
Thanks for the quick fix!
