### ISSUE TITLE
[TextField] - TextField componentDidUpdate() is called before html text input tag is really updated

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#312]
I have to control cursor (selection) in TextField while user type text. So, I extend class TextField and then I use getField() method in componentDidUpdate() to access raw HTML element for cursor controlling. But while TextField.componentDidUpdate() method is called, value of getField() is old yet. It seems TextField is updated first, and InputField used internally by TextField is updated as second. I cannot control HTML text field cursor after updates.

It happens only if I process user passed text, so TextField value is diffirent than HTML text field before processing. I handle onChange event, process passed text and update TextField value. In componentDidUpdate method I have updated value property, but getField().value has old value. If I set cursor position, it will be overwritten after real HTML tag update.

If I use direct InputField component instead of TextField, then componentDidUpdate() is fired after HTML input is really updated and I can control cursor.

It would be nice if TextField allow to use custom component as field. Then it will be possible to pass extended InputField as field component, and proper hande component updates.

**Comment by mlaursen** [comment]
This sounds interesting. So this would basically allow you to define your own `input` or `textarea` for the `TextField` to get the desired behavior?

**Comment by MichalWadowski** [comment]
If I provide own version of InputField / HTML input wrapper then yes, I can handle desired behavior, because componentDidUpdate() is called immediate after HTML tag update (after input render() call). Method componentDidUpdate() of TextField is called after own render(), but before InputField() render() and I can't fully controll behavior of input from TextField methods.

I think that defining own sub-components for use by main components will provide more flexibility. In general, not only TextField. For example, another react library https://react-bootstrap.github.io/components.html allow to override almost every default sub-component (by componentClass prop). If I need extra some feature not provided by default sub-component, then I can create own component provides this feature and replace defaults.
