### ISSUE TITLE
[TextField] - Change type of TextField to another invalidate component

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#314]
If TextField has type="text" prop, and if I change dynamically type for example to "number", then TextField is not editable. It is displayed as "text" type, but its not possible to write any content.

**Comment by mlaursen** [comment]
Could you provide a snippet/gist/codepen for this? I tried it out [here](http://codepen.io/mlaursen03/pen/OprPbZ) and it seems to work correctly.

**Comment by MichalWadowski** [comment]
There is link with code example that shows the problem: http://codepen.io/MichalWadowski/pen/LWqMLp

**Comment by MichalWadowski** [comment]
I noticed, that problem exists on Firefox, desktop and mobile version. On Chrome both mobile and desktop works correctly.

**Comment by mlaursen** [comment]
This actually appears to be a problem with the html `input` as well. Once the type is changed to `number` on focus, it immediately triggers the blur event which causes it to go back to `text` and prevents the input from being intractable. Quite odd.
