### ISSUE TITLE
Datepicker next month arrow on 31st day

### ISSUE THREAD

**Issue by adhesivewombat** [mlaursen/react-md#315]
### Description
The datepicker will skip a month if the 31st day of the month is selected and you hit the next month arrow.

Steps to repro:

1. Create a react-md datepicker with the `defaultValue` set to the 31st day of a month
2. Open the datepicker component (with default settings so that today will be selected)
3. Hit the next month arrow

### Link to a code sample
https://codepen.io/adhesivewombat/pen/vxvNXO
### Version
- The versions loaded in the codepen

**Comment by mlaursen** [comment]
I have a general idea about what is causing this, but I am going to think a little bit about if this should go into `v1.0.12` or wait until `1.1.0` (just so I can actually finish that release...)

**Comment by sniphpet** [comment]
You will also notice using the sample above that you need to click twice on previous.
