### ISSUE TITLE
Slider's bullet displays incorrectly if in a container that has text-align: center

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#323]
Example codepen: http://codepen.io/reedsa/pen/XMLgzK

**Comment by sniphpet** [comment]
@mlaursen the text-align property only affect the position of the bullet in my case.

**Comment by mlaursen** [comment]
Yeah, sorry. This issue started from a Slack message so I didn't put too much info in it. It basically messes up the "bullet" only when zeroed.

**Comment by sniphpet** [comment]
Thanks for the input
