### ISSUE TITLE
[DatePicker] - Date Picker should set week start day according to locales prop

### ISSUE THREAD

**Issue by kernigham** [mlaursen/react-md#326]
### Description
It would be good if Date Picker could set the starting day of week according to locales prop or on a own prop.

Thank you.

**Comment by gamtiq** [comment]
Unfortunately current version of ECMAScript Internationalization API Specification (Ecma-402) does not have means to determine first day of week for a specified locale: see tc39/ecma402#6.

**Comment by mlaursen** [comment]
I think the #462 pull request completes this issue. So I'll be closing it for now.

**Comment by gamtiq** [comment]
I've created [weekstart](https://github.com/gamtiq/weekstart) library that contains function to get first day of week depending on locale. It can be used with `firstDayOfWeek` property until corresponding Ecma-402 API is not ready.
