### ISSUE TITLE
Props that are only valid as a `string` should also support `node`

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#327]
When localizing apps with react-intl, you will get a lot of prop warnings unless you do the annying `intl.formatMessage(intl.messages.myMessage, ...)` since it doesn't allow components.

Things that trigger warnings at the top of my head are:

Button's `label`
TextField's `errorText`/`helpText`

**Comment by carlgieringer** [comment]
Is this related?  I am trying to conditionally hide a button until a user hovers over a card:

`<Button icon className={{hidden: !isOver}} >reply</Button>`

But this gives me this warning (react-md@1.0.11):

```
warning.js?8a56:36 Warning: Failed prop type: Invalid prop `className` of type `object` supplied to `Button`, expected `string`.
    in Button (created by ButtonTooltiped)
```

**Comment by mlaursen** [comment]
I think that should probably be using the `classnames` module? and switched to

```
<Button icon className={classnames({ hidden: !isOver }}>reply</Button>
```

**Comment by carlgieringer** [comment]
Oh, right you are.  Thank you very much, Mikkel.
