### ISSUE TITLE
[DataTable] - Icon button inside plain DataTable resize rows height

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#329]
If we add some icon buttons inside plain DataTable, then rows heights are resized. This problem exists only for plain tables, dynamic content table looks fine. Plain table cells have extra padding and its ok for text content. But if in cell is placed icon button, then its has own padding too, and rows with buttons have extra height.

I think that plain table rows should have minimum height without cells padding, or cell padding should be applied only for text only cells.

**Comment by mlaursen** [comment]
I think this was fixed with the release of 1.1.0

**Comment by MichalWadowski** [comment]
Yes, it looks fine now. Thanks!
