### ISSUE TITLE
Option to remove 'cancel' and 'save' buttons in expansion-panel

### ISSUE THREAD

**Issue by tom1193** [mlaursen/react-md#336]
Seems like the footer is fixed with two buttons, but I was looking for more customizability for the expansion-panel component. Perhaps have to option of removing the footer with the buttons? Thank you!

**Comment by MichalWadowski** [comment]
Its looks like issue https://github.com/mlaursen/react-md/issues/306

**Comment by mlaursen** [comment]
Closing in favor of 306
