### ISSUE TITLE
[Layover] - Fast clicks to MenuButton bring to wrong Menu positioning

### ISSUE THREAD

**Issue by mctep** [mlaursen/react-md#345]
![react-md menu-button](https://cloud.githubusercontent.com/assets/1949681/25346314/f30d77ec-291f-11e7-872f-99312b6e3a93.gif)

http://react-md.next.mlaursen.com/components/menus
Google Chrome

**Comment by mlaursen** [comment]
This should be fixed now with the latest commit. I don't think I published it with alpha-8 thought
