### ISSUE TITLE
[DataTable] - Table Overflow prevents Menus and Tooltips from displaying correctly

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#349]
If DataTable has popup elements like tooltip or menu, then these elements make table oversized. Table has extra scrollbars and pop elements are clipped.

I do some research and I found that css class 'md-data-table--responsive' has property 'overflow-x: auto;'. If I disable this property then problem disappear. But I'm not sure, disabling this property probably add some problems in other places.

![example](https://cloud.githubusercontent.com/assets/7845843/25470601/3525119e-2b23-11e7-9020-ea0e4ce66f5d.png)

**Comment by lext-7** [comment]
+1.  
Why not render the menu components outside the buttons and make them position fixed ?

**Comment by mlaursen** [comment]
Yeah, that is how the menu components work starting 1.1.0. I'm still working on migrating the tooltips over to being fixed as well. [1.1.0 Preview](http://react-md.next.mlaursen.com/components/data-tables)
