### ISSUE TITLE
Text instead of icons

### ISSUE THREAD

**Issue by intermundos** [mlaursen/react-md#358]
Hello,

I am having an issue with icons. Instead of icon there is a name of it. On every component I 've tried.

For example Date picker instead of calendar icon, has *date_range*.

Your help is appreciated.

![image](https://cloud.githubusercontent.com/assets/16274871/25772290/4f54216e-3270-11e7-8f19-13d8dc2608df.png)

**Comment by sniphpet** [comment]
Hello,

Did you include the material design icon font ?
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">`

**Comment by intermundos** [comment]
@sniphpet thank you! Thats the missing piece :)
