### ISSUE TITLE
[TimePicker] - TimePicker no longer selects times reliably

### ISSUE THREAD

**Issue by fellmann** [mlaursen/react-md#359]
### Description
Sometimes, the TimePicker does not respond correctly to mouse events. Especially on IE, but also on Chrome, iOS etc.

The bug occurs randomly when opening TimePicker dialogs. It responds to clicks, but the selected time is wrong.

### Link to a gist or code sample where the issue can be reproduced
As I said, it randomly occurs when opening dialogs. Still, for me a similar behavior can be reproduced (hopefully the same bug):
- Open https://react-md.mlaursen.com/components/pickers/time in Chrome 57
- Open any time picker
- Change browser window size
- Time selection should be buggy now

### Version
- React 15.3.2
- React-MD 1.0.13
- Browser Chrome 57, IE 11, Edge, Safari (mobile)

**Comment by baxford** [comment]
This is probably a different issue, but if I open the time picker example from the URL above in an ipad 2, I don't see any of the selection options when I click in a field. I also don't see any error output in the browser console.

**Comment by mlaursen** [comment]
After some more debugging, this issue seems related to the window's scroll position before a dialog is opened. If the TimePicker is opened when the user hasn't scrolled at all, it calculates correctly. If the user scrolled the page at least 50 pixels, the calculates stop working. Quite odd.
