### ISSUE TITLE
Open DatePicker/TimePicker with SPACE key

### ISSUE THREAD

**Issue by hisapy** [mlaursen/react-md#364]
This is more like a feature request.

```gherkin
Feature: Open DatePicker with SPACE key
  As a User
  I want the DatePicker/TimePicker to open when pressing SPACE key
  So I can avoid submitting forms accidentally when trying to open with ENTER

Scenario: DatePicker in a form
  Given a DatePicker inside a form
  When I focus on it
  And press SPACE key
  Then DatePicker should turn visible

Scenario: DatePicker won't open with ENTER
  Given a DatePicker inside a form
  When I focus on it
  And press ENTER key
  Then DatePicker should not turn visible

Scenario: Configure DatePicker to open with ENTER
  Given a DatePicker with prop openWithEnterKey
  When I focus on it
  And press ENTER key
  Then DatePicker should turn visible
```

**Comment by mlaursen** [comment]
I can do the first part of this in 1.0.14 (allow pickers to be opened by spacebar), but the second part will have to be in 1.1.0 since that is more of a feature request.

**Comment by hisapy** [comment]
No problem for me  ... The `open with ENTER` is something I wrote just in case of backward compatibility.

:)

**Comment by hisapy** [comment]
The problem with ENTER is just when you're in a form, and usually on Desktops UI used by people that needs to quickly navigate/populate the form using the usual keys.

**Comment by mlaursen** [comment]
I'll make it so that in 1.0.14 will prevent the enter keypress from opening the picker if the picker is inside of a form. If the picker is not in a form, the enter keypress will work as before. In next release, the enter keypress listener can be fully removed via a prop
