### ISSUE TITLE
[Dialog] - Scroll position changes after dialog closing

### ISSUE THREAD

**Issue by mctep** [mlaursen/react-md#367]
![untitled](https://cloud.githubusercontent.com/assets/1949681/26111506/f0449c12-3a5d-11e7-81ac-2d2a41adbfd4.gif)

http://react-md.next.mlaursen.com/components/dialogs

**Comment by mlaursen** [comment]
This might have been fixed with my dialog changes in 1.0.14. I'm working on merging the changes forward to find out.

**Comment by mlaursen** [comment]
Interesting. It appears to only happen if you click the overlay instead of one of the items

**Comment by mlaursen** [comment]
Since this fix was small, I think I'll bring this commit back from 1.1.x to 1.0.17
