### ISSUE TITLE
[Styling] - Unable to use css-modules with the keyframes in progress

### ISSUE THREAD

**Issue by fabiozaffani** [mlaursen/react-md#376]
I'm not sure if this is an issue we can address here in react-md but it's how the css-modules work when including sass files. In the case of react-md if we include, let's say, the react-md-progress, it will correctly include all it's styles but will fail when including the keyframes for the animation.

This happens because of how the keyframe names get changed when sass convert's it to CSS, for now the solution i'm using is to hardcoded the needed keyframes and use it a :global(keyframename) to avoid the issue, as explained in this comment by erikharper
https://github.com/css-modules/css-modules/issues/115#issuecomment-228224639

Code example of a locally working solution:

```
@keyframes :global(md-linear-indeterminate) {
   0% {
     left: -35%;
     right: 100%;
   }

   60% {
     left: 100%;
     right: -90%;
   }

   100% {
     left: 100%;
     right: -90%;
   }
 }
```

**Comment by amirburbea** [comment]
Actually can someone share a webpack config where they've used css-modules and allowed react-md to work (which is as far as I can tell incompatible with css-modules)

I've tried

```js
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader?importLoaders=1&modules&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
      'sass-loader',
    ]
  }),
```

but then my configuration seems to screw up react-md

if i avoid css-modules it of course works but I really wanted to use them.  Any help would be appreciated

**Comment by dgollub** [comment]
Running into the same issue. We use zeit/next.js (version 6.0.3) with the @zeit/next-sass plugin to compile our SCSS into CSS. So far we have no good solution to this.

**Comment by dgollub** [comment]
Just as an idea: maybe react-md could provide a mixin that outputs the `@keyframe` animations with and without the `:global` prefix. Wouldn't that work?

**Comment by mlaursen** [comment]
@dgollub I honestly know nothing about css modules. Are you saying I can do something like this?

```scss
@mixin react-md-keyframes($using-css-modules: $md-using-css-modules) {
  @if $using-css-modules {
    :global {
      @keyframes {
        @content;
      }
    }
  @else {
    @keyframes {
      @content;
    }
  }
}
```
?

I'll be happy to try something like that

**Comment by dgollub** [comment]
@mlaursen That looks like it should work, but I am actually not sure it will. We would need to test that.

The thing is that we include react-md's SCSS like this

```
html {
  :global {
    @import '~react-md/src/scss/react-md';

    $md-primary-color: $md-light-blue-500;
    $md-secondary-color: $md-light-blue-a-200;

    @include react-md-everything;

    @include react-md-theme-everything($md-blue-200, $md-blue-a-400, $md-light-theme, 'demo');
     // ....
  }
}
```

As you can see, that already has a `:global { ... }` wrapper around the react-md styles, therefore it should compile the `@keyframes` correctly, but it doesn't (hashes are appended to the keyframe names when they shouldn't).

However, this little "hack" works and compiles correctly to a global `@keyframe` in the final CSS file: 

`@keyframes :global(my-keyframe-name) { ... }`

Since this approach works I used it to copy all the `@keyframes` from react-md and included them that way in order to fix this short term for the project my team is working on. But it has the obvious downside of code duplication.

A slightly better short term solution, which switched to shortly after, is this 


```
html {
  :global {
    @import '~react-md/src/scss/react-md';

    $md-primary-color: $md-light-blue-500;
    $md-secondary-color: $md-light-blue-a-200;

    @include react-md-everything;

    @include react-md-theme-everything($md-blue-200, $md-blue-a-400, $md-light-theme, 'demo');
     // ....

    /*
      @keyframes and animations are not properly compiled when :global is involved
      There are open issues for this on

      * react-md: https://github.com/mlaursen/react-md/issues/376
      * webpack-contrib/css-loader: https://github.com/webpack-contrib/css-loader/issues/243

      However, this :local workaround makes things work again. It is a bit of code duplication
      effort, but unfortunately the best we can do right now until either of the issues above
      are fixed.
    */
    /* stylelint-disable selector-pseudo-class-no-unknown */
    .md-progress--circular-indeterminate :local {
      animation-name: md-circular-progress;
    }

    .md-circular-progress-path--animated :local {
      animation-name: md-circular-progress-dash;
    }

    .md-progress--linear-indeterminate :local ::before {
      animation-name: md-linear-indeterminate;
    }

    .md-progress--linear-indeterminate :local ::after {
      animation-name: md-linear-indeterminate-short;
    }

    .md-ink--pulsing :local {
      animation-name: md-ink-pulse;
    }
    /* stylelint-enable selector-pseudo-class-no-unknown */
  }
}
```

This has the upside that it is less code duplication; there is still some, but at least I don't have to duplicate the actual keyframes any longer.
