### ISSUE TITLE
Allow NavigationDrawer to modify style/class of navItems list

### ISSUE THREAD

**Issue by Skysplit** [mlaursen/react-md#377]
### Description
Currently it is possible to edit `navClassName` and `navStyle` in standalone `Drawer` component but it is absent in `NavigationDrawer`

### Version
- React: 15.3.1
- React-MD: 1.0.14

**Comment by mlaursen** [comment]
They are actually still passed to the `Drawer` from the `NavigationDrawer`, it looks like I just didn't document them correctly (All undocumented/remaining props are passed to the `Drawer`). I'll update that.

**Comment by Skysplit** [comment]
Thanks for lighting fast response! Nice to hear that.

Great job with this library!
