### ISSUE TITLE
[Violation] Passive event listeners

### ISSUE THREAD

**Issue by mvuherer** [mlaursen/react-md#382]
### Description
InkContainer (possible some others as well) emit a violation due to non passive event listener that do not prevent default action.
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
```
### Solution
Adding `{ passive: true }` to event listeners that **do not** prevent default action.
Such as lines 235, 247 and 248 in InkContainer.js

### Version
- React: 15.5.4
- React-MD: 1.0.14
- Browser  Chrome (58)

P.S. was trying to submit a PR for that but got denied T_T

**Comment by mlaursen** [comment]
Hmm. I didn't think I had anything preventing pull requests... Not sure what caused that :/

**Comment by francesco-carrella** [comment]
Same issue here
