### ISSUE TITLE
Snackbar doesn't dismiss when specifying onClick

### ISSUE THREAD

**Issue by makslevental** [mlaursen/react-md#385]
pretty sure the problem is here:
https://github.com/mlaursen/react-md/blob/master/src/js/Snackbars/Snackbar.js#L160

by using `action` in `Object.assign` you overwrite this assignment

https://github.com/mlaursen/react-md/blob/master/src/js/Snackbars/Snackbar.js#L153

which already calls `action.onClick`

https://github.com/mlaursen/react-md/blob/master/src/js/Snackbars/Snackbar.js#L77

consequently in that conditional should also be `btnProps.label = action.label;`

**Comment by makslevental** [comment]
should i close this?

**Comment by mlaursen** [comment]
I'll go ahead and close it. Thanks!
