### ISSUE TITLE
[SelectField] - Implement a readOnly SelectField

### ISSUE THREAD

**Issue by hisapy** [mlaursen/react-md#387]
This is a possible bug

Version: **react-md 1.0.15**
Tested in browsers: **Safari Version 10.1 (12603.1.30.0.34)** and **Google Chrome Version 58.0.3029.110 (64-bit)** 
OS: MacOS Sierra

**Current behavior**

When a `SelectField` is given `readOnly` prop, the component opens and the selected value can be changed.

**Expected behavior**

When I pass `readOnly` prop to `SelectField` then the component should not open and change

Thanks in advance

**Comment by mlaursen** [comment]
It actually looks like the `readonly` attribute is not available for [select tags](https://www.w3schools.com/tags/tag_select.asp) so I'm not sure if I'll implement it here. I think doing `disabled` instead would be preferred. I might add it in a later release though.

> other: [html form readonly SELECT](https://stackoverflow.com/questions/368813/html-form-readonly-select-tag-input)

**Comment by hisapy** [comment]
No problem then @mlaursen ... I understand and agree with the decision following the DOM behavior. I'm going to render a different component for my `readOnly` state. 

I believe you can close this issue.

Thanks.
