### ISSUE TITLE
[DatePicker] - Doesn't display on iPad

### ISSUE THREAD

**Issue by baxford** [mlaursen/react-md#388]
### Description
First up, thanks for this amazing library, it is so nice to use, we are really happy with how it works and the great documentation!
I noticed an issue with the Datepicker on a site I am working on, only on iPad2. It basically caused other components to fail in their rendering and just show a white page.
I was unable to find an error when debugging, and there is no console output to indicate any errors.
When viewing the examples for the Date picker (https://react-md.mlaursen.com/components/pickers/date) I also just see a white screen with no errors in the console.

### Images/Screenshots
![img_0001](https://cloud.githubusercontent.com/assets/914289/26535691/192ddf34-4473-11e7-9388-749da99ff0b7.jpg)

### Link to a gist or code sample where the issue can be reproduced
I have written a codepen to try and replicate - this actually renders a DatePicker, however the formatting is a little off in Safari on an iPad2
https://codepen.io/baxford/pen/dWEqyY

Alternatively, just viewing https://react-md.mlaursen.com/components/pickers/date in Safari on an iPad 2 gives me a blank screen as indicated on the attached screenshot.

### Version
- React (whichever version is used on the react-md demo site)
- React-MD (whichever version is used on the react-md demo site)
- Safari on IOS 9.3.5. Ipad 2

If I can assist with debugging this issue please let me know. If there are any pointers you can provide it would help greatly.
thanks!

**Comment by mlaursen** [comment]
This might be because  of my lazy addition of the Intl polyfill. I'll check it out

**Comment by mlaursen** [comment]
I _think_ this is fixed with my server rewrite at https://react-md.next.mlaursen.com, but I'm not really sure. I only have an iPad mini that appears to work for both sites
