### ISSUE TITLE
[Overlays] - Update components with Overlays to expose props to modify the overlay

### ISSUE THREAD

**Issue by nbolten** [mlaursen/react-md#389]
### Description

Components such as Drawers and Dialogs have a boolean prop (`overlay`) to specify whether an overlay should be created when the parent component is visible. While the implementations for each overlay seems to vary between components, it would be nice to have the ability to pass (mostly style) props to the overlays such as opacity, color, size, z-level, etc.

For example, I currently want to make the overlay for a Drawer transparent so when the Drawer is open, clicking outside the drawer closes it and the rest of the app is still visible. I know that I can modify this via scss at the component level, but it would be nice to have access at the component level as well.

### Images/Screenshots

N/A, the requested feature doesn't exist yet.

### Link to a gist or code sample where the issue can be reproduced

N/A, not an issue, is a feature request.

### Version
- React: v15.4.2
- React-MD: v1.0.15
- Browser: Chrome, Firefox

**Comment by mlaursen** [comment]
I ended up adding some hooks for both the `Drawer` and `NavigationDrawer`. The `Dialog` should have this available by using the `style` and `className` props already (the overlay is the top level component).
