### ISSUE TITLE
contained=false menu is still contained

### ISSUE THREAD

**Issue by makslevental** [mlaursen/react-md#391]
![image](https://cloud.githubusercontent.com/assets/5657668/26642767/fc10e848-45fc-11e7-84c7-88358af83d5b.png)

i can't quite figure this out because i'm a n00b but for

```javascript
<MenuButton
  ...
  contained={false}
  position={Positions.BELOW}
  ...
>
```
dropdown menu is still "contained".  i believe this https://github.com/mlaursen/react-md/blob/05f5b39641b6c452ea89f851be642467716b863f/src/scss/components/_menus.scss#L113

should just be omitted since adding `md-list--menu-contained` adds `width: 100%`

**Comment by makslevental** [comment]
so you can see the classname directly 

![image](https://cloud.githubusercontent.com/assets/5657668/26643528/9dc63fec-45ff-11e7-9ade-889237bd849f.png)

**Comment by makslevental** [comment]
should i close this?

**Comment by mlaursen** [comment]
I'll go ahead and close this as well. Thanks!
