### ISSUE TITLE
why md-grid and md-cell--middle is not centering?

### ISSUE THREAD

**Issue by ivmarcos** [mlaursen/react-md#393]
### Description

Why md-grid and md-cell--middle is not working? Is something wrong with the code?

```
 <div className="md-grid parent">
     <div className="md-cell md-cell--middle child">
            this should'nt be centered?
     </div>
</div>
```

### Images/Screenshots

![captura de tela de 2017-05-31 14-35-49](https://cloud.githubusercontent.com/assets/1471237/26645473/7f9074e8-460e-11e7-961c-f7bd48a34044.png)

### Code pen
https://codepen.io/ivmarcos/pen/jmgzZM

### Version
- React 15.5.4
- React-MD 1.0.15

**Comment by mlaursen** [comment]
So `md-cell--middle` actually only places it in the middle of the container vertically. To center it horizontally, you just need to add `margin-left: auto; margin-right: auto` to the cell. I guess I could make an additional class `md-cell--center` that would do the horizontal centering. So if you wanted an absolute centered element, you could provide `"md-cell md-cell--center md-cell--middle"`

**Comment by ivmarcos** [comment]
I think is a good idea, considering how often this may be used. Till then, I'll make as suggested. Tks @mlaursen!

**Comment by marlomajor** [comment]
@mlaursen I can't get datepicker centered with the page and none of the above helps. Any idea what's going on?
