### ISSUE TITLE
[EditDialogColumn] - Unable to create a Single Row DataTable with an EditDialogColumn

### ISSUE THREAD

**Issue by mvuherer** [mlaursen/react-md#394]
### Description
When theres only one row with EditDialogColumn row kind of breaks. 
### Link to a gist or code sample where the issue can be reproduced
Remove all but one row on "Configurable Data Table Example" and it will reproduce.
### Version
- Browser: Latest Chrome

**Comment by mvuherer** [comment]
Basically the calculation for the margin happens too early, maybe rethink all of the calculations that happen based on current view and usage, and move to positioning by parents or component its self

**Comment by mlaursen** [comment]
I'm going to target this for the `1.1.0` release since I did a rehaul of the menus/dialogs and this problem is solved there.

http://react-md.next.mlaursen.com/components/data-tables

**Comment by mvuherer** [comment]
Thanks for the update!
