### ISSUE TITLE
[Documentation] Spotify now requires oAuth

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#395]
All spotify endpoints now require oAuth for access so I need to think of new ajax examples. *sigh*

**Comment by amirburbea** [comment]
is there an update? any simple ajax example would be neat

**Comment by mlaursen** [comment]
Not really. I'm about 1/2 of the way with rewriting my server for the 1.1.0 release with a lot more documentation, but I'm not sure how to bring the API changes back easily. Part of the problem is that my ajax examples rely heavily on the returned data structure to display and do other logic so I have to remake them from the ground up :/

**Comment by mlaursen** [comment]
This should be fixed now at https://react-md.next.mlaursen.com Sadly I can't bring this back since this was my server re-write and isn't backwards compatible for older versions of react-md.

**Comment by amirburbea** [comment]
That's great - the sample works for me.

When is 1.1 going official on npm? I'm constantly pulling new versions of
your package from GitHub, building them myself and running npm pack on
them. I need at least 1.1 because I'm using TypeScript

**Comment by mlaursen** [comment]
Oh, you should be able to do `react-md@next` in your dependencies to get that working. I've been publishing each of the alpha releases on the next tag. I'm hoping for a final release at the start of September, but that's only if I can fix the final major issues with my Layover component
