### ISSUE TITLE
Can't reset Date Picker

### ISSUE THREAD

**Issue by operolim** [mlaursen/react-md#396]
I've tried following the example on the react-md site where the date picker gets reset (Last example on the page and is titled "Fully Controlled Example") by setting the date picker value to null once the reset button (or the x icon on the react-md site) is clicked, but that doesn't work and it causes the page to break and become unresponsive. 

Here's a screenshot with a date selected and before the reset button (x icon) is clicked. 
![image](https://cloud.githubusercontent.com/assets/4361051/26728054/8f5f8b5a-476e-11e7-89e1-3cdf25e09bd8.png)

Here's a screenshot of what happens once you click on the date field after the value gets cleared out. 
![image](https://cloud.githubusercontent.com/assets/4361051/26728059/940a5450-476e-11e7-9ac0-7fdcdd2fb7b9.png)

This issue may be related to #384

**Comment by mlaursen** [comment]
Hmm. Doesn't look like it linked correctly, but this should be fixed in 8b4b553.
