### ISSUE TITLE
[Drawer] - Width and positioning issue across screen sizes when Drawer is set with position="right"

### ISSUE THREAD

**Issue by fabiozaffani** [mlaursen/react-md#397]
This bug hapenned to me while using the drawer with position: right set and by looking at the code I think this is some unintended effect related to the user screen size.

Currently in the file https://github.com/mlaursen/react-md/blob/master/src/js/Drawers/Drawer.js, starting in line 237:
```
/**
     * The drawer's position on the page when it is not `inline`. When the drawer's position is `left`,
     * the width will be `calc(100vw - 56px)` on mobile devices and `$md-drawer-desktop-width` on desktops.
     *
     * When the position is `right`, the width will be `100vw` for mobile devices and scaling to the drawer's
     * children width on desktops.
     */
    position: PropTypes.oneOf(['left', 'right']).isRequired,
```

But what's currently hapenning is, the following attribute get's applyed while the Drawer is in { desktop: true } media type.

```
@media screen and (max-width: 1024px) and (min-width: 320px)
.md-drawer--right {
    left: 0;
    transform: translate3d(100%, 0, 0);
```

This makes the Right Drawer fill the entire screen width starting in a 1024 px resolution, actually it should be in 960px (the current react-md default Tablet width size).

### Version
- React: 15.5.4
- React-MD: 1.0.15

**Comment by turnerniles** [comment]
@fabiozaffani I am confused how to change the right positioned drawer's width on mobile (don't want fullscreen at 1024px, would perfer 768px). Do you know how to override the width of the drawer on mobile without using !important?
