### ISSUE TITLE
[NavigationDrawer] - Tabs should be worked into the Navigation Drawers

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#4]
Need to figure out how tabs should work in navigation drawers.

Should it be children with a prop saying children are tabs? Pass in a list of tabs as props?

It should eventually be that navigation drawers would choose the correct content to display based on a tab.

**Comment by mlaursen** [comment]
This is _technically_ doable in v1.0.0 by passing the `Tabs` as the `toolbarChildren` prop, absolutely positioning the tabs, and enabling `toolbarProminent`. It does not allow for the `TabsContainer` and  the swiping though.

**Comment by daniel5151** [comment]
Any update on this?

Also, if not, can you give an example of the absolute positioning SCSS needed to get it kind of working?

**Comment by mlaursen** [comment]
Right now, I don't have it targeted for any release. But here is how it was implemented for my website:

https://github.com/mlaursen/react-md/blob/master/docs/src/client/_styles.scss#L11-L28
