### ISSUE TITLE
TextField with multiple rows renders badly

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#402]
### Description

When specifying rows={6} for a TextField, the label and placeholder text get mangled. Also there is too much whitespace above the textfield.

### Images/Screenshots

Screenshot: http://take.ms/2CkjF
Codepen:  https://codepen.io/stickfigure/pen/weMKMJ

### Version
- React 15.4.2
- React-MD 1.0.15
- Browser latest chrome

**Comment by mlaursen** [comment]
I believe this is the same issue as #365

**Comment by stickfigure** [comment]
Ah, I had tried adding a div and it didn't work... but now I realize there was an extra div in between. Yep, duplicate.
