### ISSUE TITLE
[DataTable] - Specifying column width

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#405]
I’m not sure whether it should consider library or maybe my own customisations. Currently, there is no way (within the library) to set a maximum width of the columns in the table. In other words, the table covers all width of the parent element (width: 100%) until the content fits in the table. If there is more content, then the columns in the table widen so as to fit to the content but the size of the table exceeds the size of the element in which it is situated (over 100% of width) and therefore, we are forced to scroll it vertically and horizontally, what is really inconvenient.

We would like to have an opportunity to controll, by using one parameter, whether we want the entire content of the table to be seen but having to scroll it (as it is now) or whether we want to see the table with the width the same like the parent element but having to hide a part of the content.

Here is the example: https://codepen.io/MichalWadowski/pen/pwjpqg

**Comment by scuba6388** [comment]
> Would it fit into this issue to request to be able to specify the exact width of the column (percent, px, etc.)? I.e. so we can have a super wide column, and then a tiny little one?

If you set CSS on the table, you can do manual column sizing. On DataTable set "table-layout: fixed;" the table will then respect your column sizing when you set style on TableColumn in the header.  You can set style "width: _n_px;"  To ensure that column sizing is respected if your column widths add up to less than the table width you can just add a dummy column with blank header and cells with a width of 100%.
