### ISSUE TITLE
[DataTable] - Setting Row Height

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#406]
Why for the tables with checkboxes (not plain) cannot we adjust the rows with broader heights? We would like to have an opportunity to automatically set the height of rows when the content will not fit. I think it’s a better solution than forcing users to scroll it in two dimensions.

If it's not possible to set automatically of rows height, then maybe solution is preserve double or triple row height like it is used in List components.

**Comment by mlaursen** [comment]
I think part of this problem was my bad implementation of the table formatting. I relied on padding and height to align things in the center instead of just `vertical-align: middle`. I think changing to that and removing my plain styles will allow for easier height adjustment.
