### ISSUE TITLE
Snackbar does not play nice with mini drawer

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#410]
### Description

The snackbar appears behind the mini-drawer, but text is not indented. Seems like either the snackbar should have a higher z-index or the text should be indented.

### Images/Screenshots

http://take.ms/YTNPX

### Version
- React 15.4.2
- React-MD 1.0.15

**Comment by mlaursen** [comment]
I ended up increasing the zIndex for the first pass. I'm not sure how I feel about indenting it.
