### ISSUE TITLE
Autocomplete throws error when rendered within a ListItem

### ISSUE THREAD

**Issue by spalladino** [mlaursen/react-md#412]
Greetings! We have stumbled upon an issue where an Autocomplete rendered inside a ListItem throws an error. See [this snippet](https://codepen.io/anon/pen/ZyBgPM?editors=0010) for an example.

The error seems to be caused by [handleClick](https://github.com/mlaursen/react-md/blob/master/src/js/Autocompletes/Autocomplete.js#L636-L650), that traverses the entire hierarchy looking for a list item, assuming it belongs to the autocomplete, and it has been clicked to select a suggested value. Since it finds a ListItem that _contains_ the autocomplete, and has no value associated, it fails when attempting to apply the filter (caseInsensitive in the example case) to an undefined text.

**Comment by spalladino** [comment]
Note that using a ListItemControl instead of a regular ListItem works, though a console error is logged: `Uncaught (in promise) ReferenceError: Autocomplete is not defined`

**Comment by spalladino** [comment]
We have fixed the console error by inheriting from Autocomplete and patching the `_handleClick` method [line 639](https://github.com/mlaursen/react-md/blob/master/src/js/Autocompletes/Autocomplete.js#L639) with the following condition:
```
if (target.classList.contains('md-list-item') && target.parentNode.classList.contains('md-autocomplete-list'))
```

**Comment by mlaursen** [comment]
I ended up fixing this by making sure that the `target` is still within the `Autocomplete`'s container, so that any parent nodes will not be traversed as well.
