### ISSUE TITLE
[TablePagination] - The TablePagination does not reposition correctly if the parent table's width changes

### ISSUE THREAD

**Issue by c0b41** [mlaursen/react-md#415]
https://codepen.io/anon/pen/yXgOMQ/

### Version
- React 15.5.4
- React-MD 1.0.15
- Browser  -

**Comment by rosunshrestha** [comment]
I have the same problem. When I put rows props, pagination does not work. @mlaursen

**Comment by mlaursen** [comment]
Would you mind explaining what the problem is? (It might be a problem with my documentation) The `rows` prop is supposed to be the number of rows in your dataset so that the pagination knows it can get the next set. The `rowsPerPage` prop is for displaying a certain number of rows at a time.

**Comment by c0b41** [comment]
@mlaursen  https://www.useloom.com/share/b4c7e1abc10c4300a6d89a3622fb8937

**Comment by mlaursen** [comment]
Ahh thanks! That clears it up a bit more
