### ISSUE TITLE
[Theming] - Theme does not load colors for components

### ISSUE THREAD

**Issue by Tarvald** [mlaursen/react-md#417]
Hi,
I included react md into my project but tabs component does not have any colors in style. 

```
@import '~react-md/src/scss/_react-md';
@import '~react-md/src/scss/colors';

$md-primary-color: $md-teal-500;
$md-secondary-color: $md-pink-a-400;

@include react-md-everything;
```

I also tried to add: 
`@include react-md-theme-everything($md-primary-color, $md-pink-a-200);
`
but i didn't change anything. I have latest version of react md, problem is on any browser. I am using postcss loader via webpack.
![image](https://user-images.githubusercontent.com/7673542/27476437-0cd34054-5809-11e7-8fa9-eb0474535cb5.png)

Can you help me?:)

Best regards

**Comment by mlaursen** [comment]
Hmm. You should be able to just do:

```
@import '~react-md/src/scss/react-md';

$md-primary-color: $md-teal-500;
$md-secondary-color: $md-pink-a-400;

@include react-md-everything;
```

The [examples folder](https://github.com/mlaursen/react-md/tree/master/examples) has a few use cases of using create-react-app or a custom webpack config file and overriding the theme there. Hopefully that might be of some use?

**Comment by shrupa** [comment]
I have a similar requirement, I need to change the color of text in tabs but not able to do so. I'm unable to find anything similar in examples provided on github. Please advise.
