### ISSUE TITLE
[NavigationDrawer] - react-router Links aren't updated synchronously

### ISSUE THREAD

**Issue by yuwiggin** [mlaursen/react-md#419]
### Description 
I tried the [examples](https://github.com/mlaursen/react-md/tree/master/examples/with-react-router-v4) and found that in a small browser window(width <1024 px, when I clicked the navigation link(i.e. "Page 1") in the left drawer, the navigation link wasn't highlighted/activated accordingly but was activated in the next click. 
### Images/Screenshots
![image](https://user-images.githubusercontent.com/812370/27507200-b725ad64-58fc-11e7-90ff-0cf71e26a37a.png)

### Version
- React: 15.5.4
- React-MD: 1.0.15
- Browser: Chrome 58.0.3029.110 (64-bit)

**Comment by williegroovy** [comment]
Not sure if this would be considered hacky or not, but if you haven't already figured out how to make this work, allow me to share.

```
const navList = [
   {
      to: '/dashboard',
      label: 'Home',
      icon: 'home',
      exact: true
   },
   {
      to: '/dashboard/tables',
      label: 'Tables',
      icon: 'line_style',
   },
   {
      to: '/dashboard/media',
      label: 'Media',
      icon: 'theaters',
   }
];
```

Next I map over drawerNavItems like so:
```
<NavigationDrawer
        toolbarProminentTitle
        toolbarTitle="Richardson Demo"
        navItems={navList.map(item => 
           <NavLink {...item} location={props.location} key={item.to} />))
```

That allows me to access location.pathname for use in comparing against the Links 'to' prop.
```
const NavLink = (props) => {
  let leftIcon;
  if (props.icon) {
    leftIcon = <FontIcon>{props.icon}</FontIcon>;
  }

  return (
    <ListItem
      component={RouterLink}
      to={props.to}
      active={props.location.pathname === props.to}
      primaryText={props.label}
      leftIcon={leftIcon}
    />
)
};

export default NavLink;
```
