### ISSUE TITLE
[Autocomplete] - onAutocomplete callback should also pass back dataValue

### ISSUE THREAD

**Issue by jbetancur** [mlaursen/react-md#425]
Currently, there seems to be no way to get the `dataValue` from an Autocomplete component via the `onAutocomplete` method when using a `data` property that is an array of objects. The dataValue is very useful for filtering a larger list via a unique id, or additional parameters when selecting a search entry. Unless there is a workaround you could suggest where I could get access to the dataValue onAutocomplete, would it be possible to add this to the API?

### Version
- React latest
- React-MD 1.0.15

**Comment by mlaursen** [comment]
I think this is a good idea. I can simply add the current `dataValue` as the forth param for now. Ideally the order should be `(label, value, index, matches)`, but it's a bit hard for backwards compatibility
