### ISSUE TITLE
[Deprecation/Updates] - Change usage of findDOMNode to ref callbacks

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#427]
There are a lot of cases where I use the `findDOMNode` API to access the real `HTMLElement` to do calculations or other things. Unfortunately, this means that components can not be run with the jest snapshot feature since it does not support `findDOMNode`. In addition, it looks like `findDOMNode` might be removed from the ReactDOM API since it is considered useless when there are ref callbacks.

### Possible Problems
There are some components that really use the `findDOMNode` api since any renderable element can be used ('div', 'span', SomeCustomComponent, etc). This will have to be solved by either adding an additional hidden `div`, or `span` into the dom just to gain access to a dom element.

**Comment by Ardhimas** [comment]
Any idea when this would be worked on? No pressure, I simply ran into the findDOMNode problem with snapshot testing.

**Comment by mlaursen** [comment]
This one will probably be much later down the road. I have a [Testing Guide](https://react-md.next.mlaursen.com/discover-more/testing#snapshot-testing) that goes into some more detail about how you solve the snapshot problems until a real solution has been figured out and implemented.
