### ISSUE TITLE
[Autocomplete] - Focus of TextField in Autocomplete should be controllable via props

### ISSUE THREAD

**Issue by nbolten** [mlaursen/react-md#428]
### Description
By default, Autocomplete components place focus on the TextField after an entry has been selected, making these key updates to state:
- The Autocomplete gets 'manualFocus: true'.
- The TextField of the Autocomplete runs its `.focus()` method, making it focused.

There are cases where this may not be desirable, particularly on mobile devices. Here's the events that happen on mobile:

1) User selects the Autocomplete. The mobile keyboard launches, resulting in an effect change in screen height.
2) The user types in the Autocomplete, generating Autocomplete items.
3) The user clicks an Autocomplete item (mousedown) and it receives focus (to make the ink effect?). The mobile keyboard closes / starts to close.
4) The .focus() method eventually runs on the TextField. This can interrupt any ongoing actions that monitor focus or changes in effective screen height.

In my case, the TextField actually interrupts something largely outside of React's control (a react-mapbox-gl ReactMapboxGl component), causing it to send 'moveend' events. It seems to be a result of the mobile keyboard resizing the window, and therefore the 100% height canvas (the map is drawn on a canvas element). While this may be an additional bug in the ReactMapboxGl component (or mapbox-gl-js), it's probably useful, in general, to be able to skip the automatic focus of the Autocomplete.

For example, one may want to put focus onto a specific element (such as the next text field of a form) once an Autocomplete item is selected, by setting onAutocomplete to a function that does so. But the setState callback will be called after that, placing focus back on the Autocomplete. As a result, the text field we want receiving focus only gets it temporarily, and appears a bit glitchy: the mobile keyboard opens during input on the Autocomplete, closes on selecting an item, opens again when selecting the next text field, then closes once focus is set on the Autocomplete, and opens again when the Autocomplete actually gets focus.

I'm happy to put in a pull request, but I wasn't sure what approach you would prefer. What about a focusOnClick={} boolean prop for the Autocomplete? If false, _handleItemClick would:
1) Set manualFocus to false
2) Not set the this._field.focus() callback

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/jwadbR

This example is essentialy what was described above: an Autocomplete that is supposed to focus the next text element on autocomplete, but instead ends up doing so for only a miniscule amount of time before focus is restored to the Autocomplete's own TextField. This is particularly noticeable on slow mobile devices, where there is significant time between showing/hiding the keyboard.

### Version
- React 15.4.2
- React-MD 1.0.15

**Comment by mlaursen** [comment]
After looking at some other autocompletes, it looks like my implementation might be bad. They normally don't focus the other elements in the autocomplete list; just apply a highlight color and keep the focus on the text field at all times.

The only reason I did the focus immediately afterwards was for keyboard support, but it looks like not doing this manual focus still focuses the next element correctly with tab and focuses the text field again with shift+tab. I think the first patch will be just to make this focus disableable, and maybe rework like other autocompletes to not focus the list items.
