### ISSUE TITLE
[EditDialogColumn] - onClick prop is not being called correctly

### ISSUE THREAD

**Issue by pferdone** [mlaursen/react-md#433]
### 1.1.0-alpha5
- Browser: Chrome v57

I updated to react-md to 1.1.0-alpha5 in hopes to resolve this bug **Single Row with EditDialogColumn** #394. The layout seems to be ok now, but the onClick method isn't triggered although the EditDialogColumn opens up on click and presents its dialog.

**Comment by mlaursen** [comment]
I linked the wrong ticket in the commit message, but this should be fixed after 80360aa.
