### ISSUE TITLE
Focus issue on mobile (iOS and Android) when tapping on next TextField

### ISSUE THREAD

**Issue by mgolus** [mlaursen/react-md#434]
On both iOS (and I believe Android), if you have a short form on a page, such that the page scroll position will adjust slightly when the on-screen keyboard gets shown or is hidden, you cannot reliably focus on other fields on the form or click on buttons/tabs/etc.

It seems that this is possibly because the blur event gets fired first which is causing the keyboard to disappear. The target of the click event then gets processed incorrectly as the click event is fired as the keyboard is hidden and whatever element is in the position of the tap when this event is fired is taken as the target.

This can reproduced on the documentation page by going to https://react-md.mlaursen.com/components/text-fields on an iOS device and then viewing the last example on that page which opens a full screen form:

![sample2](https://user-images.githubusercontent.com/2809136/27803495-bdb42ca8-5ff7-11e7-975b-bd5463a30b00.gif)

Notice how if you tap (or click in iOS simulator) in the text area, it focuses the field above where you tapped, not the text area.

The issue can also be reproduced using a simple example:

```
class Example extends React.Component {
  render() {
    return (
      <div>
        <div>
          <br /><br /><br /><br /><br /><br /><br /><br /><br />
        </div>

        <TextField
          id='test1'
          label='test'
        />
        <TextField
          id='test2'
          label='test'
        />
      </div>
    );
  };
};
```

Which looks like:

![sample1](https://user-images.githubusercontent.com/2809136/27803515-e060c0a4-5ff7-11e7-98f9-562f25c6a789.gif)

Once again, tapping the bottom form field focuses the top one. If the bottom form field is focussed, tapping the top one will unfocus both fields.

**Comment by mgolus** [comment]
I did some further research and believe I have found the issue. In TextField, listeners are attached to touchstart and mousedown for the handleOutsideClick:

```
      fn('mousedown', this._handleOutsideClick);
      fn('touchstart', this._handleOutsideClick);
```

On the TextField itself though, the onClick event is being used to handleContainerClick:

`onClick={this._handleContainerClick}`

This means that when the user starts the touch on the mobile device the keyboard starts to slide down. Whatever is under the users finger once they complete the tap (or click) is what gets handled as the click event target.

**Comment by mgolus** [comment]
Playing with standard form controls, it seems that mobile behaves different than desktop in that mousedown on desktop triggers a blur on the input elements but it takes a touchend to trigger the blur on mobile devices. Changing the line:
```
fn('touchstart', this._handleOutsideClick);
```
to
```
fn('touchend', this._handleOutsideClick);
```
and changing the appropriate line in componentWillUnmount seems to resolve the problem.

**Comment by mlaursen** [comment]
Thanks for all the research for this one! I think I am actually going to remove the manual blur event on mobile devices instead of switching it to `touchend`. I tried out a couple of other frameworks and the native inputs, and the behavior appeared to be:

### iOS
The only way to dismiss the keyboard is to hit the "Done" button on it. Scrolling anywhere on the page and touch anywhere on the page did not actually dismiss your keyboard.

### Android (Samsung Galaxy S7)
Scrolling anywhere on the page did not trigger the keyboard to close. However, touching anywhere else on the page that was not an input or textarea closed the input.

I will go with this same behavior with my library.
