### ISSUE TITLE
[Autocomplete] - Autocomplete does not pass spaces v1.1.x

### ISSUE THREAD

**Issue by mctep** [mlaursen/react-md#443]
### Description

It is impossible to enter space to `Autocomplete` input.

### Link to a gist or code sample where the issue can be reproduced

http://react-md.next.mlaursen.com/components/autocompletes

### Version
- React-MD v1.1

**Comment by mlaursen** [comment]
I'll bring forward the changes from 1.0.x as a quick patch since I fixed it there: b13f316

**Comment by mlaursen** [comment]
This should be fixed in the alpha-8 patch
