### ISSUE TITLE
[TimePicker] - TimePicker value is set to next day when time is set to AM

### ISSUE THREAD

**Issue by benhunt29** [mlaursen/react-md#446]
The value of the date object behind the TimePicker is set to the next day when a time in AM is selected. 

For example: 
Display Time: 1:15 PM, Date Obj: Thu Jul 13 2017 13:15:00 GMT-0500 (CDT)
Display Time: 5:30 AM, Date Obj: Fri Jul 14 2017 05:30:00 GMT-0500 (CDT)

I'm not sure if this was done on purpose but I think the times should correspond to the same day

**Comment by mlaursen** [comment]
Yeah, this is definitely a bug. I'll target it for next patch.

**Comment by benhunt29** [comment]
@mlaursen great, thanks!

**Comment by benhunt29** [comment]
@mlaursen FYI this also goes the other way, if the initial time is set to AM, selecting a new time in PM results in Date with the date set to the previous day.

Display Time: 1:15 AM, Date Obj: Thu Jul 14 2017 13:15:00 GMT-0500 (CDT)
Display Time: 5:30 PM, Date Obj: Fri Jul 13 2017 17:30:00 GMT-0500 (CDT)
