### ISSUE TITLE
[Layover] Layover doesn't expand on correct anchor point

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#449]
Hey,

I'm trying to build a notification system using the Layover component. This Layover should expand on click on my navbar icon, at anchor (x: CENTER, y: BOTTOM). It works most of the time, but sometimes it does not and instead appears at (x: RIGHT, y: BOTTOM).

![doesn t work](https://user-images.githubusercontent.com/30187797/28233740-4370c46e-68f9-11e7-88d4-92b87d480cf1.png)

Working example :

![works](https://user-images.githubusercontent.com/30187797/28233743-4851b0c4-68f9-11e7-913b-e3be17127561.png)
 
Here's what generates the Layover : 

```javascript
<Layover
              visible={ this.state.expanded }
              toggle={ toggle }
              onClose={ () => this.setState({ expanded: false }) }
              animationPosition={ Layover.Positions.TOP_LEFT }
              anchor={ anchor }
              belowAnchor={ anchor } >
                <List id='notification-list' className="md-list--menu">
                    <NiceScroll onId='notification-list'/>
                    { notifications.map(notif =>
                        <Notification key={ notif.id } notification={ notif }/>
                    )}
                </List>
            </Layover>
```

anchor is defined as : 
```javascript
let anchor = {
            x: Layover.HorizontalAnchors.CENTER,
            y: Layover.VerticalAnchors.BOTTOM
        };
```

Thanks in advance.

**Comment by mlaursen** [comment]
This one is hopefully related to #345

**Comment by ostrebler** [comment]
Seems like, yes. The problem occurs when I click fastly on the button, but sometimes also when I click normally.

**Comment by mlaursen** [comment]
This one might be fixed now. I haven't released this in the latest patch though. I'll close this once it has been released.
