### ISSUE TITLE
Navigation Drawer persist_mini broken on react router v4 example

### ISSUE THREAD

**Issue by jackielii** [mlaursen/react-md#453]
### Description
In v1.0.16, Navigation Drawer if have type PERSISTENT_MINI, and when in mini icon mode, clicking on the icon doesn't highlight the current active route. In the example of current master repo, it works because it's using v1.0.11

### Images/Screenshots
![screenshot](https://user-images.githubusercontent.com/360983/28283389-865520d0-6b25-11e7-9a58-a97bc6a71f9e.png)

### Link to a gist or code sample where the issue can be reproduced
![image](https://user-images.githubusercontent.com/360983/28283626-2ef721fc-6b26-11e7-92d3-7ac7c776e1a9.png)

### Version
    "react-dom": "^15.5.4",
    "react-md": "^1.0.16",
    "react-router-dom": "^4.1.1",

**Comment by c0b41** [comment]
already opened  this issue #344
