### ISSUE TITLE
[Documentation] - Typography examples

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#456]
In typography example page is show 11 of formatting types. There are enumerated but name of formatting type class is not directly associated with its example. I mean, if I choose some format, I have to count number of example, and count enumerated classes to select proper class name.

It's not big deal, but it will be nice if example texts will be replaced with their class names.

**Comment by MichalWadowski** [comment]
There is my proposition: https://github.com/MichalWadowski/react-md/commit/6fdca291268bcff7df962021a65f36464987338f

**Comment by mlaursen** [comment]
The reason I went with the current words was to support some mobile devices since they overflow oddly. I think I'll go with what you proposed, but update the scroll behavior or line wrapping on mobile. It _is_ supposed to be a documentation site, so the easier it is to get information; the better.

**Comment by mlaursen** [comment]
I added what you suggested and did a fix for mobile devices. Thanks!

**Comment by MichalWadowski** [comment]
Maybe better will be ```overflow: visible;``` for .md-display-4, because now it has extra scrolls.

**Comment by mlaursen** [comment]
I'm personally fine with the additional scroll bars on mobile. I just don't want the page layout the break while on mobile. When there is visible overflow, it breaks the fixed header and other things. It isn't super ideal though.

**Comment by mlaursen** [comment]
Ahh. I see what you mean by the scrollbars now. I'll update it so they overflow is hidden only on mobile devices
