### ISSUE TITLE
[TextField] - Setting the value to 0 breaks the floating label

### ISSUE THREAD

**Issue by c0b41** [mlaursen/react-md#460]
https://codepen.io/anon/pen/KvdpaG?editors=0010#0

### Version
- React - 15
- React-MD - 1.0.17

**Comment by mlaursen** [comment]
Whoops. This is because of my cheap `isEmpty` check in text fields. I think I fixed this in 1.1.x, but I'll bring it back to 1.0.18. (This might also apply to select fields)
