### ISSUE TITLE
[SelectField] - errorText not rendered when not focus

### ISSUE THREAD

**Issue by hisapy** [mlaursen/react-md#463]
Given a SelectField, when you assign an error & errorText to it, then the errorText should be rendered without having to focus on the SelectField

Current behavior without focus

![screen shot 2017-07-28 at 3 51 15 pm](https://user-images.githubusercontent.com/836133/28733987-ae28f480-73ac-11e7-9ee0-f90b2d8d57a7.png)

Current behavior with focus (the errorText should be rendered even without focus, just like other components)

![screen shot 2017-07-28 at 3 52 18 pm](https://user-images.githubusercontent.com/836133/28734000-c58dda5a-73ac-11e7-81cc-228a86921749.png)

**react-md version**: 1.1.0-alpha-8
**react version**: ^15.6.1
**browsers**: Google Chrome and Safari on MacOS Sierra

Thanks in advance,

Hisa

**Comment by hisapy** [comment]
I noticed that this is happening while helpOnFocus is true. So I believe the errorText is affected by the helpText behavior.

**Comment by mlaursen** [comment]
You are correct, I fixed the behavior so that `helpOnFocus` only hides the `helpText`.
