### ISSUE TITLE
[Expansion Panels] - w disabled footer / btns

### ISSUE THREAD

**Issue by mim-Armand** [mlaursen/react-md#464]
### Description
Currently there is no way to disable / remove the `DialogFooter` and the `Cancel` and `Save` buttons from the `ExpansionPanel` which limits its use-cases pretty much to dialog kind of panels, meanwhile this component could be a lot more useful in other scenarios if there were a way to disable or customize the footer section.

Thx, :+1:

### Version
- React - latest
- React-MD - latest
- Browser  All

**Comment by c0b41** [comment]
@mim-Armand already support see [v1.1.0-alpha-8](https://github.com/mlaursen/react-md/releases/tag/v1.1.0-alpha-8) wait for next minor release

**Comment by mim-Armand** [comment]
Awesome! That's great, Thank you Ayhan. :+1:
