### ISSUE TITLE
[Dialog] - React warns on accessing props.key

### ISSUE THREAD

**Issue by jackielii** [mlaursen/react-md#465]
### Description
React warns when on accessing props.key: https://fb.me/react-special-props
### Images/Screenshots

      Warning: ButtonTooltipedInked: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

### Link to a gist or code sample where the issue can be reproduced
https://github.com/mlaursen/react-md/blob/master/src/js/Dialogs/DialogFooter.js#L55

### Version
- React -    "react": "^15.6.1",
- React-MD -    "react-md": "^1.0.16",
- Browser

**Comment by mlaursen** [comment]
Thanks for the initial write-up. I ended up fixing the `cloneElement` part so that it accesses the already existing `key` (which is located on `component.key` instead of `component.props.key`). It _should_ only inject the index key if you did not provide a `key` to the action yourself.

**Comment by jackielii** [comment]
Thanks, that make sense.
