### ISSUE TITLE
[Autocomplete] onAutocomplete fires twice when using keyboard

### ISSUE THREAD

**Issue by viggyfresh** [mlaursen/react-md#466]
### Description
Clicking on an autocomplete suggestion fires the onAutocomplete event once, but using the enter key fires the event twice!

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/XaKRqP?editors=1111

### My analysis

It looks like this sequence of code in `Autocomplete.js`, lines 636-637, might be the culprit:

```
// Need to emulate the click event since the default enter/space don't work for some reason
e.target.click();
this._handleItemClick(this.state.matchIndex);
```

I shoved a `console.log` in between the two, and hey presto - the double firing of the callback is interrupted by the log. Not sure how best to handle this, please do let me know if I'm just doing something wrong!

### Version
- React - 15.6.1
- React-MD - 1.0.17
- Browser: Chrome 59.0.3071.115

**Comment by mlaursen** [comment]
You're right. That might have been some weird legacy thing? I removed the `e.target.click()` and everything is working as expected in Safari, Firefox, IE/Edge, and Chrome.

I'll patch it into 1.0.18

**Comment by viggyfresh** [comment]
Thanks a bunch for the insanely quick response! Will await 1.0.18.
