### ISSUE TITLE
1.0.18 1.0.17 1.0.16 Selection Control will wrong style 

### ISSUE THREAD

**Issue by Wolke** [mlaursen/react-md#469]
### Version
- React -
- React-MD -
- Browser

**Comment by mlaursen** [comment]
This is very vague. Can you provide any other information or screenshots to help me figure out what you mean? In 1.0.16, the `SelectionControl` was rewritten a bit for double click events being triggered, so if there were any custom styles applied before it might be a bit off.

See #390 for some more info
