### ISSUE TITLE
Missing documentation (complete examples) to customize components using themes

### ISSUE THREAD

**Issue by shrupa** [mlaursen/react-md#470]
I am using themes in my project using-

@import '~react-md/src/scss/react-md';

$md-light-theme: false;
$md-primary-color: $md-light-blue-500;
$md-secondary-color: $md-deep-orange-a-200;

@include react-md-everything;

Now, I want to override the text color in tabs to white from the default black. Please advise.

**Comment by mlaursen** [comment]
So I don't think there is anything built into the theming for that right now. It might work to just apply `md-text` to your tabs container to get it working. I'd probably need to see some more code to help more.
