### ISSUE TITLE
FontIcon rendering as string instead of an icon

### ISSUE THREAD

**Issue by turnerniles** [mlaursen/react-md#483]
Hi, I am trying to use the FontIcon component from react-md v1.0.18 but it's rendering as a string instead of an icon. When I use a Button component it renders as expected (but icon button renders the string instead of the icon). And when I do a [codepen](https://codepen.io/turnerniles/pen/ayLRXg) it works but not in my local project. Am I including the css wrong?

![image](https://user-images.githubusercontent.com/8146241/29299471-d1e8cde4-813c-11e7-8fc5-750c4aeee1c6.png)

Abbreviated code...

**JS:**
```
import FontIcon from 'react-md/lib/FontIcons';

render() {
<div>
<FontIcon>home</FontIcon>
</div>
}
```

**SCSS:**
```
@import '~react-md/src/scss/react-md';

$md-primary-color: $md-teal-500;
$md-secondary-color: $md-lime-a-400;
$md-font-icon-size: 20px;
.md-icon.fa { height: $md-font-icon-size; width: $md-font-icon-size; }

@include react-md-everything;
```

**Comment by c0b41** [comment]
@turnerniles add this 

```html 
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

**Comment by turnerniles** [comment]
@c0b41 thank you!!
