### ISSUE TITLE
[DatePicker/TimePicker] - InlineIndicator expected boolean

### ISSUE THREAD

**Issue by johan-lejdung** [mlaursen/react-md#490]
### Description
When sending in an object in the `inlineIndicator` prop for component `TimepickerContainer` I get an error. The compiled code works as expected though but the error persists. 

### The Error
Warning: Failed prop type: Invalid prop `inlineIndicator` of type `object` supplied to `TimePickerContainer`, expected `boolean`.
    in TimePickerContainer (created by XXXX)

### Link to a gist or code sample where the issue can be reproduced
```
<TimePicker
        id="id"
        label="Time"
        value={date}
        onChange={onTimeChange}
        icon={null}
        inlineIndicator={indicatorElems}
        error={hasWarning}
      />
```
Where indicatorElems is a `<div>{Components}</div>`

### Version
- React - 15.4.2
- React-MD - 1.0.18

**Comment by mlaursen** [comment]
Looks like this was a copy/paste fail. I'll update both this and the date picker since it has the same problem.
