### ISSUE TITLE
[Switch] - Support icon

### ISSUE THREAD

**Issue by mctep** [mlaursen/react-md#496]
Hi! :)

Is support for `Switch` icon in plans?

Google Inbox example:

![image](https://user-images.githubusercontent.com/1949681/29625312-fcf80a24-8833-11e7-817b-c3fb5fba2924.png)

![image](https://user-images.githubusercontent.com/1949681/29657329-e5dbe504-88bf-11e7-9dcd-d84233160cb3.png)

**Comment by mlaursen** [comment]
I hadn't thought about it, but my first attempt to recreate took about 2 min. So making it configurable shouldn't be bad -- I'll add it 1.2.0
