### ISSUE TITLE
[Ink] - Inks duplicates after window focus in Safari

### ISSUE THREAD

**Issue by mctep** [mlaursen/react-md#498]
### Description

Reproduce (only for Safari):

- Focus on some element
- Go to other browser tab
- Return back
- Press `Tab` to change focused element

Result:

Old `Ink` stays on the last focused element. So it possible to clone `Inks` :)

### Images/Screenshots
![image](https://user-images.githubusercontent.com/1949681/29664024-8e7a5252-88d6-11e7-9003-b5461b52c3fa.png)

### Link to a gist or code sample where the issue can be reproduced
https://react-md.mlaursen.com/

### Version
- Browser Safari Version 10.1.2 (12603.3.8)

**Comment by mlaursen** [comment]
Well... That's interesting. I guess Safari doesn't trigger the blur event and focus when browser tabs change. Might be a "bug" with Snackbars not restarting their timeouts when the browser loses focus. Not entirely sure though..

**Comment by GerardStelt** [comment]
I have the same issue with Safari with tabs using mouse.

- Mouse-select certain tab
- Navigate to other browser tag
- Return back
- Mouse-select different tab

Same result: Ink stays 'on' on previous tab
