### ISSUE TITLE
[TablePagination] - Current Page is not being correctly updated unless it is controlled

### ISSUE THREAD

**Issue by benhunt29** [mlaursen/react-md#500]
In a table where I'm not manually updating the "page" attribute, there seems to be a bug when the user is on a page other than page 1 and selects a rowsPerPage value greater than the total number of items. The displayed "start" number doesn't go back to 1 but goes to rowsPerPage + 1. The actual value of "start" passed to onPagination seems to be correct, though. See the images below.

Step 1
<img width="390" alt="screen shot 2017-08-24 at 12 18 54 pm" src="https://user-images.githubusercontent.com/6341431/29679203-c7e78c0e-88c6-11e7-9a61-ce85a9ffe4ef.png">
Step 2 - Click right arrow
<img width="394" alt="screen shot 2017-08-24 at 12 19 02 pm" src="https://user-images.githubusercontent.com/6341431/29679210-ca1422ee-88c6-11e7-91e4-a987a125838e.png">
Step 3 - Change rows per page to a number greater than total rows
<img width="395" alt="screen shot 2017-08-24 at 12 19 13 pm" src="https://user-images.githubusercontent.com/6341431/29679215-cc5f5168-88c6-11e7-87c0-2bfeb4214803.png">

For some reason, simply using the currentPage value given to onPagination to manually update the "page" attribute fixes the problem but it's annoying to have to do. 

For clarification here are code snippets with/without the bug:

With the bug:
```jsx
<TablePagination onPagination={this.handlePagination} rowsPerPage={rowsPerPage} rows={numRows} />

handlePagination (start, rowsPerPage, currentPage) {
      this.setState({
        rows: this.props.rows.slice(start, start + rowsPerPage),
        rowsPerPage: rowsPerPage
      })
  }
```

Without the bug:
```jsx
<TablePagination onPagination={this.handlePagination} page={currentPage} rowsPerPage={rowsPerPage} rows={numRows} />

handlePagination (start, rowsPerPage, currentPage) {
      this.setState({
        rows: this.props.rows.slice(start, start + rowsPerPage),
        rowsPerPage: rowsPerPage,
        currentPage: currentPage
      })
  }
```

**Comment by mlaursen** [comment]
I can't seem to reproduce it in 1.1.0+, so I think this has been fixed?
