### ISSUE TITLE
[TextField] - Implement Currency Type

### ISSUE THREAD

**Issue by Kibble** [mlaursen/react-md#501]
### Description
It would be nice to have a "currency" option available for the TextField's "type" prop in react-md.

#### Features:
- Implemented as a "number" type such that the numeric keypad is used on mobile devices
- Add an optional "prefix" prop (typically "$" for a U.S. use case)
- Add an optional "suffix" prop ("USD", "GBP", etc)
- Inserts formatting commas as the user types (1,234,567.89)
  - Shifts formatting commas as the user edits the middle of the number

#### Optional Features:
- Format the field according to the browser locale
- Add an optional "locale" prop that will override browser locale
- Format the input to 2 (depending on locale) decimal places as part of the "onBlur" event
- Limit input characters depending on locale

**Comment by mlaursen** [comment]
Going to close this one for now. Using the `useTextField`/`useNumberField` hooks in v2, this should mostly be covered now. Text field masking isn't in scope for this project right now, so displaying: `$1000.00` instead of `1000.00` isn't really possible.
