### ISSUE TITLE
TypeScript: DrawerTypes.TEMPORARY

### ISSUE THREAD

**Issue by noseglid** [mlaursen/react-md#512]
TypeScript definition does not correctly convey that `Drawer.DrawerTypes.TEMPORARY` exists:

```
error TS2339: Property 'TEMPORARY' does not exist on type 'DrawerTypes'.
  Property 'TEMPORARY' does not exist on type '{ FULL_HEIGHT: "full-height"; CLIPPED: "clipped"; FLOATING: "floating"; PERSISTENT: "persistent";...'.
```

**Comment by noseglid** [comment]
I think the `DrawerComponent` should really take `DrawerTypesType` rather than `DrawerTypes` in its definition.

**Comment by mlaursen** [comment]
I ended up doing this: d8247db and it seemed to work correctly when running the `with-typescript` example of react-md. Any better suggestions?

**Comment by noseglid** [comment]
I don't think this is the full solution.

From my understanding, I think what you've done there is to just declare that
> anything that implements e.g. the `AutocompleteComponent` interface, will have an object `Positions`, where the key `TOP_LEFT` will be `tl`
This is correct (e.g. `Autocomplete` has a `Positions` fields which holds all the layover position.

But the component doesn't expect an object as an argument, it expects a string.

So the type the component should accept should look something like this

```ts
export type PositionsType = 'tl' | 'tr' | 'bl' | 'br' | 'below';
```

which means "one of these strings".


Because as it is now
```ts
export type LayoverPositions =  {
  TOP_LEFT: 'tl',
  TOP_RIGHT: 'tr',
  BOTTOM_LEFT: 'bl',
  BOTTOM_RIGHT: 'br',
  BELOW: 'below'
}
```

means I must pass an object (which is that exact structure).

This doesn't work:
![screen shot 2017-09-12 at 09 37 38](https://user-images.githubusercontent.com/933880/30313576-1629975a-979e-11e7-9ff5-6e05810a9e1e.png)

But this does:
![screen shot 2017-09-12 at 09 38 50](https://user-images.githubusercontent.com/933880/30313618-36244c6c-979e-11e7-87ef-1d7a00de311c.png)

But obviously the PropTypes validation will reject this object, so it doesn't *really* work.

**Comment by mlaursen** [comment]
Ohh OK. I misunderstood the `type Name = { ...keys... }` declaration. Your examples clear it up. I'll try adding ol what you've suggested, thanks!

**Comment by noseglid** [comment]
Cool!

I was just thinking about creating a PR for this, unless you want to do it yourself?

**Comment by mlaursen** [comment]
I think I would prefer a PR if you have the time. It'll be more of a
learning process instead of a bugfix if I implement it.

I'll probably be able to understand and learn from a PR quicker
