### ISSUE TITLE
[Documentation] - Dialogs code in documentation suggest using Dialog component instead of DialogContainer

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#515]
In 1.1.x library version dialog component should be DialogContainer instead of Dialog, but in code examples in https://react-md.mlaursen.com/components/dialogs there are imported as ```import Dialog from 'react-md/lib/Dialogs';```

I think it is confused, because it suggest that we import Dialog component instead of DialodContainer.

**Comment by mlaursen** [comment]
That makes sense. I'll update all the references to be `DialogContainer` instead since it is the default export.
