### ISSUE TITLE
[Layover] - Upgrading to 1.1.1 throws error regarding toggle component

### ISSUE THREAD

**Issue by Ardhimas** [mlaursen/react-md#518]
### Description

Upgrading to 1.1.1 renders the error ```Unable to find a toggle component with the provided `toggleQuery` and `toggle` element. ```

I'm not able to reproduce it outside my code base because I actually have no clue what component is causing the issue, but it's an app-breaking one.

If anyone has any ideas at all as to what components could be causing this I'd be able to debug it better. My workaround for now is to downgrade back to 1.0.19, where there doesn't appear to be any issues. Thanks!

### Images/Screenshots
![image](https://user-images.githubusercontent.com/5238654/30293548-95c06f9c-96ff-11e7-9385-54c3c986e1b2.png)
![image](https://user-images.githubusercontent.com/5238654/30293592-b875a17e-96ff-11e7-89b5-45b3800aec28.png)

- React - 15.6.1
- React-MD - 1.1.1

**Comment by mlaursen** [comment]
This error ends up happening if you created a custom `Menu` component without having valid child element as a click target. I wasn't sure how to get a better warning message about a related component for this or some more context. When using the `Menu`, you need to make sure that the `toggle` prop is a `button`, `.md-text-field-container`, `*[role="button"]` or `*[role="listbox"]`.

For example if you created a custom menu component like this:

```
    const toggle = [
      <Avatar key="avatar" className="account-options-avatar">{firstLetter}</Avatar>,
      <IconSeparator label={username} key="username">
        <SVGIcon icon={SVGIcon.Icons.MENU_ARROW_DOWN} />
      </IconSeparator>,
    ];

    return (
      <Menu
        id="account-options-menu"
        isOpen={visible}
        onClose={this.close}
        toggle={toggle}
        position={Menu.Positions.BELOW}
        component={AccessibleFakeButton}
        onClick={this.toggle}
      >
        {..list items..}
      </Menu>
  );
```

You could fix it by either making the toggle component:
```
const toggle = (
  <AccessibleFakeButton>
    <Avatar key="avatar" className="account-options-avatar">{firstLetter}</Avatar>
    <IconSeparator label={username} key="username">
      <SVGIcon icon={SVGIcon.Icons.MENU_ARROW_DOWN} />
    </IconSeparator>
  </AccessibleFakeButton>
);
```

or cheating and update the `IconSeparator` to have `role="button"`

**Comment by Ardhimas** [comment]
Thank you very much for the speedy response, I'll report back on my findings once I attempt to implement the solution.

**Comment by Ardhimas** [comment]
This issue is fixed, but I ran into a separate issue while fixing this that I'll document in another post.
