### ISSUE TITLE
[FontIcon] - Unknown prop `primary` on <i> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by luisrudge** [mlaursen/react-md#525]
### Description

Can't assign colors to font icons

### Images/Screenshots

![image](https://user-images.githubusercontent.com/941075/30429333-7576cc9c-992d-11e7-8395-8853f1a80be8.png)

### Link to a gist or code sample where the issue can be reproduced

```js
<FontIcon primary>
  people
</FontIcon>
```

### Version
- React - 15.6.1
- React-MD - 1.1.2

**Comment by mlaursen** [comment]
This is a feature only available in 1.1.0+, if you are still on 1.0.* this error will appear.
