### ISSUE TITLE
[SelectFields] - fullWidth doesn't work in Select Fields

### ISSUE THREAD

**Issue by asanzdj** [mlaursen/react-md#533]
The prop fullWidth does nothing in the Select Field Component.

**Comment by mlaursen** [comment]
Could you give an example? If you are manually setting the width of the `SelectField` with a `.md-cell` or other styles, it will appear to do nothing.

This [codepen](https://codepen.io/mlaursen03/pen/EwPgYr) shows the differences of just basic `fullWidth={false}` and `fullWidth={true}`

**Comment by asanzdj** [comment]
When I read about fullWidth prop I thinked about this: https://codepen.io/anon/pen/KXVxRx?editors=0110

**Comment by mlaursen** [comment]
Oh ok. That is probably my documentation mistake. I'll update the documentation to give a bit more detail and link them together. To get the desired affect, you should also apply `sameWidth`.

https://codepen.io/mlaursen03/pen/RLrzWE

**Comment by asanzdj** [comment]
Ok, I will use it.
