### ISSUE TITLE
[BottomNavigation] - The Bottom Navigation should switch to scroll events instead of touch events

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#537]
After updating the documentation website to use the bottom navigation on mobile instead of large toolbars, I've noticed how annoying and bad the implementation is for the dynamic navigation since it also registers left/right touches for distances. This should really be updated to work on window scroll, or any element's scroll if it is in a full page dialog or something.

### Version
- React-MD - All

**Comment by mlaursen** [comment]
This hiding functionality will be a new hook within v2 to help with this pattern.

**Comment by davidorion55555** [comment]
I have a question.
Why does component in route of NavigationDrawer condtruct twice?
