### ISSUE TITLE
How to open select field using click of a button

### ISSUE THREAD

**Issue by sachiner** [mlaursen/react-md#544]
How to open select field using click of a button

**Comment by mlaursen** [comment]
You can fully control the visibility by using:
 - [visible](https://react-md.mlaursen.com/components/select-fields?tab=1#select-field-proptypes-visible)
 - [onVisibilityChange](https://react-md.mlaursen.com/components/select-fields?tab=1#select-field-proptypes-on-visibility-change)

**Comment by sachiner** [comment]
visible is not working after once if given a value 
lam using like this 
this.visible_dropdown = true
<SelectField
                visible={this.visible_dropdown1}
                id="selectButtonNumbers"
                fullWidth={true}
                placeholder="xxxxxx"
                position={SelectField.Positions.BELOW}
                onChange={(newValue, newActiveIndex, event)=>{
                  this.visible_dropdown1 = false;
                  this.submitDropDown(newValue, newActiveIndex)}}
                menuItems={this.collectionAmountOptions}/>

**Comment by mlaursen** [comment]
Here is a working example:
https://codepen.io/mlaursen03/pen/RLKgGp

**Comment by sachiner** [comment]
Thanks @mlaursen
