### ISSUE TITLE
[DataTable] - Built-in Checkbox displays incorrectly in wide tables with little content

### ISSUE THREAD

**Issue by asanzdj** [mlaursen/react-md#549]
There is a problem with the position of multiselect icon in data tables. (.md-selection-control-container)

Here is an example of my problem:
https://codepen.io/anon/pen/KXWbdE?editors=0110

**Comment by c0b41** [comment]
Yeah same problem, quick monkey patch
```
.md-table-checkbox .md-selection-control-label{
  display:block !important;
}
```

**Comment by mlaursen** [comment]
I can patch something in for this, but I _personally_ think tables look better if you use the existing styling props to solve this issue.

https://codepen.io/mlaursen03/pen/XeMwOY?editors=0110

I'll probably do the `display: block` suggestion.
