### ISSUE TITLE
[DataTable] - Sorting while Selecting returns incorrect Row index when using onRowToggle or onCheckboxClicked

### ISSUE THREAD

**Issue by jbetancur** [mlaursen/react-md#554]
If I select a Row and then sort, then the select checkbox should sort with the row and update its index. However, the check box indexes or rows remain static [1,2,3,4,5...], so when I grab the index from onRowToggle it matches the wrong item.

## Codepen
https://codepen.io/johnnyazee/pen/MEomxp?editors=0110

### Version
- React - 15.6.2
- React-MD - 1.1.5

![sep-28-2017 19-23-57](https://user-images.githubusercontent.com/1385932/30994611-e6a62aec-a482-11e7-8776-c1ec58d41d82.gif)

**Comment by lepirlouit** [comment]
The same bug occurs with pagination.

**Comment by mlaursen** [comment]
Sadly these will take awhile to fix. I'll need to update the `DataTable` to use unique keys for each row instead of just array index order. I do need to redo most of the `DataTable` anyways to make it simpler.
