### ISSUE TITLE
[TimePicker] Displayed time not updating when value changes

### ISSUE THREAD

**Issue by ppetru** [mlaursen/react-md#559]
### Version
- React - 15.16.2
- React-MD - 1.1.5

I have a patch that fixes this, although I'm not sure that it's the right solution. I'm new to React and React-MD, so I'm not 100% sure what I'm doing :)

Also: I noticed that TimePickerContainer calls setState() in componentWillUpdate(), which is not allowed according to https://facebook.github.io/react/docs/react-component.html#componentwillupdate. However, removing those makes the TimePicker no longer allow picking times, so perhaps there's more going on that I don't understand...

**Comment by mlaursen** [comment]
Hmm. I don't recall that message in the docs about `componentWillUpdate` and I've done it in a couple of places. I should probably fix it at some point to do it at `componentWillReceiveProps` and right before the `setState` that would have caused the update as well..
