### ISSUE TITLE
[Large Edit Dialog Column] Disable the save button

### ISSUE THREAD

**Issue by tomasescamez** [mlaursen/react-md#568]
I'm creating some validations on the large edit dialog column and I'd like to disable the save button when there is an error

**Comment by mlaursen** [comment]
This one should be possible after the 1.1.7 release and commit: 124272b

[This](https://github.com/mlaursen/react-md/commit/124272b0d02eb38181080e006b8ba2185796f87b#diff-24a944d7424cbacadcaa29426c341e23R67) should be a good example of usage.
