### ISSUE TITLE
[Slider] - Support Vertical Sliders

### ISSUE THREAD

**Issue by kladdad** [mlaursen/react-md#569]
### Description

When I tried to rotate the slider (using `transform` as shown in the codepen below), the slider shows vertically. However, grabbing and moving the thumb vertically doesn't move the thumb. Instead, moving it horizontally moves the slider (as if the effect of `transform` isn't applied to it).

### Codepen snippet that shows the problem

https://codepen.io/anon/pen/wrpBOJ

### Version
- React - 15.x
- React-MD - latest

**Comment by mlaursen** [comment]
I'll change this to be a feature request for vertical sliders. I'll need to update the code to handle up/down movements instead of only left/right
