### ISSUE TITLE
[Slider] Unnecessary warning for negative/positive min/max

### ISSUE THREAD

**Issue by kladdad** [mlaursen/react-md#570]
### Description

There is a warning emitted if min and max aren't of the same sign. However, if I ignore the warning, all seems to work fine. 

```
Warning: Failed prop type: The 'Slider' is unable to have a range spanning from negative to positive. The range must either be all negative or all positive.
    in Slider (created by App)
    in App
```

Is this warning no longer needed?

### Codepen to reproduce the issue

https://codepen.io/anon/pen/qPpYmM

### Version
- React - 15.x
- React-MD -latest

**Comment by mlaursen** [comment]
Interesting, I thought my logic broke when that happens. I'll remove that warning.
