### ISSUE TITLE
[Slider] Thumb doesn't shrink back to the original size upon letting it go

### ISSUE THREAD

**Issue by kladdad** [mlaursen/react-md#571]
### Description

After moving slider thumb and letting the mouse go, the thumb circle remains big. One needs to click away somewhere else to restore the thumb's size.

Similarly, for discrete slider, the value bubble remains there even after the mouse is let go.

This can be seen in the codepen below as well as example on the documentation page: https://react-md.mlaursen.com/components/sliders

### Codepen sample

https://codepen.io/anon/pen/ZXvRem

### Version
- React - 15.x
- React-MD - latest

**Comment by williegroovy** [comment]
Just poking through the slider component, it seems like the active state is being toggled to false, if you click elsewhere to remove focus off the slider. I also noticed that the "maskedInk" state is not being toggled true when dragging starts and false when it ends. I think it might be nice to set both slices of state when dragging starts, and possibly when the user clicks on a location. As it moves it gains focus so the slider thumb grows, but it just never shrinks on completion. 

https://material.io/guidelines/components/sliders.html#

@mlaursen If that sounds like something you'd entertain for a pull-request, let me know. I'd be happy to help out with that.

**Comment by mlaursen** [comment]
@williegroovy I will happily accept a PR if you have the time!

**Comment by williegroovy** [comment]
After exploring this a little more, it appears to me that the slider is behaving as it should. Currently, when you select a sliders "thumb" it gains focus, then allows the user to use their arrow keys to change the value. Another important aspect to point out is using tab to or shift+tab to navigate through a grouping of sliders.

What if we called setState({ active: false, maskedInk: false }); in the _handleDragEnd()

To me that feels like the functionality that @kladdad wanted without compromising the users ability to make adjustments with the arrow keys.

You can still tab through everything, but if you choose to drag the thumb, when the drag ends, the thumb shrinks.
