### ISSUE TITLE
[Tooltips] - Display incorrectly in IE11

### ISSUE THREAD

**Issue by daturon** [mlaursen/react-md#574]
Hello!
When I try to call the tooltip, I see the following:

![img-2017-10-06-07-39-31](https://user-images.githubusercontent.com/3388477/31263297-ffc2d5c4-aa69-11e7-95ce-8e6fd955b7bb.png)

![img-2017-10-06-07-40-04](https://user-images.githubusercontent.com/3388477/31263305-0aeafdb4-aa6a-11e7-998f-999b3c62a048.png)

![img-2017-10-06-07-41-27](https://user-images.githubusercontent.com/3388477/31263306-0f4e309c-aa6a-11e7-93a4-ae6f0e96f012.png)

Any idea how I can fix this?

IE 11

**Comment by mlaursen** [comment]
It looks like I need to update the styles a bit for this..

To fix the buttons, I'll need to add `overflow: visible` so the tooltips appear outside of the button.

To fix the other ones, I'll need to update the tooltip to be `display: block; height: auto; padding: $some-variable-padding;`.
