### ISSUE TITLE
[EditDialogColumn - okProps/cancelProps] The props are applied inversely

### ISSUE THREAD

**Issue by tomasescamez** [mlaursen/react-md#581]
In the EditDialogColumn, the okProps are applied to the cancel button and the cancelProps are applied to the ok button.

I'm using react-md 1.1.8

![reactmd-issue](https://user-images.githubusercontent.com/5651379/31360021-ec7dbcd0-ada8-11e7-8f54-7b4fc3b374fe.png)

**Comment by mlaursen** [comment]
Whoops. Yeah, looks like I can't read. I'll do a small patch with this.
