### ISSUE TITLE
[Date Picker] Displaying the popup always in the first tab

### ISSUE THREAD

**Issue by tomasescamez** [mlaursen/react-md#583]
Added a date picker on the second tab and the popup is displaying on the first tab

react-md v. 1.18
browser: chrome

**Comment by c0b41** [comment]
https://github.com/mlaursen/react-md/issues/551#issuecomment-332653789

**Comment by tomasescamez** [comment]
Oh, fixed! Thanks @c0b41

**Comment by mlaursen** [comment]
Closing this one in favor of #551. I'll update it with some more information as well.
