### ISSUE TITLE
[ListItem] - Breaks on IE 10

### ISSUE THREAD

**Issue by JCofman** [mlaursen/react-md#584]
### Description
Hi everyone I have an issue with IE 10 and the ListItem component. When I try to render data inside the Autocomplete component I get the following error message:

```
Unable to get property 'initiallyOpen' of undefined or null reference 
```
This error occurs only in IE 10 and only with the ListItem Component. When I try to render other Components like the CircularProgress or any other elements it works fine. I think it has something to do with the following caveats of Babel -> https://babeljs.io/docs/usage/caveats/ but I was not able to resolve it. 

### Version
- React - 16.0.0
- React-MD - 1.1.9
- Browser - IE 10

**Comment by mlaursen** [comment]
Would you be able to provide a stack trace to get some more context? I am not entirely sure if I will tackle this though since I'm really supporting IE11+ right now :/

**Comment by Ixl123** [comment]
hi @mlaursen thank you for your answer and sorry for my late response. I actually don't get a big stack trace. The only thing i get is the following message `SCRIPT5007: Unable to get property 'initiallyOpen' of undefined or null reference 
bundle.js, line 44204 character 11` and it refers to this part of the code:

``` javascript
var ListItem = function (_PureComponent) {
  inherits(ListItem, _PureComponent);

  function ListItem(props) {
    classCallCheck(this, ListItem);

    var _this = possibleConstructorReturn(this, (ListItem.__proto__ || Object.getPrototypeOf(ListItem)).call(this, props));

    _initialiseProps$1.call(_this);

    _this.state = { active: false };

    if (typeof props.isOpen === 'undefined' && typeof props.visible === 'undefined') {
      var defined = function defined(v) {
        return typeof v !== 'undefined';
      };
      var _this$props = _this.props,
          initiallyOpen = _this$props.initiallyOpen,
          defaultOpen = _this$props.defaultOpen,
          defaultVisible = _this$props.defaultVisible;

      var visible = defined(initiallyOpen) ? initiallyOpen : defaultVisible;
      visible = defined(defaultOpen) ? defaultOpen : visible;
      visible = !!visible;

      _this.state.visible = visible;
    }
    return _this;
  }
```
