### ISSUE TITLE
[Slider] step behavior wrong in cases where min not zero

### ISSUE THREAD

**Issue by strickc** [mlaursen/react-md#585]
### Description
When using a slider with a step defined the increments are miscalculated and do not match the value provided by step.
### Images/Screenshots
![Image of Slider Error](https://i.imgur.com/H0wNuK6.png)
The incorrect bottom slider cannot be set to 2.5 or 2.75, despite those being evenly divisible by the 0.25 step starting at 0.5.
### Link to a gist or code sample where the issue can be reproduced
Issue is displayed on the forked codepen template:
[https://codepen.io/strickc/pen/VMdOLX](https://codepen.io/strickc/pen/VMdOLX)

### Version
- React - 15
- React-MD - 1.2
- Browser - Chrome v61

I'd be interested in providing a fix for this bug if a pull request is welcome.

**Edited** to correct my confusion between the step and discreteTicks properties.

**Comment by mlaursen** [comment]
PRs are always welcome if the contributing guidelines are followed!

- [Contributing 1](README.md#contributing)
- [Contributing 2][docs/README.md#contributing) 
- [Contributing 3](https://react-md.mlaursen.com/discover-more/contributing) 

I have been meaning to consolidate them..
