### ISSUE TITLE
[NavigationDrawer] - extractMini has no effect

### ISSUE THREAD

**Issue by p12y** [mlaursen/react-md#586]
If extractMini is true (which it is by default), it should extract the icons from the list items in a navigation drawer, but it's not. Instead the full list item is being rendered inside the mini drawer.

At first I thought the icons were just off-center:
![screen shot 2017-10-12 at 16 52 03](https://user-images.githubusercontent.com/14144032/31505894-d433b7b2-af6d-11e7-954e-0ed263da2b61.png)

However, if you increase the width of the drawer with the inspector tool, you can see that it's rendering the full list items instead of miniListItems.
![screen shot 2017-10-12 at 16 52 41](https://user-images.githubusercontent.com/14144032/31506029-3a2149ae-af6e-11e7-873b-829d1aea48d2.png)

EDIT:

I've also just realised that if you set extractMini to false, the list items don't render at all.

Version:
- React - 16.0.0
- React-MD - 1.2.0 - 1.2.2 (Haven't tried any older versions)

**Comment by mlaursen** [comment]
This seems to be working as expected with 1.3+ now. Live example: https://codepen.io/mlaursen03/pen/vjzjEo?editors=0110

Not sure when I fixed it though. Going to close for now.
