### ISSUE TITLE
List component keeps expanded/visible state by row # instead of row key

### ISSUE THREAD

**Issue by vtr** [mlaursen/react-md#597]
### Description

If I have the following, using react-md components:
```
<List>
  <ListItem>A</ListItem>
  <ListItem>B</ListItem>
  <ListItem>C</ListItem>
  <ListItem>D</ListItem>
  <ListItem>E</ListItem>
</List>
```

Each ListItem component has a delete button that deletes the item from the underlying state array. Each ListItem component is expandable.

Issue 1:
When clicking the delete button for item B, B is deleted from the list, but C is expanded.
My guess is that the click event on the delete button is propagated to row 1 (for item B), which trigger a re-render of the list with row 1 expanded, so now the ListItem C (data array is now [A, C, D, E]) gets expanded.

I managed to somehow workaround this by having the following on the onRemove function for when user clicks the delete button:

        e.preventDefault();
        e.stopPropagation();
        e.nativeEvent.stopImmediatePropagation();

However, this bring us to:

Issue 2:
Expand item C. This means row 2 in the list is expanded. Delete item B. Because an item was deleted, the List component triggers a re-render. When the list re-renders, will make sure row 2 remains expanded, but row 2 now contains ListItem D and not C.

I think both of these issues could be solved by propagating the expansion status via children key instead of index. Thoughts?

### Version
    "react": "^15.6.1",
    "react-md": "^1.2.3",

**Comment by mlaursen** [comment]
I think this has to deal more with using array index as keys instead of unique ids for each list item. If you check out [this codepen](https://codepen.io/mlaursen03/pen/aLMEVL?editors=0110#0) you can see the differences between using unique keys and just array index keys. It works as expected when using unique keys, but fails when using array index keys.

**Comment by vtr** [comment]
Indeed, thanks for taking a look. I hadn't thought of that because I'm generally using the object id as the key, but in this case, the code was still relying on array index.

**Comment by mlaursen** [comment]
Going to close this since I think it was resolved.
