### ISSUE TITLE
[TablePagination] - Does not position correctly after prop updates

### ISSUE THREAD

**Issue by johan-lejdung** [mlaursen/react-md#600]
### Description
I just saw an issue with how TablePagination is rendered. The size of the component is decided only on certain events, not on prop changes. This causes the component to potentially overlap other stuff when the props change. 
I have located that the issue is with the `_position()` function which only runs on `onResize`. I would like to propose that it also runs whenever any props changes.
 
The problem in the image was that the function `_position()` ran when we were on the first page. After stepping forward the content changed but it never resized.

### Images/Screenshots
![screen shot 2017-09-26 at 11 22 34](https://user-images.githubusercontent.com/9266884/31984922-7ea3d0e8-b963-11e7-9486-b4d094698098.png)

### Version
- React - 16.0.0
- React-MD - 1.2.4

**Comment by Ardhimas** [comment]
@johan-lejdung An easy hotfix for now is to add `style={{ display: 'block' }}` to the `TablePagination` component, which for some reason causes the reposition to occur.

**Comment by johan-lejdung** [comment]
Thanks! Great to know :)

**Comment by johan-lejdung** [comment]
Can confirm that @Ardhimas fix did not work in my project!
