### ISSUE TITLE
[Tabs] - this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by jccrofty30** [mlaursen/react-md#603]
### Description
Receive error below when calling `this.setState()`. I apologize if this is emitting from another package...but from everything I can tell it's dying inside `react-md`.

### Images/Screenshots
![image](https://user-images.githubusercontent.com/12339530/32184527-dcf448e0-bd72-11e7-8940-bbb32f5b5813.png)

### Version _(excuse the messy editing)_
- React:
    ![image](https://user-images.githubusercontent.com/12339530/32184959-46c38c6c-bd74-11e7-8d6a-1c3cb70f1315.png)
- React-MD:
    ![image](https://user-images.githubusercontent.com/12339530/32184908-2a85d028-bd74-11e7-84c2-4aa5e45ca86c.png)
- React-DOM _(for posterity)_:
    ![image](https://user-images.githubusercontent.com/12339530/32184875-0c30d988-bd74-11e7-91b6-3f55545bc032.png)

**Comment by mlaursen** [comment]
Would you be able to provide any additional code or a reproducible example? I haven't encountered it yet, so some additional context would be helpful in debugging!

**Comment by jccrofty30** [comment]
Actually trying to narrow that down...testing on codesandbox with only `react`, `react-dom`, and `react-md`...it works.

Still trying to identify what we have that is so different to produce the error...I can confirm that is is emitting from `Tabs`.

**Comment by jccrofty30** [comment]
We've resolved the issue. Completely on our end.

We've got a rather _'unique'_ situation that has us crossing projects and the `react` versions were colliding.

Apologies for the bother.
