### ISSUE TITLE
[SelectField] Width ignores subheaders, wrapped subheaders render under list items

### ISSUE THREAD

**Issue by andrewking0207** [mlaursen/react-md#607]
### Description
If I add a subheader to a select field and the primaryText is longer than the label of any list items, the width of the selectfield is only adjusted to the list item labels.  This can cause the subheader text to wrap onto the next line where it is rendered underneath the next list item.
### Images/Screenshots
![image](https://user-images.githubusercontent.com/10764235/32393631-4bc59426-c0a8-11e7-8d3c-9a3b07cd13d9.png)
### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/andrewking0207/pen/ooxxrR
### Version
- React - 16.0.0
- React-MD - 1.2.3

**Comment by mlaursen** [comment]
This can be solved pretty easily by adding
```
.md-list--menu .md-subheader {
  white-space: nowrap;
}
```

I'll test to see if there are any negative side-effects of this before adding it to the base library styles.
