### ISSUE TITLE
[ListItem] - TransitionGroup issues when doing Jest Snapshot testing

### ISSUE THREAD

**Issue by viggyfresh** [mlaursen/react-md#611]
### Description
I'm running a very basic snapshot test under Jest with the `ListItem` component (see snippet below), which throws a very unhelpful error (see below):

```
    TypeError: Cannot read property 'componentWillAppear' of null
      at TransitionGroup._this.performAppear (node_modules/react-md/node_modules/react-transition-group/TransitionGroup.js:57:20)
      at TransitionGroup.componentDidMount (node_modules/react-md/node_modules/react-transition-group/TransitionGroup.js:156:14)
...
 The above error occurred in the <TransitionGroup> component:
        in TransitionGroup (created by InkContainer)
        in InkContainer (created by withInk(AccessibleFakeButton))
        in div (created by AccessibleFakeButton)
        in AccessibleFakeButton (created by withInk(AccessibleFakeButton))
        in withInk(AccessibleFakeButton) (created by ListItem)
        in li (created by ListItem)
        in ListItem (created by FindingListItem)
        in FindingListItem
```

I wasn't able to pinpoint anything specific and haven't dug deeply into the codebase, but I found some color at [this](https://github.com/facebook/react/issues/5240) React issue (stale because they put transition group into its own package) and [this](https://github.com/callemall/material-ui/commit/38d5d3ef917893b6c21a98887c1ef085765e93ee) commit on Material-UI.

### Link to a gist or code sample where the issue can be reproduced
```Javascript
const component = renderer.create(
    <ListItem
        {...props}
    />
);
const tree = component.toJSON();
expect(tree).toMatchSnapshot();
```
### Version
- React - 16
- React-MD - 1.2.5
- Browser N/A

**Comment by mlaursen** [comment]
Looks like it was a problem with how the `react-test-renderer` builds the tree for snapshotting since it works in browsers and other renderers. Removing a `<span />` in the `TransitionGroup`'s children fixes the rendering issue.
