### ISSUE TITLE
[EditDialogColumn] - TypeError when disabling icon by setting inlineIcon to null

### ISSUE THREAD

**Issue by cayasso** [mlaursen/react-md#612]
### Description
Setting `inlineIcon={null}` is throwing a `TypeError` see bellow.

### Images/Screenshots
![image](https://user-images.githubusercontent.com/42518/32526710-6ec60906-c3f0-11e7-9022-5417ea108102.png)

### Version
- React - 16
- React-MD - 1.2.6

**Comment by mlaursen** [comment]
I accidentally did an unsafe `React.cloneElement` without checking if the icon was defined. Should be fixed now.

**Comment by cayasso** [comment]
Thank you!
