### ISSUE TITLE
[General] - Some components do not display correctly when a parent has overflow set to anything except visible

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#613]
### Description
There are some components that will not display correctly when a parent element has `overflow: hidden` set. These components usually use some type of temporary material and it does not overlap as expected.

A lot of the time, it will be related to the `Tabs` or `TabsContainer` component since it does some magic with `transform: translate3d(x, y, z)` which cause things to display weirdly. Attempting to display a `DatePicker`, a `TimePicker`, or any `DialogContainer` will have weird results since it won't calculate the current `transform`. This can be worked around by adding the `portal={true}` prop to these components. This will make the `Dialog` render outside of the container and not have to do additional calculations.

Another problem that happens is attempting to display a `Menu` in an element with `overflow: auto` (or `overflow: hidden`). There is no real fix for this one right now other than hoping that setting `simplifiedMenu={false}` will solve it. I will need to add in hooks for the `Menu` component to also be able to be portal-ed out.

### Images/Screenshots
![image](https://user-images.githubusercontent.com/3920850/32557994-f4769b72-c460-11e7-95b4-1295f15e63a0.png)

### Version
- React - *.*
- React-MD - 1.2.*

**Comment by c0b41** [comment]
@mlaursen any status? or any tips?

**Comment by mlaursen** [comment]
Not anything new yet, sorry! This isn't an issue yet for me in work since we don't use tabs and all the other cases where it might be an issue, the components can be portal-ed to fix.
