### ISSUE TITLE
[NavigationDrawer] transition doesn't work

### ISSUE THREAD

**Issue by lipt0n** [mlaursen/react-md#616]
Hi,
react-md is super cool, thanks for that.

it seems that NavigationDrawer should have transition effect, as far as i can tell it uses old (v1) version of react transitions - but, unfortunetly, without any effect.

I tried to add super long transitionEnterTimeout and transitionLeaveTimeout to see if it its doing anything. also I changed transitionName to something like example and add css:

`.example-enter.example-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
  background: red;
  border:10px red;
}

.example-leave {
  opacity: 1;
  background: blue;
  border:10px blue;
}

.example-leave.example-leave-active {
  opacity: 0.01;
  transition: opacity 300ms ease-in;
  background: green;
  border:10px green;
}`
just to see if it do anything. but it's not.

also I don't any tranition effect on examples provided in documentation.
soo..I think it is a bug.

Thx

**Comment by lepirlouit** [comment]
probably need to add the location as key in your switch

<Switch key={location.pathname}>

</Switch>

**Comment by lipt0n** [comment]
in what switch? 
i have only 
<NavigationDrawer>
{this.props.children}
</NavigationDrawer>



and children are provided by react-router v3

**Comment by lepirlouit** [comment]
look at the code for "React Router Example" by clicking the <> upper right
https://react-md.mlaursen.com/components/navigation-drawers

**Comment by mlaursen** [comment]
If you are using react-router v3, you should check out the [with-react-router-v3 example](https://github.com/mlaursen/react-md/tree/master/examples/with-react-router-v3). It shows how you can set up a `NavigationDrawer` and get the different routes to animate in with the default transition.

**Comment by lipt0n** [comment]
thx for help!
I changed it to 
    { children ? React.cloneElement(children, {key: pathname}) : null }

And I can see in react inspector what it got the key, but don't see any transition (also I dont see any in example: https://react-md.mlaursen.com/discover-more/routing-examples/navigation-drawers/drafts )

May this be because it looks like this:
![image](https://user-images.githubusercontent.com/676810/33171621-2d7e7578-d04d-11e7-80fc-34f74760b234.png)

and there is some div with key 0.1 always before my children ?
not sure, I't is not my div anyway :)
