### ISSUE TITLE
[Tabs] not passing `colored` prop makes inactive tabs unreadable

### ISSUE THREAD

**Issue by thaithco** [mlaursen/react-md#621]
### Description

Not passing `colored` prop to TabsContainer makes the tabs have nearly the same white for color and background. This makes them unreadable. Likely this happens with any configuration of TabContainer/Tabs/Tab components.

### Images/Screenshots
![image](https://user-images.githubusercontent.com/2186628/32748042-e70580ee-c888-11e7-85b4-0211dc68983d.png)
The text on the second tab is _just barely_ visible.

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/xPrqRX
### Version
- React - 16
- React-MD - 1.2

**Comment by mlaursen** [comment]
I ended up adding `activeClassName` and `inactiveClassName` to the `Tab` component as well as `activeTabClassName` and `inactiveTabClassName` to the `Tabs` component to solve this. It became a bit too hard to guess when different colors should be applied.
