### ISSUE TITLE
[Styling] body-1 and body-2-line-height defined but not used (and Bonus)

### ISSUE THREAD

**Issue by ChingxWando** [mlaursen/react-md#622]
### Description
Variables `$md-body-2-line-height` and `$md-body-1-line-height` for `body-1` and `body-2` were defined (as what the spec specifies, 20px and 24px)

But in their class definition those values were not used, instead `$md-line-height` was used. Where this still gives the same value for body-1 (20px), I believe it was not intentional... certainly not the case to be on both body-1 and body-2 :D?

```
/// A placeholder for the body-1 typography
%md-body-1 {
  @extend %md-tracking-10;

  line-height: $md-line-height;
}

/// A placeholder for the body-2 typography
%md-body-2 {
  @extend %md-tracking-10;

  line-height: $md-line-height;
}
```

### Images/Screenshots
N/A

### Link to a gist or code sample where the issue can be reproduced
[Observing that body-1 and body-2 had the same line-height... ](https://codepen.io/ChingxWando/pen/wPemmx)

Bonus: For some strange reasons the compiled sass bundle seemed to use number/ no unit line-heights. And It's causing body-1 and body-2 to calculate incorrectly as desktop media query kicked in.

```
Mobile view (14px font)
14px x 1.42857 = 20px

Desktop view (13px font, line-height remained same percentage)
13px  x 1.42857 = 18.57141 //???
```

### Version
- React -16
- React-MD - 1.2.8

**Comment by mlaursen** [comment]
Whoops.. Thanks! Should be fixed now. It is actually preferred to use unitless line heights when you can and I can't actually remember why I manually set the line-heights to `px` for these. I'll need to update most of my styles at some point to use `rem` and `em` instead as well :/
