### ISSUE TITLE
[Styling] Letter spacing value of md-tracking-5 is different to all the others

### ISSUE THREAD

**Issue by ChingxWando** [mlaursen/react-md#623]
### Description
`$md-tracking-5` is set as `.5` where prob meant `.05`

p.s. I also noticed something, `.1px`, `.2px` and `.05px` are in effect making no changes. I went on to check [the spec](https://material.io/guidelines/style/typography.html) and realised that no real value were given in the spec... it simply describe the business using some obscure, unitless numbers. Maybe we could experiment alittle bit with different base/ scale?.

Am quite happy to do pull request for bugs/ features tickets I submit... be nice to hear if I get recommendation/ approval to do that.

```
/// A placeholder for styling a class with the material design tracking of -10.
%md-tracking--10 {
  letter-spacing: -.1px;
}

/// A placeholder for styling a class with the material design tracking of -5.
%md-tracking--5 {
  letter-spacing: -.05px;
}

/// A placeholder for styling a class with the material design tracking of 0.
%md-tracking-0 {
  letter-spacing: 0;
}

/// A placeholder for styling a class with the material design tracking of 5.
%md-tracking-5 {
  letter-spacing: .5px;
}

/// A placeholder for styling a class with the material design tracking of 10.
%md-tracking-10 {
  letter-spacing: .1px;
}

/// A placeholder for styling a class with the material design tracking of 20.
%md-tracking-20 {
  letter-spacing: .2px;
}
```
### Link to a gist or code sample where the issue can be reproduced
N/A

### Version
- React - 16
- React-MD - 1.2.8

**Comment by mlaursen** [comment]
This should be fixed in @react-md/typography@v2.0.0-alpha-1

I'll comment on this issue again when v2 is released
