### ISSUE TITLE
[Styling] Current value for letter-spacing is effectively null

### ISSUE THREAD

**Issue by ChingxWando** [mlaursen/react-md#624]
### Description
Reading wikipedia, QuarkXPress and Adobe InDesign uses units of 1/200 and 1:1000. The spec used obscure/ unit-less numbers so it only gave guidelines on their relative difference comparing to each another.

Below a link to the reference image.

![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3LUZGWGdtZmFfUU0/style-typography-styles-tracking.png "")

Created pen displays words Tracking -10, Tracking -5, Tracking 0, on different units from 1 = 1/1000em, 1 = 1/500em, 1 = 1/250em and 1 = 1/125em.

From the experiment I reckon achieving results to the image actually impossible it, what the image really is, is a idealistic impression, the letters in it are certainly not evenly spaced, kerning is enabled on my browser by default but at this point in time there are no option to emphasis/ edit rendered kerning. The best thing that could be done, I reckon, is just choosing something that closely resembles the effect as well as  best improve readability in smaller sizes.

### Images/Screenshots
N/A

### Link to a gist or code sample where the issue can be reproduced
[Link](https://codepen.io/ChingxWando/pen/bYRjXz)
I use the technique of squinting and looking from a distance, I think something about or between 1/250 and 1/500 look good.

### Version
- React - 16
- React-MD - 1.2.8

**Comment by mlaursen** [comment]
This should be fixed in @react-md/typography@v2.0.0-alpha-1

I'll comment on this issue again when v2 is released
