### ISSUE TITLE
[NavigationDrawer] Pass className prop to mini drawer

### ISSUE THREAD

**Issue by cayasso** [mlaursen/react-md#636]
### Description
Hi dear, I tried to pass a class name to mini by passing navClassName, but this is only applied to the nav component and not to mini. By checking the code I noticed that currently there is no way to pass a class name to the mini drawer, because no props are being passed. Shouldn't we be passing props here?

https://github.com/mlaursen/react-md/blob/master/src/js/NavigationDrawers/NavigationDrawer.js#L981

### Version
- React - 16
- React-MD - 1.2.8

Thanks!!!

**Comment by cayasso** [comment]
Actually I think the className would need to be passed here https://github.com/mlaursen/react-md/blob/master/src/js/NavigationDrawers/NavigationDrawer.js#L977

**Comment by mlaursen** [comment]
I ended up adding 6 new props:
- `miniDrawerId`
- `miniDrawerStyle`
- `miniDrawerClassName`
- `miniNavItemsId`
- `miniNavStyle`
- `miniNavClassName`

to help with styling and add some missing ids.

**Comment by cayasso** [comment]
Thank you!
