### ISSUE TITLE
[Grid] - Add full width support

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#640]
### Description
Suggestion : It would be great to add a prop to the Grid component allowing it to be full-width. Currently, the width is determined by its children. But I often wanna create 2-cell grids or 3-cell grids which doesn't change width on cell's content update. My current workaround is to add margin-left 0 and margin-right 0 to the Grid style.

Just a thought.

### Version
- React - latest
- React-MD - latest

**Comment by mlaursen** [comment]
That makes sense. I think it will be a good addition.
