### ISSUE TITLE
[TablePagination] - wrong position on first render

### ISSUE THREAD

**Issue by ikovic** [mlaursen/react-md#641]
### Description
When loading the table data asynchronously by first showing the empty table and then rendering again when data is loaded, `TablePagination` is first rendered correctly, but then it does not update its position once the data comes in. Values like number of pages are updated, but `margin-left` stays the same and that results with the pagination being rendered a bit to the right.

When I resize the browser or go to another route and then return, it is rendered correctly. I've found this [issue](https://github.com/mlaursen/react-md/issues/351), but I can't apply the same solution.

### Images/Screenshots
![before_resize](https://user-images.githubusercontent.com/1204170/33434442-99dfab8c-d5df-11e7-92e5-568e1b371d36.png)
![after_resize](https://user-images.githubusercontent.com/1204170/33434441-99b08cee-d5df-11e7-8cf7-221aa5758f6c.png)

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/POxLqw?editors=0011
### Version
- React - 16.0.0
- React-MD - 1.2.8
- Tested only in Chrome

**Comment by c0b41** [comment]
@mlaursen this line never called, maybe it helps you https://github.com/mlaursen/react-md/blob/1c21aef83ab3a991dd30450e78109d5b49437566/src/js/DataTables/TablePagination.js#L362
