### ISSUE TITLE
[ExpansionPanel] Panel text flows outside of content in one line

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#642]
### Description
When using the ExpansionList / ExpansionPanel components, I found myself unable to write multi-line content text since it doesn't break lines properly. Everything stays on the same line, and overflows the containing div. This occures at the end of the expansion animation only.

Another bug is that when I play around with my window width, when the window gets too small, the header content appears outside the panel, expecially the expand icon.

### Code
```
<ExpansionList>
                    <ExpansionPanel
                      footer={ null }
                      label={[
                        'Search from Elasticsearch',
                        <div className='md-panel-secondary-label' key='secondary'>Find patents by keywords using our 10,000 patents database</div>,
                      ]}>
                        <div className='md-text'>
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
                        </div>
                    </ExpansionPanel>

                    <ExpansionPanel
                      footer={ null }
                      label={[
                        'Import from XML',
                        <div className='md-panel-secondary-label' key='secondary'>Get knowledge from your local patent files</div>,
                      ]}>
                        <p className='md-text'>
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
                        </p>
                    </ExpansionPanel>
                </ExpansionList>
```

### Images/Screenshots
![bugexpansion](https://user-images.githubusercontent.com/30187797/33466203-b2f424d2-d64c-11e7-9f3b-a8d23dc6a6f4.png)

PS : Used inside a NavigationDrawer

Workaround : manually set white-space to 'normal' in inner content.

### Version
- React - latest
- React-MD - latest

**Comment by mlaursen** [comment]
Do you have any additional styles set? I copy/pasted your example into a [codepen](https://codepen.io/mlaursen03/pen/GyKwyN?#) but it seems to be working as expected? This might also be related to the #645 with nested panels?

**Comment by ostrebler** [comment]
Yes it might have come from some inherited styles. The real issue with these nested expansion lists I think is #645

**Comment by mlaursen** [comment]
Ahh ok. I think this issue is coming from [these lines](https://github.com/mlaursen/react-md/blob/master/src/js/ExpansionPanels/ExpansionList.js#L146-L175) then. I might be able to fix it by changing the query selectors from 
```
this._container.querySelectorAll('.md-panel-header')
row.querySelectorAll('.md-panel-column')
```
 to 
```
this._container.querySelectorAll('> .md-panel-header')
row.querySelectorAll('> .md-panel-column')
```

but I haven't done much with Expansion lists yet personally so I'm not sure

**Comment by ostrebler** [comment]
Doesn't that generate backward compatibiliy issues when using transitions between the ExpansionList and its ExpansionPanels ? I guess it adds some spans / divs in between

**Comment by mlaursen** [comment]
Yeah, not too sure yet. I _think_ it should be okay since the tree looks like:

```
.md-expansion-panel-list
  .md-panel-header
    .md-panel-column
    .md-panel-column
  .md-panel-header
    .md-panel-column

... etc ...
```
and since the `ExpansionPanel` has to be a direct descendant of the `ExpansionPanel` to get some cloned props, it hopefully shouldn't break existing layouts.

I'm still not too sure though since I haven't used `ExpansionList`s and `ExpansionPanel`s outside of the simple examples. Hopefully these comments will help when someone starts digging into it a bit more.
