### ISSUE TITLE
[NavigationDrawer] how to change toolbarTitle and toolbarActions according to context 

### ISSUE THREAD

**Issue by wenq1** [mlaursen/react-md#643]
Is there a way to change toolbarActions and toolbarTitle contextually (i.e. according to the current route)

Example v4 basically shows the following structure:

```
App.js: 

class App extends React.Component {
    ....
        getChildContext () {
                return {
                        onChangeNavTitle:       this.onChangeNavTitle,
                };
        }


        render () {
                return (
                        <NavigationDrawer drawerTitle="Admin"
                                        toolbarTitle={<NavTitle title={navTitle} />}
                                        toolbarActions={navActions} ...>

                                <Switch key={this.props.location.key}>
                                        <Route exact path="/page1" location={this.props.location} component={Page1} />
                                </Switch>

                        </NavigationDrawer>
                );
        }
```

What I tried is inside Page1:

```
class Page1 extends React.Component {

        constructor (props) {
                super (props);

                this.state      = {
                        scripts:        [],
                };
        }

        componentWillMount () {
                this.context.onChangeNavTitle ('This is page 1');
        }
```

This is not elegant nor fully functional:

- Every subpages needs to call onChangeNavTitle () or otherwise the next routing target will still be using the previous navtitle
- One can register a router change event via this.props.history.listen (), but when route is changed via direct url input, the event is not fired

Is there better way to do it?

**Comment by mlaursen** [comment]
My documentation site is going with the second approach, but I haven't noticed the direct url input issue. It might be because my component calls the `updateLocation` when it mounts?

- [components/App/History.jsx](https://github.com/mlaursen/react-md/blob/master/docs/src/components/App/History.jsx#L15)
- [state/routing.js](https://github.com/mlaursen/react-md/blob/master/docs/src/state/routing.js#L3)
