### ISSUE TITLE
[SelectField] - Add loading indicator via a prop (e.g. loading, pending, async)

### ISSUE THREAD

**Issue by jbetancur** [mlaursen/react-md#644]
Currently, our app uses a number of drop-downs that when toggled fetches a list of values from an API. It would be more intuitive to have a way to allow a loading indicator during this async data fetch.

###  Description
I figure this can maybe work two different ways:

* `pending` prop that hides the context and activates a circular loading indicator
* as a property `async` that shows a loading indicator if menuItems length is zero or undefined

possibly allow inserting your own loading indicator via `loadingComponent={<Loader thing />}`

I can probably whip up a PR the near future, but I wanted to bounce the idea of having a loading indicator built into SelectField.

**Comment by hrmoller** [comment]
I like the idea as we're having quite the same use case as @jbetancur but in our case we're using [DropDownMenus](https://react-md.mlaursen.com/components/menus#dropdown-menu-examples).

I don't know how much (if anything at all) DropDownMenus and SelectFields are having in common but if the idea of a `pending` prop  (etc.) could be lifted to allow for broader use than just on the SelecField I think that would be ideal. Eventually I might be able to help implement the solution other places.

**Comment by mlaursen** [comment]
So maybe a higher order component kinda like this?

```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';

import getDisplayName from '../utils/StringUtils/getDisplayName';
import CircularProgress from '../Progress/CircularProgress';

export default function withLoader(Component, loadingPropName, a11yPropName) {
  return class ComponentWithLoader extends PureComponent {
    static displayName = getDisplayName(Component, 'Loader');
    static propTypes = {
      id: PropTypes.string, // recommended/required
      loadingId: PropTypes.string,
      loading: PropTypes.bool,
      loadingChildren: PropTypes.node,
      loadingInjection: PropTypes.oneOf(['prepend', 'append', 'replace']).isRequired,
    };

    static defaultProps = {
      loadingInjection: 'replace',
      loadingChildren: <CircularProgress centered />,
    };

    render() {
      const {
        loading,
        loadingInjection,
        loadingId: propLoadingId,
        loadingChildren: propLoadingChildren,
        ...props
      } = this.props;
      const { id } = this.props;

      if (loading) {
        const loadingId = propLoadingId || (id ? `${id}-loading` : null);
        const prepend = loadingInjection === 'prepend';
        const append = loadingInjection === 'append';
        let loadingChildren = propLoadingChildren;
        let loadingProp = this.props[loadingPropName];
        if (loadingId && React.isValidElement(loadingChildren)) {
          loadingChildren = React.Children.only(loadingProp);
          loadingChildren = React.cloneElement(loadingProp, { id: loadingId, key: loadingId });
        }

        if (append || prepend) {
          loadingProp = loadingProp ? React.Children.toArray(loadingProp) : [];
          if (append) {
            loadingProp.push(loadingChildren);
          } else {
            loadingProp.unshift(loadingChildren);
          }
        } else {
          loadingProp = [loadingChildren];
        }

        props[loadingPropName] = loadingProp;

        // Inject the accessibility either into props or a custom object prop
        const a11yProp = a11yPropName ? props[a11yPropName] || {} : props;
        a11yProp['aria-busy'] = true;

        if (loadingId) {
          a11yProp['aria-describedby'] = loadingId;
        }
      }

      return <Component {...props} />;
    }
  };
}
```

### Usage

```
const LoadingSelectField = withLoader(SelectField , 'menuItems', 'listProps');
const LoadingMenuButton = withLoader(DropdownMenu, 'children', 'listProps');

...
render() {
  const { loadingSelect, loadingMenu, selectItems, menuItems } = this.props;
  return [
    <LoadingSelectField key="select1" loading={loadingItems} menuItems={selectItems} loadingInjection="prepend" />,
    <LoadingSelectField key="select2" loading={loadingItems} menuItems={selectItems} loadingInjection="append" />,
    <LoadingSelectField key="select3" loading={loadingItems} menuItems={selectItems} loadingInjection="replace" />,
    <LoadingSelectField key="menu" loading={loadingMenu}>{menuItems}</LoadingSelectField>,
  ];
}
```

So when the `loading` prop is `true`:
- `select1` would inject the loading indicator as the first item in the menu items list
- `select2` would inject the loading indicator as the last item in the menu items list
- `select3` would replace the entire menu items list with the loading indicator.

In these cases, the accessibility props would also be injected when needed as well.

This should _theoretically_ work except for the fact that the `SelectField` needs to be updated to handle the `listProps` like the other menu variations, but I haven't actually tried it.

**Comment by jbetancur** [comment]
Yea, I really like the idea of wrapping it with an HOC. Seems like this would be flexible for most any use case.

**Comment by mlaursen** [comment]
Cool; I'll target it for the 1.3.0 release. I've been planning on adding a couple more HOCs to this library, so it would probably be a good time to start adding them.
