### ISSUE TITLE
DialogContainers - onHide function only gets called once when pressing the escape key

### ISSUE THREAD

**Issue by rvarela11** [mlaursen/react-md#648]
### Description

I have 2 nested DialogContainers. The second one is a warning to make sure the user really wants to cancel/close the 1st dialog container. I am running into the issue where the escape key only calls the onHide function once therefore not showing the warning dialog box after a second time. Is there a way to make sure the onHide function gets called if the escape key gets pressed more than once?

**Comment by mlaursen** [comment]
Yeah, it should now only remove the keydown listener when unmounting or the visible prop changes to false.
