### ISSUE TITLE
[SelectField] - Select field does not set visible menuitem to value 

### ISSUE THREAD

**Issue by Tasemu** [mlaursen/react-md#652]
### Description

I have a select field with various menu items. I select one item which brings up a confirm dialog. IF i cancel the dialog it re-renders the SelectField with the original value, HOWEVER the currently selected value visible is still the new menu item.

Better explanation...

I try to set the select value using state, in response to manually selecting a menuitem. The SelectField does not set the visible menuitem to the new menuitem (the one set by setState()).

### Version
- React - 16
- React-MD - ^1.2.8
- Browser

**Comment by mlaursen** [comment]
Can you give a code example? You can use this [codepen](https://codepen.io/mlaursen03/pen/ZLMWwX) if that helps. I'm not entirely sure what the bug/feature request is here.
