### ISSUE TITLE
[Dialogs] - Dialog flickers while opening or closing in IE/Edge

### ISSUE THREAD

**Issue by thezefs** [mlaursen/react-md#655]
Steps to reproduce:

1. Open https://react-md.mlaursen.com/components/dialogs in Microsoft Edge browser
2. Try to open any of proposed dialogs demos
3. Dialog flickers while animated

My MS Edge version:
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

The only workaround I found for now is to disable dialog animation:
$md-dialog-transition-time: 0;

Is there any other solution to this issue?

**Comment by mlaursen** [comment]
I'm not too sure yet how to fix this. It also happens in IE11 sadly (which is supported :( ). I'll probably dig into this more soon since we are going through heavy QA right now and this might come up.

**Comment by thezefs** [comment]
Do you have any idea when it could be fixed?

Could you consider temporary fix by bringing back your reverted change (1fc5b0b), and just making so md-overlay depends on component visibility?
Example:
line 615 'md-overlay--active': !fullPage && active && **visible**

I think it would be good enough solution - it would fix animation issues.

**Comment by mlaursen** [comment]
I'll try this out and see if it is ok and target this again for the 1.2.12 release.

**Comment by mlaursen** [comment]
It seems to work as expected in Edge with the above suggestion. Closing.

**Comment by mlaursen** [comment]
Nevermind. Applying these fixes makes Mobile Safari flash.

**Comment by thezefs** [comment]
Is there a plan to fix this issue?

**Comment by mlaursen** [comment]
Yeah, but it won't be for awhile :(. I am going to be fixing it when I change how dialogs are positioned on the page (no longer transforms) and the flow for rendering when visible is changed to true (fixing portal api and rendering elements order).

If someone has a better idea before then, I'll happily accept a PR though.
