### ISSUE TITLE
[SelectField] Edge & IE - opening select immediately causes it to close again.

### ISSUE THREAD

**Issue by Tasemu** [mlaursen/react-md#659]
### Description
In internet explorer and edge, when opening a select field, it immediately closes again. Double clicking the select field appears to open it properly but it feels very janky.

### Version
- React - 16
- React-MD - 1.2.8
- Browser  Edge & IE11

**Comment by mlaursen** [comment]
Darn. I fixed this bug once before for iOS devices. I'll try to dig into why IE/Edge are doing it now.

**Comment by mlaursen** [comment]
I can't seem to reproduce this. What versions of Edge and IE? I tried with:
- Microsoft Edge 41.16299.15.0
- Internet Explorer 11: 11.192.162299.0
