### ISSUE TITLE
[Dialogs] - Dialog jumps before closing animation starts in Edge browser

### ISSUE THREAD

**Issue by thezefs** [mlaursen/react-md#660]
Steps to reproduce:

1. Open https://react-md.mlaursen.com/components/dialogs in Microsoft Edge browser
2. Open any of proposed dialogs demos in Microsoft Edge browser
3. Close it
4. Dialog jumps before closing animation starts

My MS Edge version:
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by mlaursen** [comment]
It appears to work correctly on Edge 38 (what I have on my VM). I'll try debugging the newer versions and IE11 again.

**Comment by thezefs** [comment]
It looks like it jumps only if your zoom level is different from 100%. On zoom >100% it jumps towards down-right, on zoom  <100% upper-left.
Try different zoom in your MS Edge 38
