### ISSUE TITLE
Datepicker - Dates in calendar are not aligned with the correct day of the week

### ISSUE THREAD

**Issue by justincobb** [mlaursen/react-md#661]
### Description
The issue is reproduced on the demo site. You can see that the calendar shows Jan 4th 2018 as being Friday, which it is not. The 4th is on Thursday. The side panel shows the correct information with the 5th being on Friday. If you open up the "Select an appointment date" picker on the demo page you should see the same problem.
### Images/Screenshots
![image](https://user-images.githubusercontent.com/4258705/34594444-4aa0a83a-f18e-11e7-9b12-9053721ad9b2.png)

### Link to a gist or code sample where the issue can be reproduced
https://react-md.mlaursen.com/components/pickers/date
### Version
- React - (Whatever is running on the react-md demo page)
- React-MD - 1.2.10
- Browser - Chrome

**Comment by hisapy** [comment]
Duplicate of #634 ... can you please close it?

**Comment by justincobb** [comment]
I didn't see that one. Thanks.
