### ISSUE TITLE
[Tabs] - Wrong height calculation when content has margin

### ISSUE THREAD

**Issue by dmitriirudakov** [mlaursen/react-md#662]
### Description

Hi guys,
Looks like it's an issue with calculation of tab content height. 
Based on my quick research I can assume that a root cause is in setting 'panelHeight' in '_resizePanel' function.
offsetHeight doesn't include margin so scroll is present if margin was set.
Is it expected?

```
_this._resizePanel = function () {
      if (!_this._container) {
        return;
      }

      var activePanel = _this._container.querySelector('.md-tab-panel[aria-hidden=false]');
      if (activePanel && _this.state.panelHeight !== activePanel.offsetHeight) {
        _this.setState({ panelHeight: activePanel.offsetHeight });
      }
};
```

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/aELPOL

### Version
- React - 16.2.0
- React-MD - 1.2.10

**Comment by mlaursen** [comment]
Yeah, I think this is a bug. The height should also include margins for these panels

**Comment by zgavin1** [comment]
Hi @mlaursen. I'm interested in submitting a PR to fix this bug. I've followed the steps you outlined to getting the environment set up. Are there any other processes you would prefer for me to follow for addressing a small fix like this?

**Comment by mlaursen** [comment]
@zgavin1 I don't think much is necessary for this one. If you really want to go the extra mile, you could write tests to mock the different attributes and show that it includes margin and padding. I do think it is overkill for this one. Thanks in advance for submitting a PR!

**Comment by zgavin1** [comment]
OK if you think it would be overkill, I'll just go ahead an submit the PR
