### ISSUE TITLE
[SelectFields] - Active item adds a class called undefined

### ISSUE THREAD

**Issue by davidgit75** [mlaursen/react-md#663]
When thre's an active item on SelectField component is added to this item a class **undefined**
```
<li class="md-list-item undefined">
  <div id="carrier-matches__carrier-sales-person-options-active" role="option" data-id="79" data-value="945" class="md-fake-btn md-pointer--hover md-fake-btn--no-outline md-list-tile md-text" tabindex="-1" aria-pressed="false"><div class="md-ink-container"></div><div class="md-tile-content"><div class="md-tile-text--primary md-text--theme-primary">User Name</div></div></div>
</li>
```

It this a bug or what am I doing wrog

In version 1.2.8 doesn't add some class but on version 1.2.9 and 1.2.10 add the undefined class.

Thanks

**Comment by mlaursen** [comment]
Would you happen to have a code sample for this? I don't seem to see this behavior on my documentation site. The only thing that I can think of is that one of your menuItems has an attribute: `className: 'undefined'` but that doesn't seem likely :/

**Comment by mlaursen** [comment]
Whoops, I lied. I see it now. It is a bug and should be fixed.
