### ISSUE TITLE
[Dialogs] - Consequently shown dialogs block application screen sometimes

### ISSUE THREAD

**Issue by thezefs** [mlaursen/react-md#664]
I show few dialogs consequently. The first dialog shows that data is being loaded, then it closes and instead dialog with the error message is shown.
**Sometimes**, gone dialog leaves emtpy <span> element in DOM:
`<span class="md-dialog-container" tabindex="-1"></span>`

And it was not a big deal until 1.2.**10**
https://github.com/mlaursen/react-md/commit/142626aaedfeaab4d50c2383e576780e32d8b3d2
Until this change, md-overlay class was dependent on dialog visibility - but not anymore.
Now, if closed dialog fails to remove its span container, it results in this:
`<span class="md-dialog-container md-overlay" tabindex="-1"></span>`

md-overlay class sets z-index to 20, so overlay blocks the screen, and the user cannot close the actual dialog or do anything else.

I think that the root cause is the fact that span element is not removed sometimes, but because of 1.2.10 changes, it became more noticeable.
I have this issue in Chrome (haven't tested other browsers).

Unfortunately, I had to downgrade to 1.2.9 for now.
 
_If you cannot repro or fix this issue, could you consider making md-overlay dependent on visibility again? It would hide the root cause again, but it could be a good-enough solution. It would allow to upgrade to the latest version of react-md that has other bugs fixed (e.g. Edge animation fix)._

**Comment by mlaursen** [comment]
Oof. That was one of the side-affects I didn't think about after that change. I'll patch it back and see if I can come up with a better way to fix IE11/Edge dialogs flashing
