### ISSUE TITLE
Remove ripple effect on active item in a SelectField

### ISSUE THREAD

**Issue by davidgit75** [mlaursen/react-md#665]
Hi, how can I remove ripple effect on SelectField's active item?
So i added a custom class to every item (adding className key on every object of the menuItems array) and changed a custom background when is active but I can't keep this effect so the background color seems a little darker for the shadow added for the effect.

**Comment by mlaursen** [comment]
You can update each item in the list to have `inkDisabled: true` if you want to completely get rid of the ink affect. So something like:

```
const menuItems = someArray.map(item = >({ ...item, inkDisabled: true });

<SelectField {...props} menuItems={menuItems} />
```

This won't really work with keyboards until #666 is released though.

**Comment by davidgit75** [comment]
@mlaursen great, this worked. Thanks
