### ISSUE TITLE
[DatePicker] - Controlled DatePicker crashes when selecting the current date twice

### ISSUE THREAD

**Issue by bsunderhus** [mlaursen/react-md#669]
### Description

You can see this problem hapening in the online [documentation ](https://react-md.mlaursen.com/components/pickers/date#controlled) itself. Just click in the controlled date picker, select the current date, press ok and then click again in the controlled date picker.

The error `Provided date is not in valid range` will be spilled out and since the documentation itself has no error boudaries the page will be **unmounted**!

### Version
- React - 16.2.0
- React-MD - 1.2.9
- Browser

**Comment by mlaursen** [comment]
This might have been fixed in one of the versions in between 1.2.9 and 1.2.11. I can't seem to reproduce the error. Is there a specific browser or device that broke for you?

**Comment by willdunlop** [comment]
> This might have been fixed in one of the versions in between 1.2.9 and 1.2.11. I can't seem to reproduce the error. Is there a specific browser or device that broke for you?

This happens for me in the Chrome browser. I've been able to reproduce this error for any date that is the 13th or higher and I believe it comes down to the locales settings not being considered while the component is being controlled. I imagine this wouldn't be an issue for anyone testing with an en-US setting
