### ISSUE TITLE
[Collapse] - Uncaught error when changing collapsed state

### ISSUE THREAD

**Issue by luyc** [mlaursen/react-md#672]
### Description
When I used Collapse Component , I switch the collapse state, it will throw error: Uncaught Error: Expected ref to be a function or a string.
So I debug the source code, I found this code,
When collapsed value is true, and style.height is existing, will throw this error

### Images/Screenshots
![a](https://user-images.githubusercontent.com/4544349/35319216-d008f4e2-0119-11e8-80d6-f4c95d641495.jpg)
![image](https://user-images.githubusercontent.com/4544349/35319160-92eb59d8-0119-11e8-8d16-1195c77a4518.png)

### Version
- React - 16.2.0
- React-MD -  1.2.11

**Comment by mlaursen** [comment]
Do you have a reproducible code sample by chance? I'm not seeing this in React 16.0 or when I upgraded to React 16.2.

I'll still update the code so that the ref will be null/undefined or the function instead of boolean or the function.

**Comment by luyc** [comment]
When collapsed is false, or style.height is null, will return this error.  But the style.height will calculate before rendering. I think `!collapsed && _this2._setHeight` will return true or false, so should not assign to ref.   
Additional permis： 
     This Component is a individual component libraries.
error code:
```
// Demo.jsx
export default class Demo extends React.PureComponent {
    render() {
      const {collapsed}  =  this.props
      return <Collapse collapsed={collapsed}><div>Hello</div></Collapse>
    }
}

// Main.jsx
export default class Main extends React.PureComponent {
    render() {
      const {collapsed}  =  this.props
      return <Demo>Hello</Demo>
    }
}
```
I resolved this  error:
```
// Demo.jsx
export default class Demo extends React.PureComponent {
    render() {
      const {collapsed}  =  this.props
      return <Collapse collapsed={collapsed}><div>Hello</div></Collapse>
    }
}

// Main.jsx
export default class Main extends React.PureComponent {
    render() {
      const {collapsed}  =  this.state
      return <Collapse collapsed={collapsed}><Demo>Hello</Demo></Collapse>
    }
}
```
So it's very interesting
