### ISSUE TITLE
Autocomplete type='search' do not show reset icon on Ubuntu-Mozilla 58.0 (64-bit)

### ISSUE THREAD

**Issue by dnyaneshbhalerao** [mlaursen/react-md#673]
I am new to react and [here](https://codepen.io/novusratoon/pen/EozwNy?editors=1010) I found some unexpected behaviour that is reset Icon (x) is visible on Chrome but not on Mozilla 58.0.

**Comment by c0b41** [comment]
Actualy this is not bug, firefox not support search icon

**Comment by dnyaneshbhalerao** [comment]
@c0b41 No it is not about the search icon. It's the reset icon (x) I am talking about.

**Comment by c0b41** [comment]
@dnyaneshbhalerao same
