### ISSUE TITLE
[Button] - flat && swapTheming && disabled Buttons are not well colored.

### ISSUE THREAD

**Issue by lepirlouit** [mlaursen/react-md#683]
### Description
disabled Button with flags flat and swapTheming enabled are not in the right color.
probable issue with computing the classnames.

Overflow Classnames : 
md-background--primary md-background--primary-hover

Missing ClassNames : 
md-text--disabled

current status : 
```flat   &&   swapTheming : md-btn md-btn--flat md-btn--text md-background--primary md-background--primary-hover md-inline-block
flat   && noSwapTheming : md-btn md-btn--flat md-btn--text md-text--disabled                                   md-inline-block
raised &&   swaptheming : md-btn md-btn--flat md-btn--text md-btn--raised-disabled md-text--disabled           md-inline-block
raised && noswaptheming : md-btn md-btn--flat md-btn--text md-btn--raised-disabled md-text--disabled           md-inline-block
```

### Images/Screenshots
N/A
### Link to a gist or code sample where the issue can be reproduced
CodePen : https://codepen.io/anon/pen/bLrVvW

### Version
- React - 16.2.0
- React-MD - 1.2.11
- Browser Firefox / Chrome

**Comment by mlaursen** [comment]
Think updating it to look like the disabled raised buttons would be a good default? I was debating making it look like the other flat buttons, but I think shifting from no background to a background might look weird.

> The 2 disabled buttons in the Themi Swapped Examples are the new ones showing the disabled styles


<img width="810" alt="screen shot 2018-02-13 at 3 47 00 pm" src="https://user-images.githubusercontent.com/3920850/36178156-3c1dcfa2-10d5-11e8-9f56-bd450f0b9822.png">

**Comment by lepirlouit** [comment]
ok for me.

**Comment by iuliux** [comment]
Is there any update or timeline on this one?
Trying to figure out if I should work around it or just have a little patience.

**Comment by mlaursen** [comment]
Sorry for the lack of updates -- Should definitely work around it for now. This will be going away in v2 as the newer theming system should allow for these changes a bit easier: https://react-md.dev/packages/button/demos#custom-button-theme-title
