### ISSUE TITLE
[Drawers/NavigationDrawers] - Allow better media queries

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#685]
Right now, it is extremely hard to be able to set up custom media queries for figuring out the current device since `min-width` is not the best check. There are some use cases where you would like the app to have mobile styles on landscape tablets but also show the desktop view.

I'm not sure the best way to handle this yet. Maybe just a `mediaQuery` function prop that returns an object of device status?

```
/**
 * Only allow mobile or desktop views. Allow landscape tablets to be considered desktop
 *
 * This should theoretically make it so that portrait tablets and phones are considered mobile while
 * landscape tablets and desktop screens are considered desktop.
 */
function mediaQuery() {
  let desktop = window.matchMedia('screen and (min-device-width: 768px)').matches;
  if (desktop && window.innerHeight > window.innerWidth) {
    // android soft keyboards reduce the view height, so check if there is a TextField in focus to _guess_ the correct orientation
    desktop = !document.activeElement || !document.activeElement.tagName.match(/input|textarea/);
  }

  return { mobile: !desktop, tablet: false, desktop };
}
```

**Comment by Kaishiyoku** [comment]
That would be better. I recently stumbled across this and had issues working with the min-Sizes of the Drawer on the one hand and CSS-Media-Queries on the other because the default values were different.

**Comment by mlaursen** [comment]
I implemented new components and mixins in v2 to handle sizing in apps a bit better: https://react-md.dev/packages/sizing/demos
