### ISSUE TITLE
[SASS] Theme customization

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#688]
Hey,

I have a lot of trouble understanding how the SASS theme customization works. I spent a couple hours trying to figure it out. For example, how to I customize the icon button color ?

Currently I have this : 

```
@import '../../node_modules/react-md/src/scss/react-md';

$md-light-theme: true;
$md-primary-color: #1E88E5;
$md-secondary-color: #EF5350;

$md-light-theme-text-color: rgba(255, 255, 255, 0.7);
$md-light-theme-secondary-text-color: rgba(255, 255, 255, 0.45);
$md-light-theme-icon-text-color: rgba(255, 255, 255, 0.6);

@include react-md-everything;

```

And the icon is still black. It looks like the light-theme is not applied.
Thank you for your help.

Olivier

**Comment by mlaursen** [comment]
Hey, this actually has to do with some Sass variable default problems. For some of the more complex variables that rely on others, the only way you can get around it is by setting the overrides before you import react-md.

So for example:

```scss
$md-light-theme: true;
$md-primary-color: #1E88E5;
$md-secondary-color: #EF5350;

$md-light-theme-text-color: rgba(255, 255, 255, 0.7);
$md-light-theme-secondary-text-color: rgba(255, 255, 255, 0.45);
$md-light-theme-icon-text-color: rgba(255, 255, 255, 0.6);

@import '../../node_modules/react-md/src/scss/react-md';

@include react-md-everything;
```

_should_ be more what you are looking for. I need to do some more documentation and some changes to make this not happen though.

**Comment by ostrebler** [comment]
Thank you, that helped.
