### ISSUE TITLE
[Tabs][MenuButtonColumn] - Menu position is not right.

### ISSUE THREAD

**Issue by lepirlouit** [mlaursen/react-md#689]
### Description
The menu is not at the right position when tabs are in a container that is not 100% width.
When table is put in a container that is 75% then it's working good.
So it's linked with the TabsContainer.

### Images/Screenshots
![image](https://user-images.githubusercontent.com/1354968/36440859-1d6cce04-1671-11e8-947c-d0d541a36b37.png)

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/yvKEgv
### Version
- React : 16.2.0
- React-MD : 1.2.11
- Browser : Firefox and Chrome

**Comment by lepirlouit** [comment]
fixed this by adding 
`simplifiedMenu={true}`

**Comment by mlaursen** [comment]
Yeah, this has to do with the fact that my layovers haven't been able to adjust themselves yet when they are in a container with `transform: translate ....` yet.

**Comment by lepirlouit** [comment]
My current workaround is to remove the TabsContainer which is as explained in the docs optional. And did like on the documentation website to handle the tabs switching
