### ISSUE TITLE
[Drawers] Mini Drawer does not work properly

### ISSUE THREAD

**Issue by zenaway** [mlaursen/react-md#690]
React version : 16.2.0
react-md version : 1.2.11

I do not want a navigation drawer because I do not need a toolbar, so I want to use the Drawer's PERSISTENT_MINI drawer.

So I just pasted example and changed the type only.

But as I thought, Mini <-> Persistent will not change and only Mini Drawer shape will change to strange.

I do not know if I have something wrong or there are other options.

**Comment by mlaursen** [comment]
Sorry, right now I haven't implemented a good way to use mini drawers without the `NavigationDrawer` :/
In reality, providing `PERSISTENT_MINI` or `TEMPORARY_MINI` to a `Drawer` doesn't really do anything other than set the size to be smaller.

**Comment by zenaway** [comment]
@mlaursen too bad. :(
material-ui did not want to slow down
We should wait or make it look different.

But thank you for always making it hard! I'm writing this library for most of the projects I do.
