### ISSUE TITLE
Color classes are overridden with custom theme defaults

### ISSUE THREAD

**Issue by Indexu** [mlaursen/react-md#695]
### Description
If you create a custom theme and then use an md-[COLOR]-[VALUE]--[TYPE] class name on a tag, then the theme will override that with its own defaults.
### Images/Screenshots
![Chrome inspect element](https://i.imgur.com/c7uAq61.png)
### How to reproduce
Create a new theme (e.g. the default dark theme)
Apply the theme on the application
Create a p tag with a color class (e.g. md-red-500--text)
### Version
- React - 16.2.0
- React-MD - 1.2.11

**Comment by mlaursen** [comment]
Oof. That isn't something I thought about. I'll think about some better ways to apply base colors and work with the different `md-[COLOR]-[VALUE]--[TYPE]` classes
