### ISSUE TITLE
[DialogContainer] translate3d makes messy gradient backgrounds

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#696]
Hey,

Here is what I use for the .md-background--card : 
```
.md-background--card {
    background: radial-gradient(circle farthest-corner at 24% 14%, #394f66 0%, #30465e 21.5%, #273d55 70.2%, #223a54 83.6%, #1a2c3f 100%) fixed;
}
```

Here is what I get when I show a centered dialog with a lot of content : 

![bug-dialog](https://user-images.githubusercontent.com/30187797/36761770-edcb84be-1c20-11e8-8183-066419bb8250.jpg)

I think it is about the transform here : 

```
.md-dialog--centered {
    left: 50%;
    max-height: calc(100% - 48px);
    max-width: calc(100% - 80px);
    top: 50%;
    transform: translate3d(-50%, -50%, 0);
}
```

What can I do to solve this ?

Edit : Using a simple background color instead of a gradient solved the problem. But I wonder if there is anything to do to make the gradient work.

**Comment by mlaursen** [comment]
This has now been added as a new opt-in feature until the next major release where it will be enabled by default.

Setting `$md-dialog-use-flex-positioning: true` will now use flex-based centered instead of the old `left`/`top` + `translate3d` hack.
