### ISSUE TITLE
[CircularProgress] - high CPU when multiple instances on a page

### ISSUE THREAD

**Issue by stickfigure** [mlaursen/react-md#697]
### Description

Put a few dozen small CircularProgress indicators on a page and watch the CPU go crazy :-(

### Version
- React - 16
- React-MD - 1.2.11
- Browser - Chrome

**Comment by mlaursen** [comment]
Yeah, I've been thinking of stopping SVG animation for the circular progress since it is apparently deprecated (or being deprecated). I'll try to figure out a better way to have these rendered.
