### ISSUE TITLE
[DialogContainer] Warning about providing title and fullPage, even when fullPage is false

### ISSUE THREAD

**Issue by doug2k1** [mlaursen/react-md#700]
### Description
The `DialogContainer` component gives the following warning when the `title` is set and `fullPage` is explicit set to `false`.

> Failed prop type: You provided a `title` to the `DialogContainer` when `fullPage` has been set to true. A title for a full page dialog should be rendered as a child instead.

### Link to a gist or code sample where the issue can be reproduced
https://codesandbox.io/s/pmyo6nv267
### Version
- React - 16.2.0
- React-MD - 1.2.11

**Comment by mlaursen** [comment]
Luckily it looks like this is a simple fix to make sure that the `fullPage` is enabled instead of [just not errored](https://github.com/mlaursen/react-md/blob/master/src/js/Dialogs/DialogContainer.js#L212-L214).
