### ISSUE TITLE
Changelog please?

### ISSUE THREAD

**Issue by bingomanatee** [mlaursen/react-md#710]
Could we get a changelog? I noticed since I started using your project at v. 1.2, its gotten up to v. 1.6; I would like to know if there are API changes/breaking changes since I started using react-md.

**Comment by mlaursen** [comment]
You should always be able to see the changelog for each release [here on github]( https://github.com/mlaursen/react-md/releases) or the [What's new](https://react-md.mlaursen.com/discover-more/whats-new) page on the documentation website.
