### ISSUE TITLE
[DropdownMenu] Horizontal anchors don't work as expected

### ISSUE THREAD

**Issue by replaysMike** [mlaursen/react-md#714]
### Description

When setting HorizontalAnchors, with or without the position option they don't work as expected.

They just don't seem to work at all. Either I get a centered menu when using MenuButton/DropdownMenu, or I get a left aligned menu depending on combination of settings. When applying `position:{DropdownMenu.Positions.BELOW}` I pretty much have no control over the anchor.

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/replaysMike/pen/qooOBo

### Version
- React - latest
- React-MD - latest
- Browser - Chrome

**Comment by mlaursen** [comment]
Hmmm darn. I thought I fixed this with the `belowAnchor` prop, but that doesn't work as expected either. I'll look into fixing it
