### ISSUE TITLE
[SelectionControlGroup] - adds a comma even for a single selection

### ISSUE THREAD

**Issue by Pranjali14** [mlaursen/react-md#716]
### Description
SelectionControlGroup of type checkbox, adds a comma even for single value chosen.  
### code sample where the issue can be reproduced
https://codepen.io/Pranjali14/pen/oqMjWw

### Version
- React - 16.3.0
- React-MD - 1.2.13

**Comment by Kaishiyoku** [comment]
@Pranjali14 the codepen expired for non-pro users

**Comment by Pranjali14** [comment]
@Kaishiyoku updated the codepen link.

**Comment by mlaursen** [comment]
This should be fixed and published now.
