### ISSUE TITLE
[FloatingButton] - Floating icon buttons should have overflow:hidden

### ISSUE THREAD

**Issue by nbolten** [mlaursen/react-md#717]
### Description
Floating icon buttons (and possibly all icons?) appear to have invisible overflow by default. I didn't notice this until this edge case:
1. A 100% width parent div with `position:relative`
2. Trying to stick a FloatingButton with `position:absolute` in the upper right (`top:0; right:0;`)

In this case, the page gets a horizontal scroll bar with blank content on the right, equivalent to the overflow from the floating icon button. e.g., I used the `information` icon, and the overflow is equivalent to the text length.

Setting `overflow:hidden` on the parent button solves this issue, though it may just be masking an underlying problem.

### Link to a gist or code sample where the issue can be reproduced
This seems to reproduce what I'm talking about. Setting `position:relative` explicitly doesn't seem to be necessary to get the behavior.

https://codepen.io/anon/pen/eMLWxb

### Version
- React - 15+
- React-MD - 1.2.11 (reproducible on latest as well)

**Comment by mlaursen** [comment]
Is there a reason the [fixed](https://react-md.mlaursen.com/components/buttons?tab=1#button-proptypes-fixed) and [fixedPosition](https://react-md.mlaursen.com/components/buttons?tab=1#button-proptypes-fixed-position) don't work for you? It could also be that during some of my documentation site changes, I forgot to add an example back for fixed floating buttons.
