### ISSUE TITLE
[Button] - Buttons should use secondary color

### ISSUE THREAD

**Issue by thezefs** [mlaursen/react-md#718]
Currently button color is primary color of the theme, while according to Google, it should be secondary color.
Proof - https://material.io/color/#!/?view.left=0&view.right=0&primary.color=37474F&secondary.color=D84315

Can you fix that?
Is there any walkaround meanwhile?

**Comment by phlare** [comment]
You can just use `secondary` prop

**Comment by mlaursen** [comment]
Going to close since it exists as the `secondary` prop.
