### ISSUE TITLE
Cell - centering fails when media queries are active

### ISSUE THREAD

**Issue by Elemecca** [mlaursen/react-md#721]
In at least Chromium 65.0.3325.162, `<Cell position="center">` does not center the cell because there's a media query that sets the margin at a higher specificity.

The media query selectors for cell (e.g. `@media (min-width: 840px) .md-cell`) all set `margin: 8px` and override the less-specific `.md-cell--center` selector used for centering. Changing the centering selector to `.md-cell.md-cell--center` makes it more specific than the media queries and so makes centering work again.

**Comment by Elemecca** [comment]
This issue can be worked around by adding this SCSS snippet after including react-md:
```scss
/* the default .md-cell--center selector isn't specific enough
 * when any of the width media queries are active and changing the margins
 * see <https://github.com/mlaursen/react-md/issues/721>
 */
.md-cell.md-cell--center {
  @extend .md-cell--center;
}
```

**Comment by jkanczler** [comment]
There's an ugly workaround.
```
className={ `.${Cell.getClassName({ size: 6, position: "center" })}`
```

Use a string interpolation and put a . right away before the class names. So the `md-cell` class won't be applied.
