### ISSUE TITLE
Can't override default prop values

### ISSUE THREAD

**Issue by bioslife** [mlaursen/react-md#724]
I can't override the default prop's values:
```
<SelectionControlGroup
          ...
          component="span"
          ...
/>
```

I set the "span" value for prop **component**, but it doesn't override default value "fieldset".

### Version
- React - 16.0.2
- React-MD - 1.2.13

**Comment by mlaursen** [comment]
It looks like it works to me: https://codepen.io/mlaursen03/pen/LmGjWo?editors=0010#0

Do you have a live example where it does not work?
