### ISSUE TITLE
Toolbar - A component relative is partially hidden when setting custom md-toolbar-prominent-height

### ISSUE THREAD

**Issue by EyalIsr** [mlaursen/react-md#726]
### Description
When setting a css's `md-toolbar-prominent-height` for something bigger than the 128px default value, the component which should be "anchored" to the `Toolbar` is hidden - even though I set `md-toolbar-relative--prominent` - which I thought should make the component placed just below the `Toolbar`.  
### Images/Screenshots
![image](https://user-images.githubusercontent.com/1658701/39182509-d05436c6-47c5-11e8-9654-530bd1d4105a.png)

As you can see, the card's header and some text are hidden. 
When the default height is used, (that means - not setting any `md-toolbar-prominent-height` in css) I get a reasonable layout.

This is how it looks like with default height:
![image](https://user-images.githubusercontent.com/1658701/39182829-cd2146fa-47c6-11e8-9fcd-2cfca13cd1a1.png)

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/eyalisr/pen/KRzNxE

**Comment by mlaursen** [comment]
This is something that can only be automatically fixed when setting the scss variables before compilation. You could do:

```scss
$md-toolbar-prominent-height: 250px;

@include 'react-md/src/react-md';

@include react-md-everything;
```

which will automatically update the `.md-toolbar-relative--prominent` className to correctly do a `margin-top: 250px;`

**Comment by EyalIsr** [comment]
@mlaursen I'm not sure I followed: 
Where're those variables should be declared?

Thanks
