### ISSUE TITLE
problem in md-icon , icon dont show in some system

### ISSUE THREAD

**Issue by riazi** [mlaursen/react-md#733]
hi 
i have problem in md-icon matrial-icons , 
when i use it in my system show correct but in some system dont show icon and just text show

### Version
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^4.0.0-alpha.6",
    "font-awesome": "^4.7.0",
    "i": "^0.3.6",
    "npm": "^5.6.0",
    "react": "^16.2.0",
    "react-md": "^1.2.11",
   
thanks

**Comment by c0b41** [comment]
#358

**Comment by riazi** [comment]
@c0b41  i added  material design icon font in poroject and show correctly in my system but when   remote in my system dont see icon or in some system when run poroje dont show icon

**Comment by mlaursen** [comment]
The issue that @c0b41 linked is normally the root cause of icons not appearing, but you can also follow all the steps in the [with-create-react-app](https://github.com/mlaursen/react-md/tree/master/examples/with-create-react-app) example and apply the same logic to your project as needed. 

The most helpful section might be:
> Now that all the styles have been included, let's add the `Roboto` font and `material-icons` using the [webfontloader](https://github.com/typekit/webfontloader). First install `webfontloader`:
> 
> ```sh
> $ yarn add webfontloader
> ```
> 
> Next, update `src/index.js` to use the `webfontloader` to load the fonts:
> 
> ```diff
>  import React from 'react';
>  import ReactDOM from 'react-dom';
>  import './index.css';
>  import App from './App';
>  import registerServiceWorker from './registerServiceWorker';
> +import WebFontLoader from 'webfontloader';
> +
> +WebFontLoader.load({
> +  google: {
> +    families: ['Roboto:300,400,500,700', 'Material Icons'],
> +  },
> +});
>  
>  ReactDOM.render(<App />, document.getElementById('root'));
>  registerServiceWorker();
> ```
