### ISSUE TITLE
[Snackbar] TypeError: _props.toast is undefined when import single component

### ISSUE THREAD

**Issue by manhnt9** [mlaursen/react-md#736]
### Description
When importing with 
```javascript
import Snackbar from 'react-md/lib/Snackbars/Snackbar';
```
browser logs this error and the page doesn't load (blank)
```javascript
TypeError: _props.toast is undefined
```
but this bug isn't presented if I use
```javascript
 import { Snackbar } from 'react-md';
```
then the page loads and snackbar emits toast sucessfully.

### Version
- React - 15.5.4
- React-MD - 1.3.0
- Browser Firefox 59.0.2

**Comment by Kaishiyoku** [comment]
Same here. I'm getting this specific error message:
![chrome_2018-05-09_11-54-45](https://user-images.githubusercontent.com/5131112/39810176-56a97186-5384-11e8-9640-b0fa3aea1d2d.png)

**Comment by mlaursen** [comment]
Please see the [documentation notes](https://react-md.mlaursen.com/components/snackbars?tab=1#snackbar-proptypes)

>The Snackbar component is used for displaying a concise and small message to the user about an operation performed.
>
>The main component for the Snackbar is actually named the SnackbarContainer, so you need to make sure the import is react-md/lib/Snackbars or react-md/lib/Snackbars/SnackbarContainer. The first import is preferable.

**Comment by Kaishiyoku** [comment]
That worked, thank you.

**Comment by manhnt9** [comment]
Solved, I was importing with {}. Removing them corrects the problem.

Thank you very much!
