### ISSUE TITLE
There isn't possible to remove PasswordButton in TextField with type="password"

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#738]
In some cases I have to disallow showing up password by button. For example, someone has to sign in to application and his workmate or boss is behind him. He writes password, types TAB key and without notice what element is focused, press Enter. Instead of sign into application, his password is shown.

I can set password icon to null to hide PasswordButton, but it's still there and it can be clicked or focused.

**Comment by mlaursen** [comment]
I think I'll update it so that setting the `passwordIcon` to null will no longer render the show password button.

**Comment by chmiiller** [comment]
I'm having the same.
If I set `passwordIcon` to `null` it will hide the icon indeed but it would still be clickable =/

![pass](https://user-images.githubusercontent.com/1013632/41047251-6eb5270a-69ac-11e8-9cb5-c7e739ebfe13.gif)

**Comment by mlaursen** [comment]
Setting the `passwordIcon` to `null` will now correctly remove the password toggle button.

**Comment by chmiiller** [comment]
thanks!
