### ISSUE TITLE
[Date Picker] - Special characters appended to value in IE 11

### ISSUE THREAD

**Issue by dineshraghavan** [mlaursen/react-md#740]
### Description
While using date picker in IE 11, the selected date has special characters. You cant see in the console log but if you print the length, it has more than 10 characters. While sending the value in API request body, you could see the special characters get appended to the date string.

### Example
```javascript
2018?-?05-?11
```

### Temp solution
I came up with custom method on date selection

```javascript
  formatDate = (date) => {
    const dateExp = date.split('/');
    return `${dateExp[0].replace(/[^0-9]/g,"")}-${dateExp[1].replace(/[^0-9]/g,"")}-${dateExp[2].replace(/[^0-9]/g,"")}`
  }
```

### Version
- React - 16.3.1
- React-MD - 1.2.13
- Browser IE 11.0

**Comment by mlaursen** [comment]
Hmm, I could've sworn I patched that fix in.. Must've removed it during some of my date fixes that were implemented. Here is a function I've used in the past to remove the invisible characters that IE inserts into text fields:

```
/**
 * This will remove the invisible characters that IE inserts into text field values.
 * This makes it so that string.split('') will correctly do each character in the string
 * instead of including these hidden characters.
 */
export default function stripInvisibleCharacters(s) {
  return s.replace(/\u200e/g, '');
}
```

I'll look into patching this in though.
