### ISSUE TITLE
[TextField] - Required property does not get applied to the resulting input HTML element

### ISSUE THREAD

**Issue by alaney** [mlaursen/react-md#741]
### Description

When I use the `TextField` with the `required` property within a `form` element the form does not validate the field if it's empty. Upon further inspection it seems that the required attribute is not being applied to the `input` element in the DOM.

The issue can be reproduced on the form example for Text Fields in the React-MD Docs.
https://react-md.mlaursen.com/components/text-fields#form-example-and-misc
### Version
- React - 16.3
- React-MD - 1.3.1
- Browser - Chrome

**Comment by mlaursen** [comment]
Oof. Thanks! Should be fixed now.

**Comment by alaney** [comment]
Awesome!
