### ISSUE TITLE
[SelectField] - Required property does not get applied to the hidden input element.

### ISSUE THREAD

**Issue by jooleeunc** [mlaursen/react-md#743]
### Description
When the required property is added to SelectField, it does not get applied to the hidden input element. This bug causes form validation to pass even if nothing is entered for that field.

You will be able to see the issue in the required example on https://react-md.mlaursen.com/components/select-fields

### Version
- React - 16.2.0
- React-MD - 1.3.2
- Browser

**Comment by mlaursen** [comment]
Unfortunately this is not allowed: https://html.spec.whatwg.org/multipage/input.html#hidden-state-(type%3Dhidden)

This will most likely be fixed when I switch to a normal text input instead of a hidden one down the road

**Comment by sgarcia30** [comment]
Has this been resolved?
