### ISSUE TITLE
[Drawer] inline drawer doesnt show/hide

### ISSUE THREAD

**Issue by jairusd** [mlaursen/react-md#744]
### Description
I had a working drawer, but then i wanted it to be inline, it doesn't show/hide even after giving it true/false visible prop with onVisibilityChange prop
### Images/Screenshots
https://www.screencast.com/t/UTEksHhMQo
### Version
- React - 16.4.0
- React-MD - 1.3.2
- Browser

**Comment by mlaursen** [comment]
Right now this is intended behavior. The `inline` version is really just meant to be one of the permanent types without switching visibility. https://github.com/mlaursen/react-md/blob/a411c9f4a7be2b61fb3b17250d05654aa0a2471a/src/js/Drawers/Drawer.js#L765-L775

I'll think about adding visibility changes to the inline version

**Comment by jairusd** [comment]
Okay thanks for response. Will it be supported in the future? if not i'll just make my own workaround :)
