### ISSUE TITLE
React-MD project fail at bring up dev setup project

### ISSUE THREAD

**Issue by ntt2k** [mlaursen/react-md#748]
### Description
React-MD project fail at bring up dev setup project
I follow the "Minimal Setup" dev project steps to try to bring it up:

<img width="356" alt="screen shot 2018-05-29 at 12 49 48 pm" src="https://user-images.githubusercontent.com/4227421/40676144-7df500aa-633f-11e8-8b67-8d464d479bbb.png">

But I got these errors here -->

<img width="824" alt="screen shot 2018-05-29 at 12 55 27 pm" src="https://user-images.githubusercontent.com/4227421/40676195-a3ea0f30-633f-11e8-8883-4c99632b6358.png">

<img width="1171" alt="screen shot 2018-05-29 at 12 55 46 pm" src="https://user-images.githubusercontent.com/4227421/40676200-a86f0bdc-633f-11e8-9cbd-5099bf725a03.png">

 
### Link to a gist or code sample where the issue can be reproduced
------------------------------------------------------------
~/hobby_projects/react-md(master) » yarn dev                                                                                                
yarn run v1.3.2
$ npm-run-all -p build:watch docs
$ cd docs && npm run clean && npm run doc-dbs && npm-run-all -p start:dev watch:all
$ npm-run-all -p build:cjs:watch build:es:watch

> react-md-documentation@1.3.2 clean /Users/tnguyen/hobby_projects/react-md/docs
> npm-run-all -p clean:assets clean:dbs

$ npm run build:cjs -- -w
$ npm run build:es -- -w

> react-md-documentation@1.3.2 clean:assets /Users/tnguyen/hobby_projects/react-md/docs
> rimraf dist webpack-assets.json "public/!(robots.txt|react-md.png|favicon.ico)"

> react-md-documentation@1.3.2 clean:dbs /Users/tnguyen/hobby_projects/react-md/docs
> rimraf "src/server/databases/!(airQuality).json"

> react-md@1.3.2 build:cjs /Users/tnguyen/hobby_projects/react-md
> cross-env NODE_ENV=development BABEL_ENV=cjs babel src/js -d lib --ignore=__tests__,__mocks__ "-w"

> react-md@1.3.2 build:es /Users/tnguyen/hobby_projects/react-md
> cross-env NODE_ENV=development BABEL_ENV=es babel src/js -d es --ignore=__tests__,__mocks__ "-w"

> react-md-documentation@1.3.2 doc-dbs /Users/tnguyen/hobby_projects/react-md/docs
> npm run sassdoc && yarn run sassdoc:site && yarn run colors && npm run docgen && npm run examples-db

> react-md-documentation@1.3.2 sassdoc /Users/tnguyen/hobby_projects/react-md/docs
> babel-node src/scripts/createSassDoc.js

src/js/Autocompletes/Autocomplete.js -> es/Autocompletes/Autocomplete.js
src/js/Autocompletes/index.js -> es/Autocompletes/index.js
src/js/Autocompletes/Autocomplete.js -> lib/Autocompletes/Autocomplete.js
src/js/Autocompletes/index.js -> lib/Autocompletes/index.js
src/js/Avatars/Avatar.js -> es/Avatars/Avatar.js
src/js/Avatars/index.js -> es/Avatars/index.js
src/js/Avatars/Avatar.js -> lib/Avatars/Avatar.js
src/js/Avatars/index.js -> lib/Avatars/index.js
src/js/Badges/Badge.js -> es/Badges/Badge.js
src/js/Badges/index.js -> es/Badges/index.js
src/js/Badges/Badge.js -> lib/Badges/Badge.js
src/js/Badges/index.js -> lib/Badges/index.js
src/js/BottomNavigations/BottomNav.js -> es/BottomNavigations/BottomNav.js
src/js/BottomNavigations/BottomNav.js -> lib/BottomNavigations/BottomNav.js
src/js/BottomNavigations/BottomNavigation.js -> es/BottomNavigations/BottomNavigation.js
src/js/BottomNavigations/index.js -> es/BottomNavigations/index.js
module.js:557
    throw err;
    ^

Error: Cannot find module '../../..'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tnguyen/hobby_projects/react-md/docs/src/server/constants.js:3:1)
    at Module._compile (module.js:660:30)
    at loader (/Users/tnguyen/hobby_projects/react-md/docs/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tnguyen/hobby_projects/react-md/docs/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tnguyen/hobby_projects/react-md/docs/src/scripts/createSassDoc.js:7:1)
    at Module._compile (module.js:660:30)
    at loader (/Users/tnguyen/hobby_projects/react-md/docs/node_modules/babel-register/lib/node.js:144:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-md-documentation@1.3.2 sassdoc: `babel-node src/scripts/createSassDoc.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-md-documentation@1.3.2 sassdoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tnguyen/.npm/_logs/2018-05-29T17_51_12_476Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-md-documentation@1.3.2 doc-dbs: `npm run sassdoc && yarn run sassdoc:site && yarn run colors && npm run docgen && npm run examples-db`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-md-documentation@1.3.2 doc-dbs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tnguyen/.npm/_logs/2018-05-29T17_51_12_499Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "docs" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------------------------------------------------------------

### Version
- React-MD - 1.3.2

**Comment by ntt2k** [comment]
@mlaursen 
Thank you for the quick reply, please update document ... it will help devs that want to start to contribute.

**Comment by mlaursen** [comment]
Should be updated now. Sorry about that!
