### ISSUE TITLE
[SelectField] - Fractional numbers are not selectable

### ISSUE THREAD

**Issue by henry-young** [mlaursen/react-md#751]
### Description
The value of a number appears to be parsed as an integer before displaying the label.
For example: a value of 2.5 will show the label for a value of 2. 
The example below illustrates this.
### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/anon/pen/LrVmWO

### Version
- React - 16.4.0
- React-MD - 1.3.4
- Browser Chrome Version 66.0.3359.181

**Comment by mlaursen** [comment]
Thanks for the fix!
