### ISSUE TITLE
[TextField] Strange behavior of non-stateful right icon

### ISSUE THREAD

**Issue by bioslife** [mlaursen/react-md#762]
Is it correct, that I can't set properties like `disabled`, `primary` and etc. to right icon even when `rightIconStateful={false}`?

The causes of this behavior is obvious from this code:
```
return cloneElement(iconEl, {
        key: iconEl.key || `icon-${dir}`,
        disabled: stateful ? disabled : undefined,
        primary: stateful ? !error && active : undefined,
        error: stateful ? error : undefined,
        className: cn('md-text-field-icon', {
          'md-text-field-icon--positioned': !block,
        }, iconEl.props.className),
});
```

You can test that when you set any property to `undefined` during cloning of element, you just remove it. Compare the result of the following expressions:
`React.cloneElement(<span disabled={false}>Test</span>, { disabled: undefined })`
`React.cloneElement(<span disabled={false}>Test</span>)`

Maybe we should conditionally add properties if right icon is stateful instead setting that fields to `undefined`?

**Comment by mlaursen** [comment]
Yeah, that seems to be correct. It could probably change the `undefined` to `iconEl.props.disabled`, `iconEl.props.primary`, ...etc to fix that.
