### ISSUE TITLE
[Tabs] Tab indicator height cannot be overridden

### ISSUE THREAD

**Issue by doug2k1** [mlaursen/react-md#764]
### Description
The Sass variable `md-tab-indicator-height` seems to have no effect. The value of 2px is always set inline by this line of code:

https://github.com/mlaursen/react-md/blob/master/src/js/Tabs/TabIndicator.js#L19

There is a way to customize the tab indicator height?

### Version
- React - 16.4.1
- React-MD - 1.4.1
- Browser

**Comment by nielswh** [comment]
I'm also having the same issue. There looks to be inline style for the height in TabIndicator.  Anyway this could read in the value for md-tab-indicator-height instead of defaulting to 2?

**Comment by mlaursen** [comment]
There should now be a prop exposed in the `Tabs` component to fix this named `indicatorHeight` which defaults to `2`.
