### ISSUE TITLE
[ListItem] some Proptypes not working

### ISSUE THREAD

**Issue by geyuqiu** [mlaursen/react-md#767]
Some prototypes (on*) for ListItem are not working except onClick
https://react-md.mlaursen.com/components/lists?tab=1#list-item-proptypes

Is it planned to support, e.g. onKeyDown, onKeyUp, onMouseLeave, onMouseOver, onTouchEnd, onTouchStart

**Comment by mlaursen** [comment]
Hmm, let me look into that. They should definitely be supported

**Comment by mlaursen** [comment]
This seems to be working to me: https://codepen.io/mlaursen03/pen/eLJddP?editors=0010
