### ISSUE TITLE
[Autocompletes] Allow showing matches on focus with empty value

### ISSUE THREAD

**Issue by Xuecnahc** [mlaursen/react-md#781]
### Description

This is a suggestion to fit some use cases where we have an autocomplete with only few data.
Having a prop (defaulting to false) to show the matches on focus even with empty data would be helpful in my use-case.

Any though about it? Please feel free to reject to proposition if you think it will not be helpful.

The affected part would be the handle focus function:
```javascript
_handleFocus = (e) => {
   // [...]

   // Adding an extra flag to allow showing data with empty data
   const hasValidValue = !!value || showMatchesWithEmptyData;

   this.setState({
     matchIndex: -1,
     visible: !this.state.manualFocus && hasValidValue && !!this.state.matches.length,
     manualFocus: false,
     focus: true,
   });
 };
```

### Images/Screenshots
N/A

### Link to a gist or code sample where the issue can be reproduced
N/A

### Version
- React - *
- React-MD - ^1.5.0
- Browser - All

**Comment by mlaursen** [comment]
I think this would be a great addition, especially since I think it was referenced before (but I can't find the issue right now).

I would happily accept a PR for this since I'm spending most of my time working on my rewrite and next branch, but otherwise I can try to get this out by the end of next week.

**Comment by Xuecnahc** [comment]
Thank you a lot for your reply. I will provide the Pull Request when I will be able to work on it.

As it is my first Pull Request on the repository it will probably take a bit more time for the review. However it will be helpful for future ones.
