### ISSUE TITLE
Comparison with Material-UI

### ISSUE THREAD

**Issue by dandv** [mlaursen/react-md#784]
Thank you for publishing this library!

I wonder how it compares to @mui-org's [Material-UI](https://github.com/mui-org/material-ui). How should a developer decide between the two?

<sub>(I know this is a general question rather than an issue, but I believe the answer would be worth saving for future reference, or adding to the README. Thanks!)</sub>

**Comment by mlaursen** [comment]
See #555. I'll update the Readme to include this comparison as well

**Comment by dandv** [comment]
Thanks!
