### ISSUE TITLE
CalendarDate - buttons are missing the type attribute, and defaulting to 'submit'

### ISSUE THREAD

**Issue by jakerichan** [mlaursen/react-md#796]
### Description
This commit removed the `type='button'` attribute: https://github.com/mlaursen/react-md/commit/e27d7eb3d30b8c1025f1ddbb158521b33fa30660

Now if the picker component is contained within a form, it will automatically try to submit when a date is selected.

### Link to a gist or code sample where the issue can be reproduced
https://codepen.io/jakerichan/pen/xaWpgd?editors=1111

### Version
- React - 16.5.0
- React-MD - 1.5.1

**Comment by mlaursen** [comment]
This should be fixed with #797
