### ISSUE TITLE
[SelectField] - Update SelectField to use native select instead of hidden input

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#804]
The `SelectField` as of right now is kind of hacky since it is a combination of the `Menu` component for showing all the `<option>` and an`<input type="hidden">` to store the current value so that it can be submitted in forms. This _works_ as-is, but makes it harder for screen readers to understand this component and makes testing value changes pretty difficult.

To "test" a value change right now, you have to basically do a flow of:
- mount/render the `SelectField`
- find and click the `SelectFieldToggle` component (usually `${this.props.id}-toggle`)
- now that the options are visible, find the value you want to use by index or `data-value` and then click that item

Ideally you would be able to do `wrapper.find('#select-field-id').simulate('change', { value: 'some-value' });` but unfortunately an `<input type="hidden">` does not trigger a change event when the value is changed so I'm not sure if that will work.

If possible, it would be great to use a native `<select>` with `<option>` as children that can gain focus and change values natively but is hidden from the user. The user would still see the `<option>` as the `ListItem` component so it allows for more customization in styling since a native `<select>` can't (or is **extremely difficult to**) style.

I'm not if this solution will work yet though. If it doesn't, I can at least fix some of the accessibility concerns with the invalid `aria-` attributes that were applied to the different parts of the `SelectField`.

**Comment by hisapy** [comment]
Hey devs,

I've just found a _recipe_ that you might want to try to test your `SelectField`s' `onChange` handlers, with enzyme. 

Given that the signature of `SelectField`'s onChange  is `onChange(value, index, event, { id, name, value })`,  we can't rely on enzyme's `simulate(eventName, event)`, so instead of simulating the event, just call the handler directly:

```javascript
          wrapper.find(`SelectField#the_select`).prop("onChange")(
            testValue, // a variable holding your test value
            2, // the index of the option
            {}, // the event, 
            { id: "the_select", value: testValue }
          );

          // update wrapper with change
          wrapper.update()

          // Now expect/assert that something changed !
          expect(
            wrapper.find(FORM_SELECTOR).state('the_select')
          ).toEqual(testValue)
```

Have a nice year
