### ISSUE TITLE
[Chips] Add some space between tags input?

### ISSUE THREAD

**Issue by dandv** [mlaursen/react-md#811]
I'm looking for a tags input component and found [this demo on the Chips page](https://react-md.mlaursen.com/components/chips#with-text-fields). Looks pretty good. Would it help to add some space between tags?

![image](https://user-images.githubusercontent.com/33569/48816904-dc7ca180-ecf8-11e8-9d30-bd2758ac78bb.png)

StackExchange by comparison:

![image](https://user-images.githubusercontent.com/33569/48816921-f6b67f80-ecf8-11e8-94b6-256750f384a9.png)

**Comment by mlaursen** [comment]
Yeah, I can update the demo to have some spacing. I think I accidentally removed it at some point.. Whoops
