### ISSUE TITLE
[ExpansionList] Cannot conditionally have a ExpansionPanel in ExpansionList

### ISSUE THREAD

**Issue by daniel-rodrigue** [mlaursen/react-md#840]
**Describe the bug**
Inside a `ExpansionList`, cannot conditionally have an `ExpansionPanel` in it. This cause a javascript error in ExpansionList's `render()`.

**To Reproduce**
Render's code snippet:
```
<ExpansionList>
  {
    someFalseCond && <ExpansionPanel label="Crashed Panel">
      <div>OK!</div>
    </ExpansionPanel>
  }
  <ExpansionPanel label="Other Panel">
    <h1>Other things...</h1>
  </ExpansionPanel>
</ExpansionList>
```

**Expected behavior**
The fact that `someFalseCond` is false should not crash the ExpensionList's rendering.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: latest

**Additional context**
I tried with `false`, `null` and `undefined` for the condition and they all caused a JS error.

**Comment by mlaursen** [comment]
Ahh. I think this is because I expect valid react elements right now to clone in different props for a bad old practice/pattern. This should hopefully be easily fixable by filtering out false-ish values before attempting to clone them.
