### ISSUE TITLE
[ExpansionList] How to only have one Expansion Panel open at a time?

### ISSUE THREAD

**Issue by amitranjanthg** [mlaursen/react-md#857]
I want to close other panel opened when i click other Panel?Is there wany way i can implement now?

**Comment by amitranjanthg** [comment]
@dandv  @jcoffin  @depsypher

**Comment by zachsa** [comment]
Yes. You could, for example, have a stateful component (class or via hooks) that stores the index of the expanded panel.

The ExpansionPanel component has a property "expanded" that you can set explicitly to true or false depending on the index value in state. Then there is a property called "onExpandToggle" that accepts a callback that will fire on expansion toggle. The callback you define can set the state.

https://react-md.mlaursen.com/components/expansion-panels?tab=1#expansion-panel-proptypes-expanded

https://react-md.mlaursen.com/components/expansion-panels?tab=1#expansion-panel-proptypes-on-expand-toggle

**Comment by amitranjanthg** [comment]
i didn't get how that index will be set and callback function will be called?
please help me @zachsa 
import React, { Component } from 'react';
import { ExpansionList, ExpansionPanel } from 'react-md';
export default class Accordion extends Component{
    render(){
        const {data} =this.props;
        console.log('data',data);
        return(
            <ExpansionList>
                {faq.map((item,index)=>
                    <ExpansionPanel key={index} label={data.question} footer={null}>
                        <p>{data.answer}</p>
                    </ExpansionPanel>
                )}
            </ExpansionList>
        )
    }
}

**Comment by amitranjanthg** [comment]
@zachsa  i added key in expansionPanel but i don't know how to call onExpandToggle function?

**Comment by amitranjanthg** [comment]
```
import React, { Component } from 'react';
import { ExpansionList, ExpansionPanel } from 'react-md';
export default class Accordion extends Component{
    state={
        expand:null
    }
    check=(id)=>{
        console.log('checking',id);
        this.setState({expand:false});
    }
    render(){
        const {faq} =this.props;
        console.log('abcdefg',faq);
        return(
            <ExpansionList>
                {faq.map((item,index)=>
                    <ExpansionPanel key={index} label={item.question} footer={null} expanded={this.state.expand} onExpandToggle={()=>this.check(index)}>
                        <p>{item.answer}</p>
                    </ExpansionPanel>
                )}
            </ExpansionList>
        )
    }
}
```

**Comment by amitranjanthg** [comment]
I am calling a callback function but how will i close the particular index after toggling.
this.expand will go for all ExpansionPanel

@zachsa

**Comment by zachsa** [comment]
You are storing a boolean in state not the index.

**Comment by mlaursen** [comment]
Hi @amitranjanthg! As stated above, you can use the [expanded](https://react-md.mlaursen.com/components/expansion-panels?tab=1#expansion-panel-proptypes-expanded) prop along with the [onExpandToggle](https://react-md.mlaursen.com/components/expansion-panels?tab=1#expansion-panel-proptypes-on-expand-toggle) prop to make a fully controlled Expansion List/Panels. Here is a quick codesandbox showing how these two can be used together to allow only one panel to be expanded at a time: https://codesandbox.io/s/react-mdv1-only-one-expanded-panel-in-expansionlist-bid3v

However, in the future would you mind asking this sort of question in the [official slack channel](https://react-md.slack.com) instead? It'll help clear up the issue tracker for me and there is more information available on the [CONTRIBUTING.md](https://github.com/mlaursen/react-md/blob/master/.github/CONTRIBUTING.md#i-dont-want-to-read-the-whole-thing-i-just-want-to-ask-a-question) about getting a Slack invite.

**Comment by amitranjanthg** [comment]
Thanks @mlaursen .i didn't know about Slack.

**Comment by mlaursen** [comment]
No problem! It's really my fault since I haven't figured out a good way to publicize it due to being cheap and only getting 600 hours of hosting a month for the auto-inviter. If I make it more public, it'll run out within the first week due to bots.

**Comment by amitranjanthg** [comment]
you should move to discord

**Comment by amitranjanthg** [comment]
Hey For now Panel is opening from up to down i.e Font icon is from down to up.Can i change font icon from right to down.I tried putting <FontICon> in expander CallBack.but didn't worked ?
Can u help me @zachsa  @mlaursen
