### ISSUE TITLE
Failures on importing scss/react-md from node_modules

### ISSUE THREAD

**Issue by misolo** [mlaursen/react-md#870]
I'm using react-md, I built theme following this guide [here](https://react-md.mlaursen.com/customization/themes), but it fails many time on `File to import not found or unreadable`. 
I tried a lot to fixed it and google it and search in your documents but without any success
Please advice!

**To Reproduce**:

1. In a scss file write 
`@import '~react-md/src/scss/react-md';`
2. run `npm start` or `npm run build`
3. See error - not alway, sometimes yes and sometimes no:
```

00:10:32  Creating an optimized production build...
00:12:08  Failed to compile.
00:12:08  
00:12:08  ./src/theme/_globals.scss
00:12:08  Module build failed: 
00:12:08  @import 'components/lists';
00:12:08  ^
00:12:08        File to import not found or unreadable: {...}/node_modules/react-md/src/scss/components/_lists.scss.
00:12:08        in {...}/node_modules/react-md/src/scss/_react-md.scss (line 28, column 1)
```

- OS: ubuntu
- Browser: Chrome
- Version: latest

**Comment by mlaursen** [comment]
Can you provide a little bit more info for this to help debug? Are you using `create-react-app` for your project or something else? (what version of `create-react-app` if you are). Also, is this `react-md@1.16.0`?

I was able to get an app running with the following steps, but it is super barebones:

```sh
$ npx create-react-app my-new-react-md-app
$ cd my-new-react-md-app
$ npm install --save react-md
$ npm install --save-dev node-sass
```

Create a new `src/styles.scss`:

```diff
+@import '~react-md/src/scss/react-md';
+
+@include react-md-everything;
```

Update `src/index.js`

```diff
 import React from 'react';
 import ReactDOM from 'react-dom';
+import './styles.scss';
 import './index.css';
 import App from './App';
 import * as serviceWorker from './serviceWorker';
```

Finally start the app:

```sh
$ npm start
```

**Comment by misolo** [comment]
I'm using rejected create-react-app v1.0.0
webpack: 2.6.1
babel-core: 6.25.0
react-md: 1.16.0
node-sass: 4.12.0

Still fails

**Comment by mlaursen** [comment]
I think this is because `create-react-app`/`react-scripts` did not implement native Sass/SCSS support [until v2](https://create-react-app.dev/docs/adding-a-sass-stylesheet). It would be great if you could update to v2 or greater, otherwise you might be able to follow this old example before v2 was released: [with create-react-app v1](https://github.com/mlaursen/react-md/tree/v1/examples/with-create-react-app#react-md-with-create-react-app)
