### ISSUE TITLE
[Layout] "treeProps" does not render any nav items

### ISSUE THREAD

**Issue by Kaishiyoku** [mlaursen/react-md#878]
I'm currently following the steps at https://react-md.dev/guides/configuring-your-layout.

I have a component which renders the layout:

```es6
const MainLayout = (props) => {
    const {pathname} = useLocation();
    const navItems = {
        "/": createRoute("/", "Home", <HomeSVGIcon />),
        "/about": createRoute("/about", "About", <HelpSVGIcon/>),
    };

    return (
        <Layout
            treeProps={useLayoutNavigation(navItems, window.location.pathname)}
            appBarTitle="react-md App"
            navHeaderTitle="My App"
            title="Title"
        >
            <App/>
        </Layout>
    );
};
```

My createRoute function looks the same like in the documentation:

```es6
function createRoute(pathname, children, leftAddon, parentId) {
    return {
        itemId: pathname,
        parentId,
        to: pathname,
        children,
        leftAddon,
    };
}
```

There isn't rendered anything in the navigation drawer.

**Comment by mlaursen** [comment]
For the `createRoute` function, do you have a fallback value of `null` or is it `undefined` like the example above? I think it should render the tree correctly if you update it to be:

```diff
-function createRoute(pathname, children, leftAddon, parentId) {
+function createRoute(pathname, children, leftAddon, parentId = null) {
```

If that does work, I can explain _why_ that fixes it and also update the documentation to highlight this a bit more.

**Comment by Kaishiyoku** [comment]
@mlaursen that worked. I guess it has something to do with the Tree component children rendering logic?

**Comment by mlaursen** [comment]
Yeah, it's the [buildTree](https://github.com/mlaursen/react-md/blob/9aacba4a58a2f33ec3e22a0894258c5cdd6c088b/packages/tree/src/useNestedTreeList.ts#L24) and [useNestedTreeList](https://github.com/mlaursen/react-md/blob/9aacba4a58a2f33ec3e22a0894258c5cdd6c088b/packages/tree/src/useNestedTreeList.ts#L69) utils for building a tree list from an object. Since the `useNestedTreeList` defaults to having the `rootId` set to `null`, we also need the routes to have a default `rootId` (`parentId`) of `null` to render all the root level tree items/routes.

**Comment by Kaishiyoku** [comment]
Thank you for that really quick reply! :)

**Comment by mlaursen** [comment]
Just happened to be great timing that I checked this right as I was stopping work for the day :)

I've updated the docs to hopefully explain this a bit better as well as some outdated notes for adding a transition to the `Layout` component. Just let me know if I should try a different way of documenting this and I'll reopen this issue.
