### ISSUE TITLE
build error for live server

### ISSUE THREAD

**Issue by bill-oneil** [mlaursen/react-md#881]
When build for live server, compile error appeared
because of NavigationDrawer props.
            tabletDrawerType={NavigationDrawer.DrawerTypes.PERSISTENT_MINI}
            desktopDrawerType={NavigationDrawer.DrawerTypes.PERSISTENT_MINI}

**Comment by mlaursen** [comment]
Can you provide some more information? What is the compile error? What version of `react-md`?

**Comment by bill-oneil** [comment]
Sorry for response late. That is With-router-4 example of react-md version1.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
